### ISSUE TITLE
Several tiles from 20230303 have large SKYCHI2PDF (and bright sframesky)

### ISSUE THREAD

**Issue by dstndstn** [desihub/desisurveyops#102]
Tiles
- 20605
- 20606
- 21319
- 21337
- 22860
- 23756

all show this pattern
<img width="963" alt="1" src="https://user-images.githubusercontent.com/1065981/222927021-db7087b6-b217-422d-9bb9-2887d2570f71.png">

These tiles were observed in contiguous exposure numbers (169592 through 169598).  The weather and conditions were not remarkable during that time.  They're not closer to the moon than other exposures from this night.

**Comment by schlafly** [comment]
That's the right call.  IMO, 21319 and 23756 redshifts look fine (the first and last in this period).  We need to mark the others as bad and reprocess.  I agree with you that I don't why these look so much worse given the similar sky level.  There were some clouds at the beginning of the night that I would have blamed, but they don't look relevant for these exposures.

**Comment by dstndstn** [comment]
Done!

**Comment by schlafly** [comment]
We need to mark:
tileid, night, exposures
20605, 20230303, 169597
20606, 20230303, 169596
21337, 20230303, 169595
22860, 20230303, 169593-169594
as bad and reprocess.  @abhi0395 ?  Thank you!

**Comment by schlafly** [comment]
@abhi0395 , @akremin , can we mark these as bad?  Thanks!

**Comment by schlafly** [comment]
Thanks!  I've cleared QA on these and am closing.
