### ISSUE TITLE
Tile 11445, 2023-02-27 has a bright star on p8

### ISSUE THREAD

**Issue by dstndstn** [desihub/desisurveyops#103]
Bright star seems to mess up the redshift distribution on petal 8 a bit.

<img width="1330" alt="1" src="https://user-images.githubusercontent.com/1065981/222988302-c91ff7bc-5795-48ab-9558-f3eef1b2c0e4.png">

![tile-qa-11445-thru20230227](https://user-images.githubusercontent.com/1065981/222988313-7f6ad48a-b180-4649-b60a-759ab0c90641.png)

**Comment by araichoor** [comment]
if I m correct: that s `FIBER=4367`: that s a stuck fiber on a g~9 mag star; maybe it s a consequence of the updated positions in the focal plane model for the stuck positioners, which requires us to re-nudge the tile centers? (https://desisurvey.slack.com/archives/C01HNN87Y7J/p1675708825837509)

<img width="1382" alt="Screenshot 2023-03-05 at 2 14 41 PM" src="https://user-images.githubusercontent.com/61986357/222988877-cf546be7-9800-4dee-9f24-54c3d98ccf96.png">
https://www.legacysurvey.org/viewer-desi/?ra=201.6342&dec=6.4226&layer=ls-dr9&zoom=14&desifoot=200.5660,6.4880&catalog=tmpob40qn31

**Comment by schlafly** [comment]
This messed up redshifts on this petal.  P8 on tileid 11445, 20230227/169151 needs to be marked bad, the tile reprocessed.  Then we can repeat QA.  @abhi0395 ?  Thank you!

**Comment by schlafly** [comment]
@abhi0395 , @akremin , can we reprocess this one?  Thanks!

**Comment by abhi0395** [comment]
Hi @schlafly, Thanks for reminding me! I have marked the P8 as bad for 11445, 20230227/169151 and reprocessed it. The updated nightqa is also available now. Please have a look, and if things look fine, please feel free to close the issue!

**Comment by schlafly** [comment]
Something looks wrong here.
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/11445/20230227/tile-qa-11445-thru20230227.png
I think I expected just the one tile to be bad, but every single fiber looks like it was marked bad on all petals?
![image](https://github.com/desihub/desisurveyops/assets/1417841/318dc722-7dc0-41e9-a276-c113cb0a4c76)

**Comment by araichoor** [comment]
I think that, for whatever reason, the exposure-qa files have not been properly computed, i.e. it was generated with EFFTIME_SPEC=0 for all fibers by some failed run, but not deleted; so the subsequent correct run did not overwrite those exposure-qa-EXPID.fits files; and that propagates into the tile-qa*fits file.

I ve sorted things out with @abhi0395.

details, for the record:
I see that the `exposure-qa-0016915{0,1}.fits` files have EFFTIME_SPEC=0 for all fibers:
```
>>> d = Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20230227/00169150/exposure-qa-00169150.fits", "FIBERQA")
>>> d["EFFTIME_SPEC"].max()
0.0
>>> d = Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20230227/00169151/exposure-qa-00169151.fits", "FIBERQA")
>>> d["EFFTIME_SPEC"].max()
0.0
```

and I also notice that those files have the earliest timestamp for both folders, whereas they should be the latest files:
```
raichoor@perlmutter:login04:~> ls -tlrh /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20230227/00169150/ | head -n 3
total 5.9G
-rw-r----- 1 desi desi  442K May 16 13:28 exposure-qa-00169150.fits
-rw-r----- 1 desi desi  540K May 16 13:39 psf-b6-00169150.fits
raichoor@perlmutter:login04:~> ls -tlrh /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20230227/00169151/ | head -n 3
total 5.3G
-rw-r----- 1 desi desi  442K May 16 13:28 exposure-qa-00169151.fits
-rw-r----- 1 desi desi  540K May 16 13:40 psf-b7-00169151.fits
```

**Comment by araichoor** [comment]
remark: I think it s not the first time that this happens.

@akremin , @sbailey: maybe it would make sense to add in the desispec procedure, when you re-generate some exposures (or a tile), a small piece of code to delete any existing exposure-qa-EXPID.fits if it s going to be computed.
also note that `desi_exposure_qa` has a `--recompute` argument; so maybe using that argument could also be an option.

sorry, I m not familiar with those resubmit scripts, so I cannot quickly point where that would be..

**Comment by akremin** [comment]
The standard procedure for flagging a petal is to remove the offending
exposure and reprocess it. So this should never happen during normal
operations. This particular case is likely just a mixup.

In general, we never delete files as part of the pipeline in the spirit
that we as humans should be doing that and because if we rerun a job that
crashed due to e.g. slow I/O we don't want it redoing all of the
computations it already completed successfully. We could revisit that
stance for a subset of QA files such as this one.

**Comment by abhi0395** [comment]
Thanks, @araichoor, for your help in identifying the issue quickly. I have rerun the tile and recomputed the tsnr and nightqa again. @schlafly, please have a look. There were some problems with the slurm jobs that needed some manual fixes, and @sbailey helped with that. 

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/11445/20230227/tile-qa-11445-thru20230227.png
![tile-qa-11445-thru20230227](https://github.com/desihub/desisurveyops/assets/48716090/c3c9d204-b315-40cf-a1c4-ef8b61abacae)

**Comment by akremin** [comment]
For the record, Abhijeet followed the standard operating procedures perfectly. There is a missing input file check in the pipeline that allowed this to occur under a very specific set of conditions brought on by a NERSC bug. The file check will be added, and hopefully so will the NERSC bug.

**Comment by araichoor** [comment]
ok perfect, no code change then! thanks for the investigation!

@schlafly: I see you requested to mark petal=8 as bad only for expid=169151 => was there a reason to not also request that for expid=169150? (I ve not looked at the data..)(and sorry I didn t ask before).

**Comment by schlafly** [comment]
Ugh, no!  Sorry, I hadn't appreciated that this was a split exposure.  @abhi0395 , can we also mark
P8, 11445, 20230227/169150
as bad, and re-reprocess?  Sorry!

**Comment by abhi0395** [comment]
@schlafly thanks, yes, I will mark P8 as bad for expid 169150 as well and reprocess the tile.

**Comment by abhi0395** [comment]
@schlafly I have marked p8 bad on 169150 as well and reprocessed 11445. The updated tsnr and nightqa are available now. Please have a look, and if things appear fine, please feel free to close the issue!

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/11445/20230227/tile-qa-11445-thru20230227.png

**Comment by schlafly** [comment]
Thanks.  This looks good, thank you, closing!
