### ISSUE TITLE
issues in data processing for 20230309 night

### ISSUE THREAD

**Issue by abhi0395** [desihub/desisurveyops#105]
Hi all,
I opened a ticket on desispec about issues in data processing of 20230309 night! I am referencing the issue here as well:

https://github.com/desihub/desispec/issues/2023

**Comment by schlafly** [comment]
Hi Abhijeet,

We'll need to mark these as bad and reprocess.  Let's only mark the DESI-II special tiles and the tiles observed before that, and not the backup tiles or bright tiles observed afterward; those look minimally affected to my eyes given the brighter sources.

Affected expid are 170813-170839.
Affected tileid are 8629, 10238, 11775, 26084, 83243, 83244, 83245, 83246.

Let me know when this is done and I'll mark clear the current "unsure" status in tiles-specstatus.

**Comment by abhi0395** [comment]
Thanks @schlafly for your comments! I'll reprocess the night with appropriate flags as you have mentioned!

**Comment by abhi0395** [comment]
Hi @schlafly I flagged those exposures and purged affected tiles. The reprocessed tsnr and nightqa is available now. If you feel the night is done, please close the issue!

**Comment by schlafly** [comment]
QA cleared, closing, sorry for the delay!
