### ISSUE TITLE
Tiles 7238 and  8796 are 3-sigma outliers in new Lya QSOs

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#106]
Inspecting tile-qa from 20230326 I've found that tiles 7238 and  8796 are 3-sigma outliers in new Lya QSOs. I've marked those two tiles as unsure, waiting for more feedback from the SurveyOps team.
<img width="612" alt="Captura de Pantalla 2023-03-27 a la(s) 2 45 32 p  m" src="https://user-images.githubusercontent.com/1848618/228052253-f36673c0-bd74-44ad-809f-406786d35b65.png">

The tile QA does not look suspicious, except for the bright star on tile 8796.

<img width="1191" alt="Captura de Pantalla 2023-03-27 a la(s) 1 45 31 p  m" src="https://user-images.githubusercontent.com/1848618/228052330-e68a6f54-cde2-4a6f-be8c-07f1d083c9e3.png">

<img width="1195" alt="Captura de Pantalla 2023-03-27 a la(s) 1 45 42 p  m" src="https://user-images.githubusercontent.com/1848618/228052319-b3510011-3991-4ad0-83d6-bf2fd0c715c2.png">

**Comment by forero** [comment]
@ashleyjross commented on slack " the tile qa looks fine for these, they are almost definitely ok. (Anything with n_overlapping > 5 is usually fine.)". Closing this issue.

**Comment by araichoor** [comment]
those are the "usual" case for tiles with high previous coverage, hence few new lyas, hence more scatter.
the general rule is that, as long as the error bar is overlapping the 3sigma red shaded region, it s good.

confirming Ashley s comment, here are the newlya spectra for those two tiles, which look good:
https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/tmp-daily-newlya-7238-thru20230326.pdf
https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/tmp-daily-newlya-8796-thru20230326.pdf

ps: I really need to push that script to desisurveyops (or desispec); sorry!
