### ISSUE TITLE
Lower than average good redshift statistics in petal 1 on 20230414; several tiles marked unsure.

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#111]
The redshift success rate in petal 1 seems noticeably lower than usual for several tiles on 20230414. Some tiles have what looks like a pileup of redshifts at z~1.3 in petal 1.
* Exp 176358, tile 2693, marked **unsure**.
* Exp 176350, 176351, tile 2845, marked **unsure**.
* Exp 176357, tile 3647, marked **unsure**.
* Exp 176343, tile 5658, marked **unsure**.
* Exp 176367, tile 5915, marked **unsure**.
* Exp 176369, tile 5958, marked **unsure**.
* Exp 176359, tile 9410, a bit borderline and also BSKYTHRURMS=0.051 warning for petal 9, but marked **good**.
* Exp 176355, tile 9889, marked **unsure**.
* Exp 176370, tile 25110, marked **unsure**.

![Screen Shot 2023-04-15 at 4 20 00 PM](https://user-images.githubusercontent.com/7385438/232251587-4b62fc46-ab03-49b2-acbb-6148fcb62aaa.png)
![Screen Shot 2023-04-15 at 4 25 54 PM](https://user-images.githubusercontent.com/7385438/232251787-4522edc8-3363-46f2-b98d-280d6054a971.png)
![Screen Shot 2023-04-15 at 4 28 04 PM](https://user-images.githubusercontent.com/7385438/232251849-95d5b4b2-4c70-42b3-a929-0f655ac23156.png)
![Screen Shot 2023-04-15 at 4 30 15 PM](https://user-images.githubusercontent.com/7385438/232251917-6cc10c17-781e-4344-b6b9-a8f2910d970e.png)
![Screen Shot 2023-04-15 at 4 31 58 PM](https://user-images.githubusercontent.com/7385438/232251981-286b30e4-2a9e-4e69-92e5-aa6279af203d.png)
![Screen Shot 2023-04-15 at 4 33 15 PM](https://user-images.githubusercontent.com/7385438/232252087-eadd644b-d5d8-424e-88c8-5c755200695f.png)
![Screen Shot 2023-04-15 at 4 38 37 PM](https://user-images.githubusercontent.com/7385438/232252258-6e908d80-f208-448d-b7ae-d85a3b584faa.png)
![Screen Shot 2023-04-15 at 4 41 00 PM](https://user-images.githubusercontent.com/7385438/232252325-26053909-4895-4762-9c62-61534ffb2ab3.png)

**Comment by araichoor** [comment]
I ve looked a bit at tileid=2693, and couldn t find anything obvious...
except maybe one thing: for the sky fibers, it looks like the sky emission lines "forest" at ~9500A is ill-subtracted (maybe due to some wavelength miscalibration?), resulting either in an excess or a drop of flux, which is interpreted by redrock as a positive/negative 4000 A balmer break at z ~1.3, 1.4.
e.g.
<img width="1375" alt="Screenshot 2023-04-15 at 2 41 36 PM" src="https://user-images.githubusercontent.com/61986357/232254336-274766f3-ce72-4b41-a88a-3da1ec72d6d2.png">

here are the 100 petal_loc=1 sky fibers: https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/tmp-2693-thru20230414-sky-pet1.pdf.
and for comparison here the 66 petal_loc=0 sky fibers: https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/tmp-2693-thru20230414-sky-pet0.pdf.

**Comment by araichoor** [comment]
thanks @schlafly for precising your thought on slack.

to visualize the effect, I ve (ivar-weighted-)stacked the sky fibers per 250 fibers, for all maindark tiles of 20230414.
the effect on petal1 is as you predicted, I think, with being bad in both "amps", in the red part of the z-camera:
![tmp-sky-maindark-thru20230414-petal1](https://user-images.githubusercontent.com/61986357/232265887-1893e146-b56c-4a3f-9a1f-1583af066f15.png)

but what worries me a bit is that it looks like we such an effect for ~all cameras and ~all petals (of course with the effect being more or less strong; but it is strong in many cases).
see this pdf: [tmp-sky-maindark-thru20230414.pdf](https://github.com/desihub/desisurveyops/files/11241195/tmp-sky-maindark-thru20230414.pdf)

note that with our simple lbg sims, with @julienguy, we think we see the impact of this effect on redrock performances; see slides 17-20 of the Napa meeting: https://desi.lbl.gov/DocDB/cgi-bin/private/RetrieveFile?docid=7449;filename=desi-2-redshif-efficiency-and-redrock-improvements-v1.pdf
I know it s understudy to absorb such an effect in the redrock fitting, but maybe it could be "fixed" earlier in the pipeline?
like at the sky fitting level, with doing something like forcing median(flux) = 0 per half-camera per sky fibers in batch of 250 fiber numbers? (though the stats may be low).

**Comment by schlafly** [comment]
Thanks for this.  I was imagining that the feature at ~8700A in your plot corresponds to an amp boundary.

You also see something on z3, which is something I've noticed in the sframe residuals as well.  The r1 and r6 amp issues are new to me and I don't know why I can't see them on the sframe residuals.

**Comment by schlafly** [comment]
Here's another visualization of 20230414/00176349 z1.
![image](https://user-images.githubusercontent.com/1417841/232515159-36a77fd3-7f71-44be-a293-fcaaf2580199.png)
The residuals are really more of a checkerboard than a linear trend across the bad CTE region.  Maybe we can just add a second CTE sector on the other half of z3 to mostly null this.

**Comment by araichoor** [comment]
thanks for following up.
- re-z1: seeing your plot, and looking back at mine, it looks that effect is bimodal for the "second amp", ie there are two regions, approx. 1500<pixels<2250 and 2250<pixel<3000 (that s what you refer to as "checkerboard", right?) => would we know the (instrumental) reason for that?
- "_Maybe we can just add a second CTE sector on the other half of z3 to mostly null this._" => you mean z1, right?
- re-r1, r6: if you look hard, you can see that r1 is stripey; for r6, I agree I don t see anything in the sframesky images; I ll dig a bit in that.

**Comment by schlafly** [comment]
I don't know the reason for this.  And I'm being dumb; we can't just add another sector; we can currently only add sectors in the fiber number direction and not in the wavelength direction.  No, I don't understand what would make things look this way instrumentally.  But it doesn't look strongly coupled to the behavior of the sky to me.

Yes, sorry, z3 is the other spectrograph I worry about.  I meant z1.  Your PDF doesn't really look stripey, though.

**Comment by araichoor** [comment]
re-r1: here s the sframesky pdf file, with narrowing the colorbar range (from -100,100 to -25,25): https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/sframesky-20230414-clim25.pdf
hopefully it makes the stripeyness a bit more visible; you can "catch" the feature on expid=176342, then see it in the other exposures.

btw, I see there that r8 (blue side) also has some stripey behaviour; see e.g. expid=176357, but it s visible in ~half of the exposures; and in my tmp-sky-maindark-thru20230414.pdf plot, the spectra have a funky shape in this region, with a similar bi-modal behavior; though the amplitude is rather small.

**Comment by schlafly** [comment]
Sorry, I agree that r1 is stripey; I don't like that explanation for your plot here:
![image](https://user-images.githubusercontent.com/1417841/232534749-c5570258-1be4-48c7-9714-0268ebfdc8b0.png)
because that doesn't look very stripey-like?

**Comment by araichoor** [comment]
maybe the "stripey-ness" is on top of an offset? e.g. in expid=176349, I can see this offset in r1.

**Comment by schlafly** [comment]
These got reprocessed as part of the CTE work and should now be good.  I've now marked them as good and am marking this as resolved.
