### ISSUE TITLE
Tileid=4542 has a suspicious accumulation of z~0.9328 redshifts

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#118]
during qa, I ve set this tile as "unsure" because of this horizontal pattern in the Z vs. FIBER plot:
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/4542/20230520/tile-qa-4542-thru20230520.png
![tile-qa-4542-thru20230520](https://github.com/desihub/desisurveyops/assets/61986357/9e2ee31e-683a-4e8d-bd20-0bcf4afbec1d)

I think the reason is probably linked to the fact that this tile was design eight months ago, in Sep. 2022, as it got an efftime=0 exposure on 20220923 (took me a while to identify that!):
```
 NIGHT   EXPID  TILEID EFFTIME_SPEC
-------- ------ ------ ------------
20220923 144017   4542          0.0
20230519 181421   4542        345.3
20230520 181544   4542        634.3
```
the focal plane then had 20 less stuck fibers (788 vs. 807), and it s likely also that some of those stuck fibers have been moved since with some engineering work.
I didn t have time to investigate further to fully convince myself that it explains what we see (though I think it does).
I ll get back to this next week.

**Comment by schlafly** [comment]
This got ~inadvertently marked good and committed to the MTL on 20230616, together with 22035.  I think these are probably fine so we don't care, but that increases the urgency to resolve this issue somewhat.
