### ISSUE TITLE
Garbage redshifts on P4 on tile 10357

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#12]
P4 shows clear pileups of garbage redshifts around z=0.25 and z=0.5.
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/10357/20211210/tile-qa-10357-thru20211210.png

This doesn't look like it affects LyA and I will mark it good.  

I am having trouble seeing what is causing them; the sframe files look pretty good.
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20211210/sframesky-20211210.pdf

**Comment by julienguy** [comment]
Very likely due to b4 bias instability.
![Screenshot from 2022-08-18 08-52-16](https://user-images.githubusercontent.com/5192160/185440461-501c4b2b-55f5-49f8-9211-97dc843ce349.png)
```
plot_frame -i ~/redux/daily/exposures/20211210/00113301/sframe-b4-00113301.fits --sky-fibers --rebin 64
```
![Screenshot from 2022-08-18 08-53-39](https://user-images.githubusercontent.com/5192160/185440615-23c4f627-6abd-4eb0-b183-b73dd565f4ce.png)

**Comment by schlafly** [comment]
Reviewing the nightqa on this one, all of these dark tiles show these features.
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20211210/tileqa-20211210.pdf
so it isn't the case, as I had previously believed, that this tile is much worse than the others on the night (the b4 instability has similar amplitude to my eyes throughout the night, but that makes sense now).

Would we want to mark as bad, reprocess, and re-incorporate into the MTL?  The redshifts are pretty compromised.

**Comment by julienguy** [comment]
Note that we now have in place the preprocessing option `--bkgsub-for-science` for all blue CCDs. It was not in place when this night was run as part of the daily processing. It would be interesting to rerun this night. I think it should be scheduled for the himalayas run.

**Comment by schlafly** [comment]
As @julienguy predicted, the iron reductions address this due to bkgsub-for-science.  Thanks to @araichoor for running tileqa for these.
https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/nightqa_20211210_iron/tileqa-20211210.pdf
https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/nightqa_20211210_iron/sframesky-20211210.pdf
b4 sframes look immaculate with this change.  Closing.

**Comment by araichoor** [comment]
for posterity, as I cannot guarantee those tmpdir files will last:
those have been generated with (from an interactive node):
```
desi_night_qa -p /global/cfs/cdirs/desi/spectro/redux/iron -n 20211210 -g cumulative -o /global/cfs/cdirs/desi/users/raichoor/tmpdir/nightqa_20211210_iron --nproc 64 --steps sframesky,tileqa
```

and here are the plots:
<img width="1246" alt="Screenshot 2023-03-01 at 2 36 07 PM" src="https://user-images.githubusercontent.com/61986357/222281505-050eaf32-61db-4824-813b-603ada3b88e6.png">
<img width="1162" alt="Screenshot 2023-03-01 at 2 36 40 PM" src="https://user-images.githubusercontent.com/61986357/222281478-9b87dc29-d732-42a3-bc08-0e83c4cc3e1b.png">
<img width="1160" alt="Screenshot 2023-03-01 at 2 36 32 PM" src="https://user-images.githubusercontent.com/61986357/222281498-a19ee75a-2268-4113-ad38-15f39cb93d9b.png">
