### ISSUE TITLE
TILEIDS 4390, 4563, 4549, 4535, 8153 with a large fraction of LRGs with z=0.0

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#120]
On the night 20230609 we observed 20 dark tiles, during QA I marked five of those (TILEIDS 4390, 4563, 4549, 4535, 8153) as unsure. The reason is that, in my opinion, there seems to be an unusual large fraction of LRGs with z=0.0. TILEID 8153 looks extreme.

<img width="1317" alt="unsure 4563" src="https://github.com/desihub/desisurveyops/assets/1848618/7e08fc2f-3274-45ee-9a46-715d4b419449">
<img width="1309" alt="unsure 4549" src="https://github.com/desihub/desisurveyops/assets/1848618/2fea5665-decc-4029-9a6b-44bcb7481059">
<img width="1293" alt="unsure 4535" src="https://github.com/desihub/desisurveyops/assets/1848618/c65fd3de-e197-4d36-b7aa-1c7ec364ea9a">
<img width="1305" alt="unsure 8153" src="https://github.com/desihub/desisurveyops/assets/1848618/639de782-a839-4970-b05c-e3c657eea4d5">
<img width="1300" alt="unsure 4390" src="https://github.com/desihub/desisurveyops/assets/1848618/7302819f-430b-42df-927d-3ff329850be0">

**Comment by araichoor** [comment]
great you caught those -- this z~0 spike in the n(z) are not easily spottable...

for what is worth: I suspect it is the same thing as reported here https://desisurvey.slack.com/archives/C01HNN87Y7J/p1684712775285589, ie artefacts along the wise star spikes.
those tiles all are kind of close to the galactic plane

I don t have time now to check it myself; but what I would do to double-check is to grab all the z~0 lrgs in those tiles, and dump them in the viewer, and check against the wise imaging.

**Comment by forero** [comment]
Doing the check that Anand suggested, it does look like that most of these  z~0 come from artifacts around the bright stars
These are some results from TILEID 8153
![Captura de Pantalla 2023-06-16 a la(s) 10 17 09 a  m](https://github.com/desihub/desisurveyops/assets/1848618/3179e97f-14e9-4061-96b0-372140ae24e6)

![Captura de Pantalla 2023-06-16 a la(s) 10 16 41 a  m](https://github.com/desihub/desisurveyops/assets/1848618/2a23517c-824c-48aa-b1e4-7ff33afe61eb)


![Captura de Pantalla 2023-06-16 a la(s) 10 17 29 a  m](https://github.com/desihub/desisurveyops/assets/1848618/11b2c247-9eaf-4bdb-9acc-5e8c1ca4104d)

**Comment by forero** [comment]
Example from TILEID 4390

![Captura de Pantalla 2023-06-16 a la(s) 10 28 34 a  m](https://github.com/desihub/desisurveyops/assets/1848618/1b8d760f-f7e8-4c1c-a216-349598a4f0a2)

**Comment by schlafly** [comment]
Great.  Can you update these to have good QA, and close?  Thanks!

**Comment by forero** [comment]
Jose updated this tiles to have good QA. Closing now.
