### ISSUE TITLE
Many fibers with LOWEFFTIME in petal 9 for TILEID = 3297

### ISSUE THREAD

**Issue by jose-bermejo** [desihub/desisurveyops#121]
<img width="961" alt="Screen Shot 2023-06-15 at 12 53 50 PM" src="https://github.com/desihub/desisurveyops/assets/50589102/5adc99c4-3174-4c4f-a769-03230250f2c6">

I marked as unsure tile 3297 as it presents a lot of fibers with LOWEFFTIME accumulated in petal 9.

**Comment by schlafly** [comment]
This is usually because the calibration stars preferentially sample areas where the fiber positioning is poor, leading to a low THRUFRAC and therefore low EFFTIME.  These are okay to mark as good.
