### ISSUE TITLE
Tile 25564 has a lot of LOWEFFTIME and QAFIBERSTATUS > 0 fibers for petals 4 and 5

### ISSUE THREAD

**Issue by jose-bermejo** [desihub/desisurveyops#122]
<img width="965" alt="Screen Shot 2023-06-15 at 1 08 16 PM" src="https://github.com/desihub/desisurveyops/assets/50589102/4e53301d-6996-44a2-a3f7-d03504865b3f">

I marked this tile as unsure due to the strange behavior of petals 4 and 5

**Comment by araichoor** [comment]
I ll mark it as good.

this is typical when some previous observations are missing some petals.
here, expid=152192 from 20221106 was missing those petals=4 and 5:
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/25564/20221106/tile-qa-25564-thru20221106.png.
<img width="1382" alt="Screenshot 2023-06-15 at 10 17 07 AM" src="https://github.com/desihub/desisurveyops/assets/61986357/414b6e4c-4043-44a0-bb61-2539437b3413">

so when the two exposures are coadded, those petals=4 and 5 only have observation from the second exposure, and are thus short of efftime.

**Comment by schlafly** [comment]
Just repeating what Anand said, go ahead and mark this one as good Jose.  Thanks!

**Comment by jose-bermejo** [comment]
Thank you Anand and Eddie for double checking. I changed the status to good
