### ISSUE TITLE
Unstable amplifier on r4 on 20230615

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#123]
r4 was unstable due to an FEE reset on 20230615.  24909 was affected but was marked good and incorporated into the MTL.  Possibly only half the chip is affected.  We should mark the affected petal or amplifier as bad and reprocess and reincorporate into the MTL.

**Comment by araichoor** [comment]
for completeness:
we also marked as "unsure" tiles corresponding to 9 exposures on 20230618, taken after a similar event:
```
 22:34 [05:34] CCDS4Z failure. Recovery procedure didn't work.; AlarmID: 2003; Action: Klaus power cycled the FEE. (LO)
```
expid=185816 is the first exposure after the recovery: one of the r4 amplifiers is clearly affected
<img width="840" alt="Screenshot 2023-06-19 at 8 55 56 AM" src="https://github.com/desihub/desisurveyops/assets/61986357/e6e556cf-6579-459d-9b05-b6648a2d98e8">
the effect then decreases for the subsequent exposures; we conservatively set 9 exposures as "unsure", and will perform a finer diagnosis on those.
```
# EXPID TILEID
185816	10621	
185817	7509
185818	7511
185819	9597
185820	7510
185821	7519
185822	9227
185823	6111
185824	5039
```

**Comment by schlafly** [comment]
Let's r4 bad on 20230615, expid 185436 - 185440, which corresponds to tileid 24909, 83380, 83381, 9051.  The main survey tiles would need to be reprocessed in a special way because these have been incorporated into the MTL (@sbailey).  The tertiary tiles (83380, 83381) would not need that treatment.

**Comment by schlafly** [comment]
@akremin , @marcelo-alvarez , @abhi0395 , anyone able to mark r4 as bad on expid 185436 - 185440?  Then @geordie666 will have to rearchive & readd to the MTLs.

**Comment by schlafly** [comment]
Pinging this ticket.

**Comment by abhi0395** [comment]
@schlafly Re-processed and tsnr+nightqa updated

**Comment by schlafly** [comment]
This looks good to me.  They are likewise good in the spec status (which is why they made it to the MTLs), so I think there's nothing for me to do here and it's over to @sbailey for rearchiving 24909 and 9051.

**Comment by sbailey** [comment]
@schlafly @geordie666 I have re-archived tiles 24909 and 9051 with
```
desi_archive_tilenight -n 20230615 -t 24909 --rearchive
desi_archive_tilenight -n 20230615 -t 9051 --badpetals 4 --rearchive
```
The reason that 24909 does not need `--badpetals 4` is because it was also observed on 20230529 including r4, so there is a zmtl-4*.fits .

Passing off to @geordie666 for MTL update.

**Comment by geordie666** [comment]
Tiles `24909` and `9051` have been re-updated in the MTL ledgers.
