### ISSUE TITLE
r4 amplifier issue on 20230618

### ISSUE THREAD

**Issue by LNapolitano** [desihub/desisurveyops#124]
r4 was again unstable due to an FEE reset on 20230618. This issue covers exposures 185816 - 185824 and as a result tiles [5039, 6111, 7509, 7510, 7511, 7519, 9227, 9597, 10621] have been marked unsure. The effect is strongest at exposure 185816 and becomes less evident in later exposures.

**Comment by schlafly** [comment]
@ashleyjross , want to try to assess where we should draw the line on this one?  The unstable amplifiers are barely bad by eye out to 185824, which is where we've currently marked unsure to.  But e.g. the redshifts for 185819 still look fine to me, so perhaps I'm being too stringent.  But maybe my eye isn't sensitive enough and we should be masking more.  Can you say something more quantitive?  Thanks!

**Comment by ashleyjross** [comment]
Tile 9227, expid 185822, does have suspiciously low LRG success (93%), so masking r4 out to where you marked unsure might make the most sense.

**Comment by schlafly** [comment]
Okay, let's mark r4 as bad for 185816-185824 and reprocess.  These aren't in the MTL and so these would follow our usual reprocessing mode.  @abhi0395 or @marcelo-alvarez , maybe?

**Comment by schlafly** [comment]
Pinging this ticket.

**Comment by abhi0395** [comment]
Thank you for reminding @schlafly, and I am so sorry for the delay in reprocessing. I have reprocessed these tiles now and have updated the nightqa.

https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20230618/

Please close the issue if you feel it's resolved.

**Comment by araichoor** [comment]
@abhi0395 : looks like none of those have their `tile-qa*fits` file:
```
raichoor@perlmutter:login18:~> TILEIDS="5039 6111 7509 7510 7511 7519 9227 9597 10621"
raichoor@perlmutter:login18:~> date; for TILEID in $TILEIDS; do ls /global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/$TILEID/20230618/tile-qa-$TILEID-thru20230618.fits; done
Mon 14 Aug 2023 08:23:24 PM PDT
ls: cannot access '/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/5039/20230618/tile-qa-5039-thru20230618.fits': No such file or directory
ls: cannot access '/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/6111/20230618/tile-qa-6111-thru20230618.fits': No such file or directory
ls: cannot access '/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/7509/20230618/tile-qa-7509-thru20230618.fits': No such file or directory
ls: cannot access '/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/7510/20230618/tile-qa-7510-thru20230618.fits': No such file or directory
ls: cannot access '/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/7511/20230618/tile-qa-7511-thru20230618.fits': No such file or directory
ls: cannot access '/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/7519/20230618/tile-qa-7519-thru20230618.fits': No such file or directory
ls: cannot access '/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/9227/20230618/tile-qa-9227-thru20230618.fits': No such file or directory
ls: cannot access '/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/9597/20230618/tile-qa-9597-thru20230618.fits': No such file or directory
ls: cannot access '/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/10621/20230618/tile-qa-10621-thru20230618.fits': No such file or directory
```

quickly looking at the 5039 log files, it looks like the `spectra` for petal=4 fail, leading to further errors downstream.
```
raichoor@perlmutter:login18:~> cat /global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/5039/20230618/logs/spectra-4-5039-thru20230618.log 
================ Start of Process 0 ================
ERROR:util.py:88:runcmd: missing input /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20230618/00185824/cframe-b4-00185824.fits.gz
ERROR:util.py:88:runcmd: missing input /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20230618/00185824/cframe-z4-00185824.fits.gz
CRITICAL:util.py:99:runcmd: FAILED missing required inputs: desispec.scripts.group_spectra.main(['--inframes', '/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20230618/00185824/cframe-b4-00185824.fits.gz', '/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20230618/00185824/cframe-z4-00185824.fits.gz', '--outfile', '/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/5039/20230618/spectra-4-5039-thru20230618.fits.gz', '--coaddfile', '/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/5039/20230618/coadd-4-5039-thru20230618.fits', '--onetile', '--header', 'SPGRP=cumulative', 'SPGRPVAL=20230618', 'NIGHT=20230618', 'TILEID=5039', 'SPECTRO=4', 'PETAL=4'])
================= End of Process 0 =================
```


note that you d then also have to re-generate the nightqa, as several diagnoses there use those `tile-qa*fits` file.

thanks!

**Comment by abhi0395** [comment]
Hi @araichoor, thank you so much for pointing out these issues. I am sorry that I missed this important part. It seems I need to flag petal=4 in all cameras together and reprocess them again. If I remember correctly, the pipeline processes all cameras on a given petal together, so it fails if anyone is missing. I will discuss them with Anthony tomorrow and reprocess them.

**Comment by abhi0395** [comment]
Hi @araichoor, it's reprocessed now. The updated nightqa is available at:

https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20230618/

**Comment by schlafly** [comment]
Thanks Abhijeet!  I repeated QA on these tiles and am closing.
