### ISSUE TITLE
desi_tile_vi changes tiles-specstatus.ecsv QA column datatype based on current entries

### ISSUE THREAD

**Issue by LNapolitano** [desihub/desisurveyops#125]
When desi_tile_vi is run, the datatype of the QA column of tiles-specstatus.ecsv will be set to be a string with length equal to the current longest string in the QA column. In practice this means that if no entries have QA = "unsure" then the datatype will be set to a four-string. When the code is next run, if a user attempts to set the QA value = "unsure" the following warning will occur:

/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/bin/desi_tile_vi:285: StringTruncateWarning: truncated right side string(s) longer than 4 character(s) during assignment tiles_table["QA"][index]="unsure"

And the QA value will be saved as "unsu" rather than "unsure"

**Comment by schlafly** [comment]
This one was merged so I'm closing.
