### ISSUE TITLE
Incorrect MTL-reprocessing of four tiles

### ISSUE THREAD

**Issue by geordie666** [desihub/desisurveyops#126]
During the September-November 2021 CTE issues we MTL-reprocessed multiple tiles for which we decided the redshifts needed to be corrected. This was almost entirely successful, but a corner case is situations where we lost an entire petal (in the zmtl files) _after_ reprocessing by the spectroscopic pipeline.

This corner case led to problems on four tiles corresponding to, e.g., these files:
```
'/global/cfs/cdirs/desi/spectro/redux/daily/tiles/archive/6369/20211122/zmtl-4-6369-thru20210930.fits'
'/global/cfs/cdirs/desi/spectro/redux/daily/tiles/archive/7402/20211123/zmtl-4-7402-thru20211002.fits'
'/global/cfs/cdirs/desi/spectro/redux/daily/tiles/archive/23960/20211122/zmtl-4-23960-thru20210921.fits'
'/global/cfs/cdirs/desi/spectro/redux/daily/tiles/archive/26173/20211122/zmtl-4-26173-thru20210921.fits'
```
The problem, here, is that these petals don't exist at all in the re-archiving (the files are missing) but they did exist in the original archiving:
```
/global/cfs/cdirs/desi/spectro/redux/daily/tiles/archive/6369/20211001/zmtl-4-6369-thru20210930.fits
/global/cfs/cdirs/desi/spectro/redux/daily/tiles/archive/7402/20211004/zmtl-4-7402-thru20211002.fits
/global/cfs/cdirs/desi/spectro/redux/daily/tiles/archive/23960/20210924/zmtl-4-23960-thru20210921.fits
/global/cfs/cdirs/desi/spectro/redux/daily/tiles/archive/26173/20210927/zmtl-4-26173-thru20210921.fits
```
In fact, we identified these four cases purely _because_ the files exist in the original archiving but are missing in the re-archiving.

As an example of why this is likely wrong, here's what happens to a target on tile `6369` after re-archiving and MTL-reprocessing:
```
more /global/cfs/cdirs/desi/survey/ops/surveyops/trunk/mtl/main/dark/mtl-dark-hp-4441.ecsv | grep 39627791414594408 | awk '{print $18, $19, $20, $21, $22, $23, $24}'
-1.0 -1 -1 -1.0 -1 -1.0 QSO|UNOBS
0.2725044744258378 0 6369 2.001432429104902 1 82.13470605574548 QSO|MORE_MIDZQSO
```
So, here we have an unobserved QSO with a state that is updated by a good observation on tile `6369`. But, the QSO stays in that "original" state because no new information is included for the target when petal 4 of tile `6369` is re-archived.

This contrasts, for example, with a target for which we took the "correct" approach of setting the entirety of petal 4 to `BAD_PETALQA` in the re-archiving. For example:
```
more /global/cfs/cdirs/desi/survey/ops/surveyops/trunk/mtl/main/dark/mtl-dark-hp-4413.ecsv | grep 39627742844556827 | awk '{print $18, $19, $20, $21, $22, $23, $24}'
-1.0 -1 -1 -1.0 -1 -1.0 QSO|UNOBS
1.6715542476640988 0 4317 1.6751628955377766 1 741.1169929411262 QSO|MORE_MIDZQSO
1.671985369011397 524288 4317 1.6773043418019986 1 813.2519231270999 QSO|UNOBS
1.6744277501658869 0 2764 1.6929402563567568 1 461.61966776067857 QSO|MORE_MIDZQSO
```
Here the unobserved QSO target (`QSO|UNOBS`) turns into a `QSO|MORE_MIDZQSO` on tile `4317`, then turns back into an unobserved QSO target on tile `4317` because of an observation with `ZWARN` of `524288` (which corresponds to `BAD_PETALQA`). The QSO target is then subsequently successfully observed on tile `2764`. 

The progression tracks correctly for target `39627742844556827` because `BAD_PETALQA` was set for every fiber on petal 4 when tile `4317` was re-archived (e.g., see the file `'/global/cfs/cdirs/desi/spectro/redux/daily/tiles/archive/4317/20211122/zmtl-4-4317-thru20211007.fits'`).

**Comment by schlafly** [comment]
The good news here is that I think we decided that those Sep 2021 events could be fixed in software and didn't affect QSO identification.  So we might not have wanted to reprocess those tiles in the way we did at all.

But I think we still have those CCDs that were affected by CTE marked bad in iron.  I think we want to turn that off in the next round of reductions.

**Comment by sbailey** [comment]
I have re-re-archived these tiles with the commands below.  Let's close this ticket after @geordie666 completely closes the loop with an MTL update of these tiles.  Tiles 6369,7402,23960,26173 now have a latest ARCHIVEDATE of 20230821.
```
source $HOME/bin/desi_daily_env.sh

cd $DESI_ROOT/survey/ops/surveyops/trunk/ops/
svn update .

desi_archive_tilenight -t 6369  -n 20210930 --rearchive --badpetals 4
desi_archive_tilenight -t 7402  -n 20211002 --rearchive --badpetals 4
desi_archive_tilenight -t 23960 -n 20210921 --rearchive --badpetals 4
desi_archive_tilenight -t 26173 -n 20210921 --rearchive --badpetals 4

# there was a bug that left this in a writeable state; fix with
chmod u-w $DESI_ROOT/spectro/redux/daily/tiles/archive/6369/20230821/zmtl-4-6369-thru20210930.fits
# for other tiles, I fixed code before running desi_archive_tilenight

svn commit -m "re-re-archiving tiles 6369,7402,23960,26173 for missing petal 4" $DESI_ROOT/survey/ops/surveyops/trunk/ops/tiles-specstatus.ecsv
```
