### ISSUE TITLE
Mark tiles observed on 20230806 as bad if they were <35 deg from the Moon

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#128]
The [unusual behavior of z6 in sframesky during 20230806](https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20230806/sframesky-20230806.pdf) might be correlated with high sky background conditions. (See more in [this thread](https://desisurvey.slack.com/archives/C01HNN87Y7J/p1691524377813169) on slack.) At @schlafly's suggestion, we can be conservative and mark all exposures <35 deg from the Moon on 20230806 as bad, unless the data team considers the exposures to be good.

**Comment by schlafly** [comment]
The following exposures need to be marked bad and reprocessed:
 ```
 NIGHT   EXPID  TILEID       DMOON       
 int64   int64  int64       float64      
-------- ------ ------ ------------------
20230806 189022  22371  19.47282675129187
20230806 189023  22357 18.644996332802968
20230806 189024  22358 15.397947262709197
20230806 189025  25507 12.394243980697885
20230806 189026  22131 13.283330079142571
20230806 189027  22131  13.15279402906439
```

12 degree min separation (!).  On the other hand, the actual sky brightnesses here aren't so bad.
![image](https://github.com/desihub/desisurveyops/assets/1417841/e2a14855-4c2a-4ed8-a347-c0e0caf14001)
Things look similar in g.  I don't understand this, but we still probably shouldn't keep this data.  @akremin , others?

**Comment by araichoor** [comment]
if useful -- for this specific case, or for a more general discussion about how close to the Moon we can go -- please find attached a couple of plots based on `exposures-daily.csv` and `offline_matched_coadd_ccds_SV3-thru_20230809.fits`.

<img width="1117" alt="Screenshot 2023-08-14 at 2 43 56 PM" src="https://github.com/desihub/desisurveyops/assets/61986357/fce7ee22-45dc-4671-a44b-e07ac20ef3e8">

**Comment by akremin** [comment]
I have marked the exposures to be ignored by the pipeline, removed the processed files on disk for the affected tiles, and rerun the tsnr and nightqa for the night.

The impacted tiles were not observed at any other times, so no need to rerun anything.

Back to you Eddie @schlafly.
