### ISSUE TITLE
Spurious z>1.0 redshifts in bright tiles in Petal 1 (and Petal 3)

### ISSUE THREAD

**Issue by rongpu** [desihub/desisurveyops#131]
In 20230811, 20230812 and earlier nights, many of the bright tiles have spurious redshifts at z>1.0 in Petal 1, and sometimes in Petal 3 as well. The spurious redshifts in Petal 1 are probably due to the b1 amplifier issue.

Five tiles from 20230811 and 20230812 are marked unsure because of this issue: 20164, 20538, 22609, ~~23980~~, 24165. Their QA pages are listed below.

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/20164/20230812/tile-qa-20164-thru20230812.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/20538/20230812/tile-qa-20538-thru20230812.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/22609/20230811/tile-qa-22609-thru20230811.png
~~https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/23980/20230811/tile-qa-23980-thru20230811.png~~
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/24165/20230811/tile-qa-24165-thru20230811.png

Edited by EFS to remove 23980 because this is also bad due to observation on 20230809 / unstable amplifiers.

**Comment by rongpu** [comment]
Bright tiles [20540](https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/20540/20230814/tile-qa-20540-thru20230814.png) and [24837](https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/24837/20230814/tile-qa-24837-thru20230814.png) from 20230814 are marked as unsure due to the same issue.

**Comment by rongpu** [comment]
Bright tiles 21614, 22315 and 25922 from 20230815 are also marked as unsure.

**Comment by schlafly** [comment]
@julienguy , I note that z1 and z3 have the largest CTE effects we know about.  Looking at
https://data.desi.lbl.gov/desi/users/schlafly/misc/cte-check-00185425-z.pdf
they also feel to me like cases where there's a slope across the CTE affected region (which we're now correcting).  In the last round of fixes we were unhappy that the sky lines were not getting good corrections on these petals; from the sframe residuals, that looks to be the biggest issue.

We could pursue the next level of hack, adding in an additional sky line template into the sector fitting or downstream, along the lines of your 'sky line template ~tpcorr' PR from once upon a time, but only to a sector.  That's a bit painful but would probably be helpful.  We could pursue more principled CTE corrections.

My impression from @rongpu is that this is the bigger issue than b1 to poor P1 redshifts; I'm sorry to have blamed this on b1.

**Comment by schlafly** [comment]
Also tileid 24763, expid 189274, night 20230808, from https://github.com/desihub/desisurveyops/issues/129; merging those issues.

**Comment by schlafly** [comment]
Rongpu also tagged 20533, 21008, 24164 with this issue.

**Comment by schlafly** [comment]
I'm going to go ahead and mark the tiles in this issue as good, following discussion on the survey-ops call that these are due to CTE.  I am clearing QA for the following tiles, and then repeating the QA to mark them as good.
20164
20533
20538
20540
21008
21614
22315
22609
24164
24165
24763
24837
25922

**Comment by schlafly** [comment]
We expect this to be addressed by the new CTE code, closing.
