### ISSUE TITLE
Apparent mismatch between tiles-main.ecsv and tiles-daily.csv?

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#132]
I notice in my status page, in the "Pending tiles" section, that TILEID=4534 is labelled `obsend` in `tiles-main.ecsv`, but has `EFFTIME_SPEC=0` in `tiles-daily.csv`.
This tile has `QA=none` in `tiles-specstatus.ecsv`.

Digging a bit, I also find nine other tiles which are `obsend` and `IN_DESI=True` in `tiles-main.ecsv`, but do not appear in `tiles-daily.csv` (and those also do not appear in `tiles-specstatus.ecsv`).

Unless I m missing something, those shouldn t happen, right?
I suspect those may be due to some reprocessing, which have somewhat not been synchronized.. I ve not digged yet into the desisurveyops issues to convince myself of that.

Code snippet:
```
# read tiles-daily.csv
d = Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/tiles-daily.csv")

# read tiles-main.ecsv, cut on "obsend" tiles
t = Table.read("/global/cfs/cdirs/desi/survey/ops/surveyops/trunk/ops/tiles-main.ecsv")
sel = t["STATUS"] == "obsend"
t = t[sel]

# tiles not appearing in daily
sel = ~np.in1d(t["TILEID"], d["TILEID"])
t[sel]
=> 
TILEID  PASS    RA      DEC    PROGRAM IN_DESI  PRIORITY  STATUS EBV_MED DESIGNHA DONEFRAC AVAILABLE PRIORITY_BOOSTFAC
int64  int32 float64  float64    str6    bool   float64    str8  float32 float32  float32     bool        float64     
------ ----- -------- -------- ------- ------- ---------- ------ ------- -------- -------- --------- -----------------
  3472     1  265.962   24.764    DARK    True  1.227e+00 obsend   0.074    30.17   1.0028      True             1.000
  7741     4  166.106    8.240    DARK    True  1.371e+00 obsend   0.031    -9.05   1.0054      True             1.000
 22308     1  256.050   57.853  BRIGHT    True  1.007e+00 obsend   0.021    12.92   1.0385      True             1.000
 23891     2  255.389   45.630  BRIGHT    True  1.093e+00 obsend   0.022    12.33   1.0510      True             1.000
 24723     3  271.809   65.368  BRIGHT    True  9.690e-01 obsend   0.042    16.28   1.0250      True             1.000
 25880     3  200.937   30.797  BRIGHT    True  1.166e+00 obsend   0.013    -3.32   1.0069      True             1.000
 40896     0   65.392    1.536  BACKUP    True  1.373e+00 obsend   0.142     0.00   1.0275      True             1.000
 40935     0   61.618    0.103  BACKUP    True  1.411e+00 obsend   0.242     0.00   0.8832      True             1.000
 42809     0   55.643   -2.044  BACKUP    True  1.394e+00 obsend   0.104     0.00   1.0113      True             1.000


# tiles in daily, but with efftime=0
sel = np.in1d(t["TILEID"], d["TILEID"][d["EFFTIME_SPEC"] == 0])
t[sel]
=>
TILEID  PASS    RA      DEC    PROGRAM IN_DESI  PRIORITY  STATUS EBV_MED DESIGNHA DONEFRAC AVAILABLE PRIORITY_BOOSTFAC
int64  int32 float64  float64    str6    bool   float64    str8  float32 float32  float32     bool        float64     
------ ----- -------- -------- ------- ------- ---------- ------ ------- -------- -------- --------- -----------------
  4534     2  256.295   15.641    DARK    True  1.306e+00 obsend   0.112    26.46   1.0061      True             1.000

**Comment by schlafly** [comment]
Thanks Anand.  4534 is missing entries in the exposures-daily.ecsv file for expid 182168 and 182169.
```
20230525 4534 182168 SCIENCE DARK 1170.443 418.688 -1.0 418.688 -1.0 good ""
20230525 4534 182169 SCIENCE DARK 1501.314 587.363 -1.0 587.363 -1.0 good ""
```
In past cases I think these get marked bad in the offline pipeline but the tsnr afterburner doesn't run on them and they get lost.  AP assumes that the EFFTIME_ETC are correct if exposures-daily.ecsv doesn't say anything about the tiles.

None of the tiles in your list have entries in exposures-daily.ecsv.  The missing entries that need to be added are:
4534: 20230525, expid 182168, 182169.
3472: 20230525, expid 182170.
23891: 20230525, expid 182165.
24723: 20230525, expid 182172.
7741: 20230614, expid 176606.
22308: 20230608, expid 184545.
25880: 20220221, expid 123283.
40896: 20220911, expid 141872.
40935: 20220911, expid 141871.
42809: 20220911, expid 141868.

```
20230525 3472 182170 SCIENCE DARK 1522.507 1002.821 -1.0 1002.821 -1.0 good ""
20230416 7741 176606 SCIENCE DARK 1685.884 1005.371 -1.0 1005.371 -1.0 good ""
20230608 22308 184545 SCIENCE BRIGHT 435.053 186.933 -1.0 186.933 -1.0 good ""
20230525 23891 182165 SCIENCE BRIGHT 487.629 189.186 -1.0 189.186 -1.0 good ""
20230525 24723 182172 SCIENCE BRIGHT 501.315 184.501 -1.0 184.501 -1.0 good ""
20220221 25880 123283 SCIENCE BRIGHT 792.406 181.242 -1.0 181.242 -1.0 good ""
20220911 40896 141872 SCIENCE BACKUP 445.46 61.653 -1.0 61.653 -1.0 good ""
20220911 40935 141871 SCIENCE BACKUP 606.913 52.994 -1.0 52.994 -1.0 good ""
20220911 42809 141868 SCIENCE BACKUP 608.612 60.675 -1.0 60.675 -1.0 good ""
```

We probably need a better system for making sure that exposures that have an EFFTIME_ETC all make it to exposures-daily with an EFFTIME_SPEC eventually.  @akremin , I'm not sure who is best set up for pushing these into exposures-daily, but it looks to me like that's what needs to happen?  Thanks!

**Comment by araichoor** [comment]
thanks @schlafly for the quick investigation!

about how to better monitor such things:
- could that be done at the spectro. pipeline stage (e.g. when running the afterburner to generate the {exposures,tiles}-daily.csv files)
- or would it required to add an extra-step in the dailyops (when running `desi_tile_vi` or `afternoon_plan.sh`), like performing some consistency checks between:
  - {exposures,tiles}-daily.csv
  - tiles-specstatus.ecsv
  - tiles-main.ecsv
and report any such inconsistencies? (like a big message on the prompt, that would catch the eye).

**Comment by schlafly** [comment]
We could do something at AP time but I'm a bit reluctant to introduce more handshakes there.  We expect some level of inconsistency at AP time whenever we don't have updates from NERSC (e.g., now---we have stuff in AP from two nights ago but not in exposures-daily), so it would be a warning that is often ignored.

I'd be happier if it were at the spectroscopic pipeline stage, but I don't know what would be involved there.

**Comment by araichoor** [comment]
I forgot about this `exposures.ecsv` file in `$DESI_SURVEYOPS/ops/`.
then would even a simple like this make sense (with maybe few additional more quality cuts; e.g. restrict to nights up to when the daily has been run).
if I m correct, that catches the exposures you list above, and more.

we (I) could run this by hand like once a week, and report if there s something missing.

```
t = Table.read("/global/cfs/cdirs/desi/survey/ops/surveyops/trunk/ops/tiles-main.ecsv")
tileids = t["TILEID"][t["IN_DESI"]]

a = Table.read("/global/cfs/cdirs/desi/survey/ops/surveyops/trunk/ops/exposures.ecsv")
sel = (np.in1d(a["TILEID"], tileids)) & (a["QUALITY"] == "good")
a = a[sel]

b = Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures-daily.csv")
sel = ~np.in1d(a["EXPID"], b["EXPID"])
a[sel].pprint_all()

=>

 NIGHT   TILEID EXPID  OBSTYPE PROGRAM  EXPTIME  EFFTIME_ETC EFFTIME_SPEC EFFTIME  GOALTIME QUALITY COMMENTS
-------- ------ ------ ------- ------- --------- ----------- ------------ -------- -------- ------- --------
20211220  23046 114876 SCIENCE  BRIGHT  1455.613     105.105       -1.000  105.105     -1.0    good       --
20220110  24410 117827 SCIENCE  BRIGHT   916.408      17.409       -1.000   17.409     -1.0    good       --
20220110  24410 117828 SCIENCE  BRIGHT  1228.330       7.778       -1.000    7.778     -1.0    good       --
20220110  24410 117829 SCIENCE  BRIGHT   826.652       0.469       -1.000    0.469     -1.0    good       --
20220216  24459 122527 SCIENCE  BRIGHT  1560.731      55.470       -1.000   55.470     -1.0    good       --
20220216  24459 122528 SCIENCE  BRIGHT  1330.230      66.059       -1.000   66.059     -1.0    good       --
20220216  24459 122529 SCIENCE  BRIGHT   909.493      28.064       -1.000   28.064     -1.0    good       --
20220216  24459 122530 SCIENCE  BRIGHT    42.099       1.116       -1.000    1.116     -1.0    good       --
20220216  42669 122531 SCIENCE  BACKUP   602.955      25.048       -1.000   25.048     -1.0    good       --
20220216  42660 122532 SCIENCE  BACKUP   601.416      22.097       -1.000   22.097     -1.0    good       --
20220216  42666 122533 SCIENCE  BACKUP   602.993      16.234       -1.000   16.234     -1.0    good       --
20220216  42665 122534 SCIENCE  BACKUP   601.498      15.680       -1.000   15.680     -1.0    good       --
20220216  41654 122535 SCIENCE  BACKUP   116.539       0.014       -1.000    0.014     -1.0    good       --
20220221  25880 123283 SCIENCE  BRIGHT   792.406     181.242       -1.000  181.242     -1.0    good       --
20220415  42416 130372 SCIENCE  BACKUP   147.499       0.065       -1.000    0.065     -1.0    good       --
20220911  41334 141794 SCIENCE  BACKUP   600.729       4.951       -1.000    4.951     -1.0    good       --
20220911  40835 141795 SCIENCE  BACKUP   137.773       0.000       -1.000    0.000     -1.0    good       --
20220911  40065 141865 SCIENCE  BACKUP   601.838      17.400       -1.000   17.400     -1.0    good       --
20220911  41419 141866 SCIENCE  BACKUP   602.791      27.518       -1.000   27.518     -1.0    good       --
20220911  41421 141867 SCIENCE  BACKUP   602.802      34.934       -1.000   34.934     -1.0    good       --
20220911  42809 141868 SCIENCE  BACKUP   608.612      60.675       -1.000   60.675     -1.0    good       --
20220911  41461 141869 SCIENCE  BACKUP   607.988      29.690       -1.000   29.690     -1.0    good       --
20220911  40895 141870 SCIENCE  BACKUP   607.867      30.101       -1.000   30.101     -1.0    good       --
20220911  40935 141871 SCIENCE  BACKUP   606.913      52.994       -1.000   52.994     -1.0    good       --
20220911  40896 141872 SCIENCE  BACKUP   445.460      61.653       -1.000   61.653     -1.0    good       --
20220911  42873 141873 SCIENCE  BACKUP   156.037      14.020       -1.000   14.020     -1.0    good       --
20230416   7741 176606 SCIENCE    DARK  1685.884    1005.371       -1.000 1005.371     -1.0    good       --
20230503  41894 178901 SCIENCE  BACKUP   601.914       1.044       -1.000    1.044     -1.0    good       --
20230525  23891 182165 SCIENCE  BRIGHT   487.629     189.186       -1.000  189.186     -1.0    good       --
20230525   4534 182168 SCIENCE    DARK  1170.443     418.688       -1.000  418.688     -1.0    good       --
20230525   4534 182169 SCIENCE    DARK  1501.314     587.363       -1.000  587.363     -1.0    good       --
20230525   3472 182170 SCIENCE    DARK  1522.507    1002.821       -1.000 1002.821     -1.0    good       --
20230525  24723 182172 SCIENCE  BRIGHT   501.315     184.501       -1.000  184.501     -1.0    good       --
20230608  22308 184545 SCIENCE  BRIGHT   435.053     186.933       -1.000  186.933     -1.0    good       --
```

**Comment by schlafly** [comment]
Thanks for looking at this.  Yes, that's what I was doing.  The "quality" field is meaningless and you should ignore it.  Normally you'd see some recent entries there even when things are working due to NERSC being a bit behind AP.

**Comment by akremin** [comment]
This can only happen when the pipeline isn't run (or isn't rerun) when new data is processed. So to me adding it to the afterburner for a given night wouldn't help because if we knew about it we would have already dealt with it. We can add it as a check over all nights each time we run the afterburner, but that seems like overkill versus a standalone daily/weekly/monthly check.

To me this seems most obviously implemented on the survey ops side whenever specstatus is updated, given the pipeline never deals with the specsstatus file except for a recent addition where we restrict to completed tiles in reprocessing. That said it is trivial to add this in either framework and the check operates at the interface of the two, so I am happy to discuss adding it as a data-ops check.

**Comment by schlafly** [comment]
From my perspective, this isn't a specstatus question.  This is about the exposures-daily.ecsv file, and when we set things as bad that needs to get reflected there.  AP / survey-ops is a consumer of that information and (eventually...) notices when it's not populated, but there doesn't need to be AP <-> offline pipeline feedback for those inconsistencies to be noticed.

**Comment by akremin** [comment]
Fair point. We have the knowledge to do this in data-ops alone and we should do a better job of robustness on our side without feedback. I'll open an associated ticket in desispec and assign myself for this.

**Comment by araichoor** [comment]
yes, sure, thanks @akremin!
