### ISSUE TITLE
missing r causes no standards to be selected thus blocking b and z

### ISSUE THREAD

**Issue by abhi0395** [desihub/desisurveyops#134]
While re-reprocessing some tiles (desisurveyops issues: [34](https://github.com/desihub/desisurveyops/issues/34), [88](https://github.com/desihub/desisurveyops/issues/88)), I encountered some problems with spectro pipeline. Here is a summary of the problem:

If a tile was observed with multiple exposures on a given night and any of the _r-camera_ needs to be marked bad on any of those exposures (not all), then the pipeline also fails to select standard stars for b and z cameras. I discussed this issue with @sbailey and @julienguy, and we found that this is happening because the pipeline selects standard stars based on r-camera, so if any petal is missing r-camera, then it won't select any standard stars and b and z calibration will also fail.

Here are a few example tiles where this problem occurs:

1) Issue: [34](https://github.com/desihub/desisurveyops/issues/34), Night: 20220324, Tile: 82636 (EXPID: 127343-127350):

r1 is marked bad for three exposures (127343-127345) due to "ion pump contamination". All other exposures (127346-127350) are fine. However, the pipeline is failing select standards due to missing r-camera for all those exposures.

Here are a few important lines from the [tilenight log file](https://data.desi.lbl.gov/desi/spectro/redux/daily/run/scripts/night/20220324/tilenight-20220324-82636-14298412.log):

```
INFO:proc_joint_fit.py:416:main: Starting stdstar fitting at Wed Aug 23 10:04:53 2023
INFO:proc_joint_fit.py:448:main: Will use input FIBERFLAT: /dvs_ro/cfs/cdirs/desi/spectro/redux/daily/calibnight/20220324/fiberflatnight-z9-20220324.fits
ERROR:proc_joint_fit.py:475:main: Missing expected frame /dvs_ro/cfs/cdirs/desi/spectro/redux/daily/exposures/20220324/00127343/frame-r1-00127343.fits.gz
ERROR:proc_joint_fit.py:479:main: Missing expected sky /dvs_ro/cfs/cdirs/desi/spectro/redux/daily/exposures/20220324/00127343/sky-r1-00127343.fits.gz
ERROR:proc_joint_fit.py:475:main: Missing expected frame /dvs_ro/cfs/cdirs/desi/spectro/redux/daily/exposures/20220324/00127344/frame-r1-00127344.fits.gz
ERROR:proc_joint_fit.py:479:main: Missing expected sky /dvs_ro/cfs/cdirs/desi/spectro/redux/daily/exposures/20220324/00127344/sky-r1-00127344.fits.gz
ERROR:proc_joint_fit.py:475:main: Missing expected frame /dvs_ro/cfs/cdirs/desi/spectro/redux/daily/exposures/20220324/00127345/frame-r1-00127345.fits.gz
ERROR:proc_joint_fit.py:479:main: Missing expected sky /dvs_ro/cfs/cdirs/desi/spectro/redux/daily/exposures/20220324/00127345/sky-r1-00127345.fits.gz
```

2) Issue: [88](https://github.com/desihub/desisurveyops/issues/88), Night: 20221209, Tile: 83200 (EXPID: 157130-157134):

r3, r4, r5, r6, r9 are marked bad for one of the exposures (157134) "due to unstable amplifier". All other exposures (157130-157133) are fine. However, the pipeline is failing select standards due to missing r-camera for all those exposures.

As far as we are aware, we have encountered issues where either b or z cameras go bad, but the pipeline proceeds smoothly as standard star calibration is based on r-camera. I am not sure how many tiles/exposures might have had this issue in the past.

**Comment by araichoor** [comment]
sorry, I m lagging a bit behind in those tickets.
just reading this one now: is there any chance this will be fix like, this week? (if not, no worries, but I d just like to know).
I m asking because I m compiling data for the odin/lae observations; and this tileid=82636 is one of those.

**Comment by abhi0395** [comment]
Hi @araichoor, I am not sure how and when we are going to fix this problem. Perhaps, Stephen or Julien can comment more on this!

**Comment by schlafly** [comment]
It seems to me that this issue is better tracked in desispec; @abhi0395 , would you mind closing this one and opening a related ticket there?

From a survey-ops perspective, whether only one camera goes or all three go is a bit of a wash, since we end up throwing the petal out of the MTLs, etc..  But obviously it would be better to save the data in general.

**Comment by abhi0395** [comment]
Thanks @schlafly I have opened a new ticket on desispec

https://github.com/desihub/desispec/issues/2128
