### ISSUE TITLE
Tile 25578 on 2023-08-24 alert on 9-BSKYTHRURMS

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#135]
Tile 25578 on 2023-08-24  has "Alert: 9_BSKYTHRURMS=0.113".

**Comment by schlafly** [comment]
Our rule here is to scrutinize these more carefully than average, but mark them as good if nothing pops up.  I think you can go ahead and mark this as good.

However, it looks to me the center of the sky line on b9 got masked for all fibers, and this is what has led to the problem.  I've never seen that before.  Maybe @araichoor , any interest in looking at the sky line on b9 and seeing if you can see what happened there?

**Comment by schlafly** [comment]
@julienguy , I took a look at frame-b9-00192356.fits.gz, and the MASK extension has a lot of masking right at the 557 nm oxygen line.  I did not see that masking in the preproc image.  I wasn't really aware that there was masking in between preproc and mask.  It's getting BAD2DFIT, which I guess makes sense given where it's coming in, but ... that's weird?

**Comment by sbailey** [comment]
FYI BAD2DFIT comes from the spectral extractions, reporting that the 2D PSF model is a bad fit to the actual data, which typically arises from unflagged cosmics or unmasked CCD defects.  I'm not immediately sure why that would appear as a new problem on a sky line.

**Comment by araichoor** [comment]
sorry, I don t have time right now to dive into this.

but I could quickly generate small pdf for the sky fibers for 20230824 for:
- tileid=25578, petal=9: https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/tmp-25578-thru20230824-sky-pet9.pdf
- tileid=25578, petal=8 (ie same tile, different petal): https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/tmp-25578-thru20230824-sky-pet8.pdf
- tileid=20873, petal=9 (ie next observed tiled, same petal): https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/tmp-20873-thru20230824-sky-pet9.pdf.

maybe that can help answer your question, @schlafly? (sorry, I cannot carefully inspect those right now).

besides, that s probably unrelated to this issue, but seeing those spectra:
I notice that lots of stuck fibers (negative targetids) have apparently very dubious sky spectra.
with quickly checking the two tiles, it could be some fibers are "regularly bad".
@julienguy: could you remind me what/where is the criterion for the spectro. pipeline to consider a fiber valid for entering the sky computation?

**Comment by LNapolitano** [comment]
Adding tile 9339 (EXPID=00197796) from 2023-09-23 as an additional instance of this effect. From the sframe the masking seems to affect b0 and b5 although an alert was only raised for b5.

**Comment by sybenzvi** [comment]
Adding tile 6932, expid 191143-191144 from 2023-10-02 as another instance.
![Screen Shot 2023-10-05 at 9 34 12 AM](https://github.com/desihub/desisurveyops/assets/7385438/926b629f-2698-4f66-920f-ad04be4cab4b)

**Comment by sybenzvi** [comment]
Adding tile 5374, expid 199443 from 2023-10-04 to the list.
![Screen Shot 2023-10-05 at 7 34 20 PM](https://github.com/desihub/desisurveyops/assets/7385438/b958df15-bb48-4eb0-8269-b540ccd7d22e)

**Comment by schlafly** [comment]
I've marked the original 25578 as good as it's just this sky line issue.
