### ISSUE TITLE
Tile 22287 on night 2023-08-29 fails flux calibration on 4 petals

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#136]
Tile 22287 on 2023-08-29 is a BRIGHT tile observed with two exposures.  Survey speeds were approx 15% for the first exposure 00193272 and 7% for the subsequent exposure 00193273.  Aside from clouds, the only comment in the night logs was "Amps B1A and B1C have low read noise errors for all exposures".  The moon was nearly full but 99 deg away.  The standard star fluxing has wild variations both within petals and between petals, resulting in data from 2 petals being rejected and other petals having presumably very poor flux calibration.

![tile-qa-22287-thru20230829](https://github.com/desihub/desisurveyops/assets/7918018/7241430d-9e5d-4ce4-ae71-2fb65c11f632)

**Comment by schlafly** [comment]
To me the fact that petals 9-3 all have low THRUFRAC suggests passing clouds?  I'd be interested in seeing Anand's spacewatch movie for this night.  The other thing that affects THRUFRAC (though usually not in a spatially correlated manner like this) is focus errors.  Julien has a good code snippet for diagnosing that.
```
im = '00126561'
night = '20220317'
from astropy.table import Table
for spec in range(10) :
    t=Table.read(f"/global/cfs/cdirs/desi/spectro/redux/daily/exposures/{night}/{im}/cframe-r{spec}-{im}.fits.gz","FIBERMAP")
    s=Table.read(f"/global/cfs/cdirs/desi/spectro/redux/daily/exposures/{night}/{im}/cframe-r{spec}-{im}.fits.gz","SCORES")
    i=t["FIBERFLUX_R"]>10
    x=t["FIBER_X"][i]
    y=t["FIBER_Y"][i]
    ratio=s["MEDIAN_CALIB_COUNT_R"][i]/t["FIBERFLUX_R"][i]
    ratio /= np.median(ratio)
    plt.scatter(x,y,c=ratio,vmin=0.8,vmax=1.2)
plt.colorbar()
```
The first of the two images looks fine.  The second image has the pretty large flux variations:
<img width="783" alt="image" src="https://github.com/desihub/desisurveyops/assets/1417841/ebc99073-4bf3-42fd-90df-908673ebd555">
To me the suggestion is that the fiber positioning on the second exposure was not good; maybe we rejected the move or made the wrong move?  I'm imagining that pattern looks a little like ADC motions, but I'm just imagining that.

I think we'd want to mark the 2nd exposure as bad.  First exposure has enough EFFTIME anyway.

**Comment by araichoor** [comment]
spacewatch movie for 20230829 here: https://data.desi.lbl.gov/desi/users/raichoor/main-status/spacewatch/spacewatch-20230829.mp4
those two exposures are around 13s-15s => nothing particular here in the movie... except an overall sharp dimming of the spacewatch images during 00193273; but that s probably only some display feature?

**Comment by schlafly** [comment]
@akremin , @abhi0395 , can you mark 193273 on 20230829 tileid 22287 as bad and reprocess 22287?  Thanks!

**Comment by abhi0395** [comment]
22287 is re-processed, tsnr+nightqa redone. 
updated nightqa:

https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20230829

**Comment by schlafly** [comment]
It looks like I was wrong and 193272 isn't really acceptable either, though it's better than 193273.  Let's mark 20230829/193272, tileid 22287 bad as well.  Sorry!  That will be all the exposures on this tile.

**Comment by abhi0395** [comment]
@schlafly, thanks! reprocessed, tsnr+nightqa re-done!

https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20230829/

**Comment by SGontcho** [comment]
Thanks @abhi0395 @schlafly, this has been cleared in the QA. Now closing.
