### ISSUE TITLE
Reprocess r3 and z3 for EXPID= 194739-194743 from 20230905

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#137]
@akremin, @abhi0395 : could mark `r3` and `z3` as bad on the following 20230905 exposures, and reprocess the related tiles?
```
# TILEID EXPIDS
21751    194739
21745    194740
9113     194741,194742
26167    194743
```

towards the end of the night, there s been an instrumental issue with petal=3 during expid=194737:

from Klaus in [#observing](https://desisurvey.slack.com/archives/CT1TAQU59):
```
“Unfortunately we had another FEE incident this morning that required the SP3 ccd controllers to be power cycled. The symptoms, however, were different from past occurrences. CCDS3B, the one that failed, remained reachable on the network but the core ccdcontroller part was no longer accessible. A restart attempt (dosctl) failed with an error message that the FEE controller can not be initialized. Not to loose more time I didn’t investigate further and opted for the power cycle. In summary, FEE hung during an exposure, remained accessible on the network, restart with dosctl failed because fee controller could not be initialized. I did not attempt to reboot the FEE. The power cycle worked.”
```

on the subsequent exposures (194739, 40, 41, 42, 43), the r3 and z3 sframesky images are impacted.
and that messed up some redshifts, see e.g. for tileid=9113.
- example of a sframesky file (expid=194739, tileid=21751):
<img width="763" alt="sframesky-20230905-00194739" src="https://github.com/desihub/desisurveyops/assets/61986357/c158d74e-1728-4481-8bf1-6f5753d738f2">

- example of a Z vs. FIBER plot (tileid=9113):
<img width="321" alt="zfiber-tileid9113-20230905" src="https://github.com/desihub/desisurveyops/assets/61986357/976f6078-4046-4404-a802-242003411902">

I have marked TILEID=21751 and 21745 as `"unsure"` (the other two tiles have not reached yet enough efftime to get prompted by `desi_tile_vi`).

**Comment by schlafly** [comment]
Can you also preemptively mark 9113 and 26167 as unsure, either by manually editing tiles-specstatus or by forcing those tiles to show up (--tileids to desi_tile_vi should do it?)?  If we don't mark them unsure now they'll come up later when they get observed, and we'll have to remember why those tiles are special.

**Comment by araichoor** [comment]
sure, thanks for reminding that.
I ve just done it with:
```
desi_tile_vi --prod daily -i tiles-specstatus.ecsv --user raichoor --viewer display --tileids 9113,26167
svn commit -m "set 9113 and 26167 as unsure" tiles-specstatus.ecsv
```
here:
https://desi.lbl.gov/trac/changeset/3010/data/surveyops/trunk/ops/tiles-specstatus.ecsv

**Comment by abhi0395** [comment]
@schlafly I marked "a3" as bad on these exposures and have reprocessed these tiles. TSNR+nightqa have been re-run as well. The reason that I have marked "a3" is because "r3" has a problem, and as discussed in issue #134, missing "r-camera" causes "b" and "z" to fail to compute psf.

**updated nightqa**
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20230905/

**Note:**
For tile **26167** (it was also observed on 20230909, so I have re-processed and updated the nightqa+tsnr for that night as well)

For tile **9113** (it was also observed on 20230913, so I have re-processed and updated the nightqa+tsnr for that night as well)

**Comment by SGontcho** [comment]
I've re-QA-ed all the tiles. I've updated the status of 21751 and 21745 to "good".

For 9113 and 26167 I get the following message when trying to re-QA:

> desi_tile_vi --prod daily -i tiles-specstatus.ecsv --user SGontcho -n 20230905 -t 9113 --viewer display
> INFO:desi_tile_vi:151:main: prod    = /global/cfs/cdirs/desi/spectro/redux/daily
> INFO:desi_tile_vi:152:main: qa dir  = /global/cfs/cdirs/desi/spectro/redux/daily
> INFO:desi_tile_vi:181:main: Found 11508 tiles in tiles-specstatus.ecsv
> INFO:desi_tile_vi:199:main: Includes 1862 tiles with ZDONE=false but EFFTIME_SPEC>=GOALTIME*MINTFRAC
> no tile/night selected

checking with @schlafly

**Comment by SGontcho** [comment]
All QA updated/committed. Closing.
