### ISSUE TITLE
Tile 22842 on 2023-09-08 has string of outlier redshift in petal 1

### ISSUE THREAD

**Issue by SGontcho** [desihub/desisurveyops#138]
Tile 22842 (BRIGHT), observed on 20230908 had a string of z=1.1 targets in petal 1.  Likely linked to z1 CTE issue ?

<img width="729" alt="20230908_tile22842" src="https://github.com/desihub/desisurveyops/assets/8261450/e5ef411d-e404-4046-98a9-c269b338a531">

**Comment by schlafly** [comment]
This is the usual z1/z3 CTE issue; we're accepting these in the hope that an improved CTE correction will address them.  Let's re-VI as good and close.

**Comment by SGontcho** [comment]
Done
