### ISSUE TITLE
Tiles 20740 and 20867 on 2023-09-09 have strings of outlier redshift in petals 1 and 3

### ISSUE THREAD

**Issue by SGontcho** [desihub/desisurveyops#139]
BRIGHT tile 20740 observed on 20230909 marked unsure, clumps of fibers at z=1.1 in petal 1 and 3 on Z v. FIBER plot.
BRIGHT tile 20867 observed on 20230909 marked unsure, clumps of fibers at z=1.1 in petal 1 on Z v. FIBER plot.

Likely linked to z1, z3 CTE issues. Similar to what was signaled in issue #138 

<img width="946" alt="20230909_tile20740" src="https://github.com/desihub/desisurveyops/assets/8261450/1eb94763-e1f6-40f4-ac23-65da317d7bc7">
<img width="942" alt="20230909_tile20867" src="https://github.com/desihub/desisurveyops/assets/8261450/118cdc85-0a27-44f6-ad91-e2a8f65af5bb">

**Comment by schlafly** [comment]
Agreed, this is the usual z1/z3 CTE issue.  We're accepting these; let's re-VI as good and close.
