### ISSUE TITLE
Tile 9497 half amp marked bad due to spurious jump

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#14]
David Schlegel has documented the cause of the spurious jump here.
https://github.com/desihub/desispec/issues/1619

This causes the tile to lose a half amp.  I plan on marking the tile as good anyway, so we'll reobserve objects in that half amp.  Tagging @djschlegel and @sbailey in case they want to overrule.

**Comment by djschlegel** [comment]
Same problem on tile 25275 observed on 20220126 exposure 120334.

**Comment by schlafly** [comment]
This tile is now marked as good.

**Comment by schlafly** [comment]
22230 on 2022-02-11 (expid 122156) is another case of this.
https://github.com/desihub/desisurveyops/issues/24

**Comment by schlafly** [comment]
@akremin , could we reprocess 25275?  This one should be fixed by Julien's CR fix, leading us to save an amp.  I should have gone ahead and marked this as good a month ago, but I only got 9497 at that point, and missed that 25275 was also included.

**Comment by akremin** [comment]
25275 has now been rerun. 

What is the workflow for closing out these tickets? Do I need to add the issue number to the closed_issues.ecsv (https://github.com/desihub/desisurveyops/blob/main/doc/closed_issues.ecsv) list first? Do I do a direct-to-main commit for that?

**Comment by schlafly** [comment]
In this case I still need to re-QA it before we can close the ticket.  This one won't need to go into closed_issues since that is only intended for places where we know the daily processing has issues that it wasn't necessary to prepare.  Feel free to assign it back to me to get it off your plate.

**Comment by schlafly** [comment]
25275 is now marked as good, closing.
