### ISSUE TITLE
Tile 22614 on 2023-09-09 likely CTE issues

### ISSUE THREAD

**Issue by SGontcho** [desihub/desisurveyops#140]
BRIGHT tile 22614 observed on 20230909 marked unsure, clumps of fibers at z~1.1 in petal 1 and trails at z~1.8 in petal 1,3,4,5 on Z v. FIBER plot.

<img width="948" alt="20230909_tile22614" src="https://github.com/desihub/desisurveyops/assets/8261450/7ea28878-a2cd-4d06-a476-5651f65de695">

**Comment by schlafly** [comment]
The feature at z=1.1 on P1 is the "usual" z1 CTE that we're trying to fix but are accepting for now.  I don't think the small number of fibers at z=1.8 are bad enough to hold this tile for (we have much worse bright tiles on the books).  Can you re-VI this as good and close, unless I'm missing something?

**Comment by SGontcho** [comment]
Done.
