### ISSUE TITLE
Tile archiving: consistency check between folders and tiles-specstatus.ecsv

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#141]
Following today s discussed topic, if useful, here are few lines of code which should catch any inconsistency, for the mainbright and maindark tiles, between:
- what s in `$DESI_ROOT/spectro/redux/daily/tiles/archive`
- what s reported as archived in `$DESI_SURVEYOPS/ops/tiles-specstatus.ecsv`.

We could for instance plug that at the beginning of the `run_mtl_loop` script? or else..

I ve tested those lines with the current files, and it says everything is fine; it runs in few seconds.
I could mock up later some fake data to verify it breaks if it should -- i.e. that I didn t mess up the coding.

any comment / suggestion is welcome!

```
import os
from glob import glob
from astropy.table import Table
from desiutil.log import get_logger

log = get_logger()

# what s in the archive
archivedir = "/global/cfs/cdirs/desi/spectro/redux/daily/tiles/archive"
fns = []
for pattern in ["????", "1????", "2????", "3????"]:
    fns += sorted(glob(os.path.join(archivedir, pattern, "*")))

fns = [fn for fn in fns if os.path.basename(fn) != "20210623.try1"]
arch_d = Table()
arch_d["TILEID"] = [int(fn.split(os.path.sep)[-2]) for fn in fns]
arch_d["ARCHIVEDATE"] = [int(fn.split(os.path.sep)[-1]) for fn in fns]
arch_d["TILEID_ARCHDATE"] = ["{}-{}".format(tileid, archdate) for tileid, archdate in zip(arch_d["TILEID"], arch_d["ARCHIVEDATE"])]
# in case of multiple ARCHIVEDATE for a TILEID, only keep the latest ARCHIVEDATE
ii = np.lexsort((-arch_d["ARCHIVEDATE"], arch_d["TILEID"]))
arch_d = arch_d[ii]
_, ii = np.unique(arch_d["TILEID"], return_index=True)
arch_d = arch_d[ii]

# what s in tiles-specstatus.escv
fn = os.path.join(os.getenv("DESI_SURVEYOPS"), "ops", "tiles-specstatus.ecsv")
svn_d = Table.read(fn)
svn_d["TILEID_ARCHDATE"] = ["{}-{}".format(tileid, archdate) for tileid, archdate in zip(svn_d["TILEID"], svn_d["ARCHIVEDATE"])]
sel = (svn_d["FAFLAVOR"] == "mainbright") | (svn_d["FAFLAVOR"] == "maindark")
sel &= svn_d["ARCHIVEDATE"] != 0
svn_d = svn_d[sel]

# tiles in archive, not in tiles-specstatus
arch_sel = ~np.in1d(arch_d["TILEID_ARCHDATE"], svn_d["TILEID_ARCHDATE"])
arch_msg = "nb of tiles in archive, not in tiles-specstatus: {}".format(arch_sel.sum())
# tiles in tiles-specstatus, not in archive
svn_sel = ~np.in1d(svn_d["TILEID_ARCHDATE"], arch_d["TILEID_ARCHDATE"])
svn_msg = "nb of tiles in archive, not in tiles-specstatus: {}".format(svn_sel.sum())

if (arch_sel.sum() == 0) & (svn_sel.sum() == 0):
    log.info(arch_msg)
    log.info(svn_msg)
else:
    if arch_sel.sum() > 0:
        print(arch_d[arch_sel].pprint_all())
        log.error(arch_msg)
    if svn_sel.sum() > 0:
        print(svn_d[svn_sel].pprint_all())
        log.error(svn_msg)
    raise ValueError(arch_msg + " ; " + svn_msg)
```

**Comment by geordie666** [comment]
Sure, I can add something like this to `run_mtl_loop`. I'll assign myself in a `desitarget` issue soon.

**Comment by araichoor** [comment]
thanks @schlafly for the comments.

- "_you could probably handle the weird file name case more cleanly by making your pattern '????????' instead of '*'_." => indeed, yes, thanks, that looks better!
- "_you've excluded SV3, backup, and engineering tiles by ~tileid. Another approach would be to exclude any tileid not in tiles-main.ecsv, which would remove the SV3 and engineering tiles, but not the backup tiles. You could remove those, too, by additionally putting in a PROGRAM != 'BACKUP' check_." => yes, that should also work; and indeed may be more robust to future changes -- or cleaner;
-  "_I imagine you've been careful here because there are some archived BACKUP tiles, but no MTL updates for those archived backup tiles?_" => kind of; I thought that, as only main{bright,dark} tiles are updated in the MTL ledgers, that s the only set of tiles we want to check; but I think nothing prevents to check all tiles, if we wanted to; the risk being to divert the attention of the people doing the dailyops with non-relevant tiles.

if useful, for reference, looking a bit more closely at non-main{bright,dark} tiles, I see that:
- 488 sv3 tiles are archived, and consistently  (ie the same number of sv3 tiles) have ARCHIVEDATE!=0 -- ok;
- 2 mainbackup tiles are archived,  and consistently have ARCHIVEDATE!=0: 41712, 41713 -- ok;
- 26 TILEID > 80000 tiles have ARCHIVEDATE!=0, but are actually not archived; those all are sv2 tiles, except one (TILEID=82264) -- this is inconsistent, but we probably don t care...

and a last remark: note that in my approach, I just check the folder existence, not its content.
I feel it s a safe enough check, and checking individual files may add complexity+computing time, for a little gain; but I mention in case people think we d want to do a per-file check.

**Comment by schlafly** [comment]
FWIW, it looks like 82264 was our first special test backup tile.  I suspect this relates to when we started archiving and what we decided to archive then.  It sounds like requiring the TILEID to be in tiles-main would safely exclude these cases and is probably the most understandable approach.

**Comment by sbailey** [comment]
> [@sbailey](https://github.com/sbailey) , should we get rid of daily/tiles/archive/1000/20210623.try1? I don't remember what that was.

That appears to be a leftover from early tile archive testing; I removed it.

**Comment by schlafly** [comment]
I think we can close this?

**Comment by araichoor** [comment]
as far as I know, yes, as it s now merged in desitarget.

just, to be sure: when running the mtl update with desiproc, it s desitarget/main which is loaded by the `gomtl` command, not some tagged version?

**Comment by schlafly** [comment]
Good point!  No, 2.5.0 for MTL updates.
```
gomtl ()
{
#    source /global/project/projectdirs/desi/software/desi_environment.sh 21.7e
# moving to 22.5 for compatibility with perlmutter
    source /global/common/software/desi/desi_environment.sh 22.5
    module swap desitarget/2.5.0
    export MTL_DIR=$SURVEYOPS/mtl
}
```
Obviously very intentionally to avoid doing MTL updates with different versions of things.  @geordie666 , how concerned do we need to be about updating the desitarget version used for MTL updates?

**Comment by geordie666** [comment]
I think we should definitely make a new tag and run with what will then be `desitarget` `2.7.0`. 

I'd want a little time to do that though, to check we aren't going to immediately break anything. And I'm swamped today. Maybe right after Thanksgiving to avoid breaking anything close to Thanksgiving?

**Comment by schlafly** [comment]
Good.  Yes.  After Thanksigiving makes sense; I'll leave this issue open.

**Comment by schlafly** [comment]
I think we're all done here and can close?

**Comment by araichoor** [comment]
I confirm the `gomtl` command now uses the latest `desitarget/2.7.0` tag.
I m closing this issue.

```
gomtl ()
{
#    source /global/project/projectdirs/desi/software/desi_environment.sh 21.7e
# moving to 22.5 for compatibility with perlmutter
#    source /global/common/software/desi/desi_environment.sh 22.5
# moving to 23.10 for compatibility with desitarget/2.7.0
    source /global/common/software/desi/desi_environment.sh 23.10
    module swap desitarget/2.7.0
    export MTL_DIR=$SURVEYOPS/mtl
}
```
