### ISSUE TITLE
Bad r0 dark on 20230927

### ISSUE THREAD

**Issue by LNapolitano** [desihub/desisurveyops#144]
r0 dark and morning dark for 20230927 are particularly poor. Potentially affects all observations for the night and may be associated with new SM4 mirror. Note that this effect is also present in r0 dark for 20230928 and 20230929 although less significant.

Covers expids: 00198312-00198336 and main-bright tileids: [20691, 22357, 22358, 22280, 23938, 25507, 25505, 26802, 27351, 26801]
 
![20230927-r0dark](https://github.com/desihub/desisurveyops/assets/17151647/2c125aad-714a-426c-8081-86e554595d4a)
![20230927-r0morningdark](https://github.com/desihub/desisurveyops/assets/17151647/ab6ab717-449e-4356-be53-040f9b306191)

**Comment by abhi0395** [comment]
r0 is marked bad for this whole night, tiles reprocessed. In addition, I had to mark r5 as bad for (expid: 198318, tileid 40692) as there were no valid calib stars on that petal for fluxcalibration. nightqa+tsnr updated

https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20230927/

**Comment by schlafly** [comment]
Thanks Abhijeet, @SGontcho , can you clear & repeat QA on this night?  Thanks!
