### ISSUE TITLE
Tiles 26608 and 26610 from 20230929 have multiple SKYCHI2PDF Alerts.

### ISSUE THREAD

**Issue by LNapolitano** [desihub/desisurveyops#145]
Both tiles were observed early in the night on 20230929. Exposure IDs are 00198612 and 00198613.

![20230929-Tile26608](https://github.com/desihub/desisurveyops/assets/17151647/e32a1330-040c-469c-a46d-2758ad6d71fc)
![20230929-Tile26610](https://github.com/desihub/desisurveyops/assets/17151647/bfeafeab-7270-4edb-9ced-42ad210667c3)

**Comment by schlafly** [comment]
These look bad enough that we should mark these exposures as bad.  20230929, expid 198612-198613, tileid 26608 26610.  Thanks!

**Comment by abhi0395** [comment]
exposures (198612-198613, tileid 26608 26610) marked bad for 20230929, tsnr+nightqa have been updated.
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20230929/

**Comment by schlafly** [comment]
@SGontcho , let's go ahead and clear QA and then close this, thanks!

**Comment by SGontcho** [comment]
QA cleared, closed.
