### ISSUE TITLE
skythrurms warnings for tile 6932, expid 191143-191144

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#147]
These two exposures had skythrurms warnings for b5 and b9. Out of an overabundance of caution I marked this tile as unsure but it's probably ok.

![Screen Shot 2023-10-05 at 9 34 12 AM](https://github.com/desihub/desisurveyops/assets/7385438/38b12a82-42ce-475d-9962-572a53682bb4)

**Comment by schlafly** [comment]
Let's mark this as good; I don't see an effect on the redshifts and the sframes look fine.  I wonder if it's also related to the masking of the b sky line; you could add it to https://github.com/desihub/desisurveyops/issues/135.

**Comment by sybenzvi** [comment]
I added this tile to the list in #135 and marked it good. Closing the ticket.
