### ISSUE TITLE
pileup of redshifts at z=1 for tile 5846, expid 199286(7) on 2023-10-03

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#148]
There seems to be a pileup of redshifts right below z=1 in this tile that strikes me as odd. Wondering if this is a candidate for reprocessing, so I marked it unsure.

![Screen Shot 2023-10-05 at 6 54 57 PM](https://github.com/desihub/desisurveyops/assets/7385438/7853dccf-d7c3-4327-a776-72a2cf2bd90b)

**Comment by schlafly** [comment]
Thanks.  I looked on 2023-10-02 for this tile and found 6932 instead, which you had previously flagged here.
https://github.com/desihub/desisurveyops/issues/147
I've now re-marked that one as unsure; the smattering of spectra with redshifts around ~0.9 that I looked at looked marginal to me.

I also looked at this tile.  Roughly a third of the redshifts looked questionable to me, and two thirds looked fine.  @rongpu , would you mind looking at 6932 (20231002) and 5486 (20231003), and trying to decide whether you think they are problematic or not?

**Comment by rongpu** [comment]
OK, thanks. The spectra in 5846 also look fine. I should note that in both tiles, many (most?) of the spectra show visible sky residuals at ~9500A (see the example below), although they does not seem to have affected the redshifts (at least not the z=~0.9 galaxies).
![image](https://github.com/desihub/desisurveyops/assets/16765087/3e30bb1f-1936-41c4-a450-5321d77b274c)

**Comment by schlafly** [comment]
Okay, let's mark these as good as close.  @SGontcho ?  Thanks!

**Comment by SGontcho** [comment]
QA updated, marked as good. Closed.
