### ISSUE TITLE
multiple ZSKYCHI2PDF alerts for tiles 2761 and 11852, 2023-10-04

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#149]
Two tiles with coadds across multiple nights had multiple ZSKYCHI2PDF warnings:
* Tile 2761 (2023-10-02 expids 199152, 199153), first two screen shots below.
* Tile 11852 (2023-10-03 expid 199298, 2023-10-04 expid 199452) final screenshot.

They don't look particularly serious but I marked them unsure for now to be cautious.

![Screen Shot 2023-10-05 at 7 32 02 PM](https://github.com/desihub/desisurveyops/assets/7385438/55178e2a-f54b-4f11-b68f-964dfb1d1d85)
![Screen Shot 2023-10-05 at 7 31 04 PM](https://github.com/desihub/desisurveyops/assets/7385438/11ba3cac-8df0-4816-860f-07a4b6181f43)
![Screen Shot 2023-10-05 at 7 37 43 PM](https://github.com/desihub/desisurveyops/assets/7385438/9856b4aa-931d-4723-a4eb-52e9c49f3de5)

**Comment by schlafly** [comment]
Let's mark these both good.  It's probably noteworthy that they're at the extreme southern boundary of the footprint and so are slow to observe.  There's some weird clumping of redshifts on P4 of 11852 but it's hard to see too much to worry about.  Can you mark good and close?  Thanks!

**Comment by schlafly** [comment]
@sybenzvi , can you mark these as good and close?  Thanks!

**Comment by schlafly** [comment]
I went ahead and marked these as good, closing.
