### ISSUE TITLE
pileup of redshifts at z~1 for tile 1671, expid 199935, 2023-10-07

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#151]
Could be a statistical fluctuation, but there seems to be a pileup of redshifts at z~1 for tile 1671, expid 199935 in petals 1, 8, and 9. Marked the tile unsure for now.

![Screen Shot 2023-10-08 at 3 33 10 PM](https://github.com/desihub/desisurveyops/assets/7385438/a5de1477-0e09-45e2-8b81-5d4aeef006ac)

**Comment by schlafly** [comment]
These cases are hard to adjudicate.  FYI, here is what I did to look at them:
```
night=20231007; petal=1; tileid=1671 ; plot_spectra -i ~/redux/daily/tiles/cumulative/$tileid/$night/coadd-$petal-$tileid-thru$night.fits --rebin 5 --errors --redrock ~/redux/daily/tiles/cumulative/$tileid/$night/redrock-$petal-$tileid-thru$night.fits --zrange 0.9 1.0
```
Roughly half are nice ELGs are half have no signal and some sky subtraction issues get picked up.  Let's discuss on the call but these are likely okay.

**Comment by SGontcho** [comment]
Done, closed.
