### ISSUE TITLE
pileup of redshifts at z~0.9 for tile 11873, expid 199938, 2023-10-07

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#152]
A second tile from 2023-10-07 (tile 11873, exp 199938) looks to have a band of redshifts at z~0.9 across all petals. Seems a bit suspicious so marking it as unsure.

![Screen Shot 2023-10-08 at 3 40 58 PM](https://github.com/desihub/desisurveyops/assets/7385438/a8bb510d-93f5-493b-8d66-f4ec9a6ee957)

**Comment by schlafly** [comment]
Let's discuss on the survey-ops call tonight, but I think we'll end up saying that the redshift histogram looks nominal and the sframes look okay so we'll call it good.

**Comment by schlafly** [comment]
@SGontcho , let's mark this as good and close.

**Comment by SGontcho** [comment]
Done. Closed.
