### ISSUE TITLE
Bright sky trace on exposure 201918 for night 20231021

### ISSUE THREAD

**Issue by geordie666** [desihub/desisurveyops#155]
The redshifts on P1 look bad for tile `22827` from the night of `20231021`:

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/22827/20231021/tile-qa-22827-thru20231021.png

There is a trail to high redshifts for fibers >~ 250 on P1. This is due to a very bright source being extracted near the edge of P1:

<img width="947" alt="201918" src="https://github.com/desihub/desisurveyops/assets/13952581/627691cb-9938-4ff3-9c2d-b7f9ffe9c23a">

As the issue is likely astrophysical rather than instrumental there's probably not much we can do about this, but it's a Sunday so I'm opening this issue for wider discussion.

**Comment by araichoor** [comment]
it s a stuck fiber on a mag=5 star... ouch! (`FIBER=862, LOCATION=1338, TARGETID=-228271338`): https://www.legacysurvey.org/viewer-dev/?ra=343.8067&dec=8.8160&catalog=tmpngldqzwq.

this fiber has become "stuck" on Oct. 17, i.e. few days only before the observation:
```
           TIME           LOCATION STATE     POS_T       POS_P     MIN_P    MAX_P    MIN_T      MAX_T      EXCLUSION    
------------------------- -------- ------ ------------ --------- --------- ------- ---------- --------- ----------------
2022-09-21T17:00:39+00:00     1338      0          0.0       0.0 1.8821365   182.0 -193.84338 190.84338 81e666b0d9f8a699
2023-10-17T17:00:48+00:00     1338      2 -0.084694706 143.42325 1.8821365   182.0 -193.84338 190.84338 81e666b0d9f8a699
```

so I guess it s bad luck...

we observed during 1101s: is there a risk of any instrumental damage?

**Comment by schlafly** [comment]
I think we want to keep this as unsure, mark P1 as bad (we don't want to use those redshifts), reprocess, and then mark good.  @abhi0395 , @akremin ?

**Comment by abhi0395** [comment]
@schlafly Tile has been reprocessed and nightqa+tsnr have been updated. Please feel free to close the issue if things look good to you.
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20231021/

**Comment by schlafly** [comment]
Looks good, thanks Abhijeet, over to @SGontcho .

**Comment by SGontcho** [comment]
Done, closed.
