### ISSUE TITLE
Unstable CCDs on 20231028

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#156]
We have marked all of the bright tiles observed on this night with the exception of 22944 (last tile of night) as unsure.  r2, r3, r5 show some pretty clear "unstable CCD" signatures through around 202419 (r5), 202451 (r2, r3).  This makes sense; this was the first night we came back to observations after network work and turning back on the spectrographs.

There's also a more modest effect on z8 through 202415 that I will probably ignore, as well as on r1, which is harder to diagnose because r1 is being stripey.

The tileqa don't show much to me beyond P2 being problematic in the first bright tile, so I'm inclined to ignore these more modest effects.  I'll come back to this ticket later and try to ask for a more specific set of petals & exposures to be marked bad before reprocessing.

**Comment by schlafly** [comment]
These are all bright tiles where the redshifts are not dramatically affected.  Out of an abundance of caution, I'm going to ask that r2 & r3 be marked bad through EXPID 202451.  @sbailey , is this you this week?

The effects on r5, r1, and z8 are more subtle; let's just accept them.

There's some indication that the redshifts are problematic on P0 & P4 as well in the QA on 83421, the first tile of the night.  Let's not treat that as special, though, because I can't actually spot by eye what's causing the problems there.  But pinging @segasai just to say that this tile was taken with unstable amplifiers and will have atypical residuals.

**Comment by sbailey** [comment]
@schlafly tile 20542 exposure 202421 was reobserved on 20231030 exp 202785 and then flagged as good and archived.  Do you want me to flag r2r3 as bad for this tile on 20231028 and re-process, which then might cause us to re-archive and re-QA?

All other impacted tiles are still in the QA=unsure or none state.  Tile 83421 is the only other case which has been re-observed since 20231028 (on night 20231030 exp 202769).

Note that due to #2128, flagging r2 and r3 as bad takes out the whole petal for those exposures, not just the camera.

For now I will proceed with flagging+reprocessing the other impacted tiles, but will wait to hear from @schlafly about tile 20542.

**Comment by schlafly** [comment]
Thanks, I'll need to dig in there.  20542 had looked finished, so it shouldn't have come up for reobservation, and I thought we had marked all tiles observed on that as unsure, so it shouldn't have been easy for it to be marked good.  Something weird happened here...  yes, let's just leave this one in its current state for now.

**Comment by sbailey** [comment]
I have flagged r2 and r3 as bad for night 20231028 tiles 20524,20525,20938,21252,22881,25220,83421 and reprocessed them, including rerunning tile 83421 on 20231030.  nightqa and tiles/exposures files have been updated.

I did *not* flag or reprocess tile 20542 which had already been QA approved.  Back to you @schlafly for QA wrapup (or post if you need more / different processing).

**Comment by schlafly** [comment]
On the NTS side, because the EFFTIME_ETC for this tile was only 110 s, it got queued for reobservation.  This is one of the usual cases where EFFTIME_SPEC >> EFFTIME_ETC due to bright moon; fine.

I thought we had marked all of the 20231028 as unsure, but presumably I just grepped against tiles-specstatus, which was only giving me the last night, letting this one go through.

It is the case that on the basis of the sframes I would have asked r2 & r3 to be marked as bad and reprocessed.  That said, I don't have any real indication in the redshifts that we should do anything here.  We have two options:
(1) Accept that we have this and move on.  I'll document it in "closed_issues."  We could imagine future improved unstable-amplifier handling could fix whatever minor effect is present.
(2) Go through the reprocess-mtl stuff for this tile.

Anyone want to argue for (2)?  Otherwise I'll do (1).

**Comment by sbailey** [comment]
I don't have a strong opinion betwen (1) and (2), but I'll note a (1.5) option too: flag r2 and r3 as bad on this exposure for future processing, but not bother with reprocessing daily, re-archiving, mtl updates, etc. right now

**Comment by schlafly** [comment]
Okay, let's do your 1.5.  If we ever do something like "reincorporate-iron-into-MTL", this will get swept up with that.  Thanks!

**Comment by sbailey** [comment]
Regarding tile 20542: although I suggested option 1.5 (flag as bad for future, but not reprocess for daily), I no longer like that idea.  Flagging r2 and r3 for 20231028 would cause those two petals to drop below TSNR thresholds, effectively removing those targets from future LSS catalogs despite continuing the survey as-if those targets have been observed fine.

Looking at the QA again, I'm in favor of option (1) "Accept that we have this and move on".

The potentially problematic night with 242s of EFFTIME_SPEC:
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/20542/20231028/tile-qa-20542-thru20231028.png

The cumulative redshifts including another 114s of EFFTIME_SPEC:
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/20542/20231030/tile-qa-20542-thru20231030.png

@schlafly let's discuss/finalize at today's survey ops call (if we are having one)

**Comment by schlafly** [comment]
Okay, we're going to do nothing here.  I've added the tile to the closed_issues file.
