### ISSUE TITLE
Tile 1999 marked as unsure - dome vignetting on exposure 203590

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#159]
In the nightlog for 20231105, here's what happened:

> 23:14 [06:14] Exp. 203590- Not Sure -  - Common error camera B1A and warning B1C. Also warning in. camera Z7B. We are unsure because, although the exposure looks good, we think there might have been some dome vignetting as a consequence of the system not coming back correctly after the glitch that caused the loss of the previous exposure.
EDIT: there was dome vignetting starting about half way through the exposure which increased gradually (as can be inferred from the sky level starting to drop o"). (SO).

Looking at the QA for the corresponding tile 1999, we do not see any problematic effect on the redshifts. However, @schlafly pointed out that the  THRUFRACs are a little unusual. Therefore, we marked that tile as unsure. I am adding this issue to keep track of this situation.

**Comment by schlafly** [comment]
Thanks Jaime.  Yeah, those THRUFRACs are too variable for me, and I'm worried this one will bite us later.  @sbailey , can you mark 203590 on tileid 1999 as bad in the exposure tables, and reprocess this one?  Thanks!

**Comment by sbailey** [comment]
Done.  FTR, 1999 was only observed on 20231105 exp 203590 so "reprocessing" it was flagging it as bad, purging it, and updating tiles/exposures/qa .
```
TILEID  NIGHT   EXPID  EXPTIME EFFTIME_SPEC
------ -------- ------ ------- ------------
  1999 20231105 203590  1548.9          0.0
```

**Comment by schlafly** [comment]
Cleared in QA, done.
