### ISSUE TITLE
Tile 24211 has pile-up at z=1.8 on P7

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#16]
Exposure 120202 on 2022-01-25 (tile 24211) has a pile-up of spurious z=1.8 redshifts on petal 7.
<img width="826" alt="1" src="https://user-images.githubusercontent.com/7918018/151251031-613f8ece-45dc-412d-b694-409ee53ef785.png">

**Comment by schlafly** [comment]
This is a mystery to me.  The sframe looks great.  THRUFRAC is very low on P7, but with low calibration RMS, and somehow the low THRUFRAC doesn't result in low EFFTIME or the petal being thrown out.
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/24211/20220125/tile-qa-24211-thru20220125.png
Something is wrong with P7, but I haven't seen this before.

**Comment by julienguy** [comment]
The flux calibration in b7 is completely wrong, so wrong that this generates a step in the output spectra. This is a rare failure not seen before.
```plot_frame -i ~/redux/daily/exposures/20220125/00120202/cframe-*7-00120202.fits --std --rebin 10```
![Figure_1](https://user-images.githubusercontent.com/5192160/151423799-1512e2f5-d342-4507-8e12-00131fae2052.png)

The tile QA is correctly reporting this issue.

**Comment by julienguy** [comment]
Fixed in https://github.com/desihub/desispec/pull/1667

**Comment by akremin** [comment]
Files reprocessed and tables updated. Back to Eddie for QA/specstatus

**Comment by schlafly** [comment]
Now marked as good, closing.
