### ISSUE TITLE
Tile 8697 marked as unsure - redshift pileup around z~0.3

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#160]
<img width="1099" alt="Captura de Pantalla 2023-11-11 a la(s) 2 17 33 p  m" src="https://github.com/desihub/desisurveyops/assets/1848618/1fe26947-f4e7-4f3f-8b31-015d33b5b2e0">

Tile 8687 observed on two exposures (204269 and 204270) on 20231110 shows some  redshift pileup around z~0.3 on petals 2, 4, 5, 6, 7 and 9. 

Looking at the sky sframes for those two exposures, one issue that might be relevant is that there are some bright columns across the r-band camera. That column is not prominent on all the other dark exposures, and might be contributing the redshift pileup.

<img width="1076" alt="Captura de Pantalla 2023-11-11 a la(s) 2 31 41 p  m" src="https://github.com/desihub/desisurveyops/assets/1848618/aa6b5986-f78c-469d-8dab-929b90f7c2d6">

<img width="1080" alt="Captura de Pantalla 2023-11-11 a la(s) 2 31 48 p  m" src="https://github.com/desihub/desisurveyops/assets/1848618/de982597-40dd-49b4-add8-129f35e3bd91">

**Comment by schlafly** [comment]
This looks like the same kind of H-alpha emission you spotted the other day, together with a lot of z=0 false redshifts, and is in the same part of the sky?

**Comment by forero** [comment]
The lot of z=0 false redshifts in this tile I attribute to H-alpha. It is the same part of the sky we spotted the other day. However, the z=0.3 pileup does not show in the other tiles around the same region.

**Comment by schlafly** [comment]
This just looks like especially bad nebular emission to me; apparently 0.3 is another attractor.  sframes look fine except for the bright nebular emission.  I've marked good and am closing.
