### ISSUE TITLE
Tile 22543 on 20231122

### ISSUE THREAD

**Issue by SGontcho** [desihub/desisurveyops#162]
Bundle of fibers at z=1 in petal 1. 
Similar to issues observed previously, but tile marked as unsure to safe. 

<img width="423" alt="Screen Shot 2023-11-23 at 10 00 12" src="https://github.com/desihub/desisurveyops/assets/8261450/17f71357-351c-4bd1-8ab1-c6b3400e6a15">

**Comment by schlafly** [comment]
This is the usual z1 CTE issue and can be marked good, thanks!

**Comment by SGontcho** [comment]
Ok, first time I am seeing it in 3 days, so I guess that's good! 
I'll mark this tile as good.
