### ISSUE TITLE
Night 20231123, VCCD on Z2 issue

### ISSUE THREAD

**Issue by SGontcho** [desihub/desisurveyops#163]
VCCD was off for Z2 for some time during the end of the night on 20231123.
The following tiles were flagged as 'unsure'.

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/21894/20231123/tile-qa-21894-thru20231123.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/25069/20231123/tile-qa-25069-thru20231123.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/21942/20231123/tile-qa-21942-thru20231123.png

**Comment by schlafly** [comment]
Looking at the redshifts and sframes, I think these are fine.  Can you go ahead and repeat QA for them?  Thanks!

**Comment by schlafly** [comment]
@SGontcho , pinging this ticket.

**Comment by schlafly** [comment]
Can we clear this?  Thanks!
