### ISSUE TITLE
Tile 20630 is very shallow on petals 5 and 8

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#165]
Bright tile 20630 was observed on 2023-05-01 and completed much later on 2023-02-05.  It shows as very low efftime on petals 5 and 8.  For petal 8, this is explained by many of the fibers not positioning on the 05-01 night.  For petal 8, I have no immediate explanation.  I've marked this tile as "unsure" in QA.
![tile-qa-20630-thru20231205](https://github.com/desihub/desisurveyops/assets/7918018/04a11352-33d9-452d-b287-53a208d1552a)

**Comment by araichoor** [comment]
[for the record, there s a typo in the previous message: "_much later on 2023-02-05._" => it s on 2023-12-05]

my understanding from a quick look:
- on expid=178578 from 20230501: petal 8 have all fibers 4250-4499 with `EFFTIME_SPEC=0`;
- on expid=208237 from 20231205: petal 5 is not reduced (as for all exposures from that night), hence all fibers there have `EFFTIME_SPEC=0`.

the combination of those two explain the "orange" patterns in the tile-qa plot, where the "orange" regions only have one exposure.
makes sense?

**Comment by schlafly** [comment]
The good half of P5 got processed.  @SGontcho , can you reQA and close?  Thanks!

**Comment by schlafly** [comment]
Let's reQA and close.
