### ISSUE TITLE
b3 restart in middle of observing night 20231215

### ISSUE THREAD

**Issue by LNapolitano** [desihub/desisurveyops#170]
Quoting Anand on slack: "however, I notice that b3 has been re-started in the middle of the night, before expid=209982 (see the VCCDSEC alerts); we see some effect in the Z vs. FIBER on the bright tiles, also in the skyzfiber plot." With this in mind I've marked all exposures following the restart as unsure.

This effects expid 209982-210003 and tileids: [4488, 5548, 9164, 9188, 20333, 20334, 20366, 21905, 21921, 26872, 27680, 27682, 27799]

**Comment by schlafly** [comment]
@araichoor , good catch, but the b cameras are pretty immune to this instability issue.  The sframe for 209981 and 209982 look similar and good to me on b3.  I suspect the skyzfiber P3 issue is our long term z3 CTE / offset issue, so I would lean towards marking these all good.  Do you see anything else?

**Comment by araichoor** [comment]
no, nothing else; I was mostly waiting for your input.
your analysis sounds good to me, e.g. 20231216 bright tiles have the ~same pattern in petal=3, hence we cannot blame b3.
@LNapolitano: could you turn those back to "good"? (sorry for all the extra-work!)

**Comment by LNapolitano** [comment]
@araichoor sure thing, I'll re-QA those tiles today so we can close the issue. Thanks all.

**Comment by LNapolitano** [comment]
The tiles noted in my original comment have all been changed from unsure to good, I'll go ahead and close this issue.
