### ISSUE TITLE
20240105 and 20240106 dark tiles have suspicious nz on dark tiles, especially for petals 1, 6, and 7

### ISSUE THREAD

**Issue by ashleyjross** [desihub/desisurveyops#173]
I have initially marked all of the tiles as unsure. My guess is that we will mark these good (it seems similar to the petal 1 issue that has been with us for a while), but this issue can document everything.

<img width="963" alt="Screenshot 2024-01-07 at 2 19 52 PM" src="https://github.com/desihub/desisurveyops/assets/14100086/0ac3ec49-9ffe-4cc4-a6fe-d51443710f32">
<img width="1068" alt="Screenshot 2024-01-07 at 2 06 06 PM" src="https://github.com/desihub/desisurveyops/assets/14100086/0d7e1c27-9b5f-4d23-9515-29704f9349fa">
<img width="365" alt="Screenshot 2024-01-06 at 5 16 10 PM" src="https://github.com/desihub/desisurveyops/assets/14100086/cef04a46-ef1f-4508-9e90-c55d92dc41f2">
<img width="375" alt="Screenshot 2024-01-06 at 5 13 31 PM" src="https://github.com/desihub/desisurveyops/assets/14100086/7ded6f72-b862-490c-8328-da39853e5998">

**Comment by schlafly** [comment]
We addressed this by adding new sector offsets on r1, z3, r6, and r7.  This doesn't appear to affect LyA, so we won't reprocess, though the next product should get these updates.  Can you mark good and close?  Thanks!

**Comment by schlafly** [comment]
Ashley or Satya, can we mark these as good so that we can get them in to the next MTL?

**Comment by ashleyjross** [comment]
I just marked them good. Sorry for the delay!
