### ISSUE TITLE
more suspicious n(z) on dark tiles from 20240108

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#175]
For 20240108, there are some patterns in the dark tile n(z) distributions similar to what @ashleyjross reported in #173, with the distribution in several petals looking uncomfortably close to the sky fiber n(z) -- specifically, redshifts piling up in similar locations in certain petals. The effect is more subtle than what appeared in 20240106. Also observed step-like structures in the sframes similar to observations from 20240106.

I marked the following dark tiles as unsure after squinting at them and the sky fiber z distribution and deciding there were enough similarities to warrant a ticket.

* Tile 003545 expid 00218108
* Tile 003690 expid 00219129
* Tile 003926 expid 00218113
* Tile 005105 expid 00218111
* Tile 006204 expid 00218119
* Tile 006205 expid 00218121
* Tile 006674 expid 00218110
* Tile 007104 expid 00218117
* Tile 010234 expid 00128118
* Tile 010866 expid 00218125

![Screenshot 2024-01-09 at 8 02 25 PM](https://github.com/desihub/desisurveyops/assets/7385438/41a76feb-8c0c-42b0-915c-441c0e89c174)
![Screenshot 2024-01-09 at 7 32 31 PM](https://github.com/desihub/desisurveyops/assets/7385438/9f8ba64c-e6d4-4b87-a8fc-64171d0f8104)
![Screenshot 2024-01-09 at 7 35 26 PM](https://github.com/desihub/desisurveyops/assets/7385438/f74d3412-e58b-4fc5-a797-00092badad3d)
![Screenshot 2024-01-09 at 7 38 01 PM](https://github.com/desihub/desisurveyops/assets/7385438/d31bf366-acb4-475c-af6c-94edfa3598a6)
![Screenshot 2024-01-09 at 7 40 13 PM](https://github.com/desihub/desisurveyops/assets/7385438/76868384-85cb-4105-8c11-bedf9d73c200)
![Screenshot 2024-01-09 at 7 45 25 PM](https://github.com/desihub/desisurveyops/assets/7385438/9049f26e-e01e-4bb0-8d05-f4cf29f53fe3)
![Screenshot 2024-01-09 at 7 47 32 PM](https://github.com/desihub/desisurveyops/assets/7385438/145c6bb5-d176-4602-815b-0391155a047c)
![Screenshot 2024-01-09 at 7 49 34 PM](https://github.com/desihub/desisurveyops/assets/7385438/c370c1ea-eaea-42d6-b366-3b3c9a3d74b8)
![Screenshot 2024-01-09 at 7 52 44 PM](https://github.com/desihub/desisurveyops/assets/7385438/c7f73d15-067a-4506-a02a-36ba0ed54021)
![Screenshot 2024-01-09 at 7 56 55 PM](https://github.com/desihub/desisurveyops/assets/7385438/cd226271-bf85-403e-96ab-866a6c735f8d)
![Screenshot 2024-01-09 at 7 59 08 PM](https://github.com/desihub/desisurveyops/assets/7385438/933db3d9-4f24-4a7a-8615-d7814d962207)

**Comment by schlafly** [comment]
This is due to a combination of new CTE on r7, known but uncorrected CTE on r1, and CTE on r6 and z3 affecting the rest of the amps.  I've added sectors to the yaml files and committed them today.  The results look quite good on 20230105, so let's mark these as good.  We do not plan to reprocess them as the LyA decisions look good.  Can you mark good and close?

**Comment by sybenzvi** [comment]
All tiles from 20240108 marked as good.
