### ISSUE TITLE
Large continuum noise in red in 20240129/222260, tileid 20711

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#177]
![image](https://github.com/desihub/desisurveyops/assets/1417841/e88d0a6c-2a3f-4cb1-8da0-ec8308bbdea6)
The sky subtraction residuals on 20240129/222260, tileid 20711 are pretty bad.  This impacts the final redshifts.  We should discard this bright exposure and reprocess 20711 without it.  This was the first tile of the night; maybe a twilight thing??

**Comment by abhi0395** [comment]
@schlafly 
I have marked 20240129/222260, tileid 20711 as bad and reprocessed. This tile was also observed on 20240130; I have re-processed that as well. nightqa and tsnr have been updated for both nights. Please feel free to close the ticket if everything looks fine to you.

**Comment by schlafly** [comment]
This looks good to me, closing.  For my own records, I am leaving the tile as "unsure" because the 20240130 exposure is also problematic due to the unstable CCD issue.
