### ISSUE TITLE
CCD instability on 20240130

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#178]
All tiles on 20240130 suffered from some remaining instability on z1 due to work on the FEE software during the day.  Even in the morning darks things look pretty bad.
![image](https://github.com/desihub/desisurveyops/assets/1417841/0798606f-188e-458b-b976-0309da81c5ee)
There is a pretty clear impact on the sky redshifts on z1 and I will ask for it to be marked bad for the entire night.  There are smaller signals on r3 and z5; I will likely ask for r3 to be marked bad for the first half of the night, and will neglect z5.  But I need to revisit this more carefully tomorrow.  All tiles have been marked unsure.

**Comment by schlafly** [comment]
Sorry for the delay.  Let's do the following:
- z1 on 20240130 should be marked bad on all science exposures.
- r3, z5 on 20240130 should be marked bad for exposures with IDs 222463 through 222471.
Then we need to reprocess the affected tiles and clear QA.

**Comment by schlafly** [comment]
Just pinging on this one, thanks!

**Comment by abhi0395** [comment]
@schlafly re-processing is complete, nightqa and tsnr have been updated. I have marked `a1` as bad for all science exposures and `a35` for `expid: 222463 - 222471`. Please close the ticket if everything looks fine.

**Comment by schlafly** [comment]
Thanks, looks good, I've updated QA and am closing.
