### ISSUE TITLE
Tiles marked as unsure after r3 FEE crash on 20240321

### ISSUE THREAD

**Issue by rongpu** [desihub/desisurveyops#184]
After the r3 FEE crashed last night, the sky residuals show a "glow" pattern that mostly decayed away after a few exposures. Below is the exposure immediately after the crash (the corresponding tile QA: https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/21767/20240321/tile-qa-21767-thru20240321.png).

We decided to reprocess all tiles that were observed after the crash without r3. These tiles are: 21767, 4379, 2825, 20025, 20017, 20046, 21768, 21774, 23369

<img width="909" alt="Screenshot 2024-03-22 at 9 35 36 AM" src="https://github.com/desihub/desisurveyops/assets/16765087/c2411457-5750-4ade-a32b-2c774fba86a0">

**Comment by akremin** [comment]
@rongpu can you please provide the amplifier so that we can just flag the amp impacted by the FEE restart?

**Comment by rongpu** [comment]
From the morning dark it looks like at least two amps, C & D, are affected (see below). @schlafly could you advise here?
<img width="445" alt="Screenshot 2024-03-22 at 1 59 06 PM" src="https://github.com/desihub/desisurveyops/assets/16765087/ff737a01-e8b7-4307-9b96-602792f771bc">

**Comment by rongpu** [comment]
I have reprocessed these tiles with the entire petal 3 flagged as bad.

**Comment by schlafly** [comment]
Thanks Rongpu.  Yes, our normal procedure for these "unstable CCD" issue is just to flag the whole petal.  Usually the effect more obviously extends to all 4 petals, but I think just flagging everything is the most expeditious approach here.

**Comment by schlafly** [comment]
These were reQAed as good, closing.
