### ISSUE TITLE
Should tertiary executable scripts be moved elsewhere from bin/?

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#185]
I am not very familiar with the habits of github different folders.

But I realized that having the `desi_fba_tertiary_{prognum}` scripts in `bin/` makes them "available" when one loads desisurveyops.
These scripts are the ones I use to the design the tertiary programs tiles.
Storing those files in github is more for book-keeping of what we have done rather than to re-use these scripts.

So I am wondering if it would not be better to put those in another folder; I think I remember from some `fiberassign` discussion that for instance the`etc/` folder could be used for such goals.
Or maybe it is ok to leave those in `bin/`, I don t know.

@schlafly? @sbailey? @geordie666?

**Comment by geordie666** [comment]
My 2 cents: I think those scripts are sufficiently uniquely named that it isn't really a problem to have them in `bin/`. It seems unlikely that anyone (or any automated code) would accidentally trigger them by mistake?

**Comment by akremin** [comment]
Right now I count six scripts plus a wrapper script with very similar names. I think it is fine to leave them, but also fine to move them if you prefer. If we get to the point where there are 30+ such scripts and it becomes difficult to find the non-fiberassign scripts in `bin` with e.g. `ls`, then my opinion might change. For now, I personally think it's fine.

**Comment by geordie666** [comment]
I think we converged on the location of these scripts, so I'm going to close this issue.
