### ISSUE TITLE
Marked 2 tiles as unsure due to r5 and z5 CCD restart at the end of night 20240402 

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#187]
At the end of night 20240402  r5 and z5 CCDs had to be restarted. Following the restart, three bright tiles were observed: 26720, 26723, and 27191. Despite the reasonable redshifts, tiles 26720 and 26723 were marked as unsure during QA. Tile 27191 did not appear during QA because it did not accumulate enough effective time.

Here is how the z5 morning dark looks like

![z5 morning dark 20240402](https://github.com/desihub/desisurveyops/assets/1848618/5b42b72e-0178-4e15-bbc4-662a670c6f05)

**Comment by schlafly** [comment]
Can we mark z5 as bad on the last three exposures on the night, 233955-233957?  Corresponding tile IDs 26720, 26723, and 27191, on 20240402.  Then reprocess and we'll reQA?

**Comment by abhi0395** [comment]
@schlafly Marked "a5" as bad for exposures 233955-233957 from 20240402, re-processed and tsnr+nightqa have been updated. Please close the issue if everything looks fine.

**Comment by schlafly** [comment]
Thanks Abhijeet.  I think I was expecting just z5; is a5 intentional?

**Comment by akremin** [comment]
The current code can't fit standard stars without all 3 arms/cameras. Given r5 was also rebooted and potentially unstable, I view this as less of a loss than other nights where we genuinely throw out two good arms.

**Comment by schlafly** [comment]
Okay, your call.  I'm not worried about r5 based on the darks & sky residuals, but if you want to do a5, sounds good.

**Comment by forero** [comment]
Just marked 27191 as unsure

**Comment by schlafly** [comment]
These three have now been marked good, closing.
