### ISSUE TITLE
All tiles observed on the night of 20240403 marked as unsure due to multiple problems/doubts

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#188]
As I said on slack:

> I am not sure if it's me being paranoid/primed by the information about the three FEE crashes, but I feel like I am seeing some structure/clumpiness in the redshifts. Some of the clumpiness in Petal 3 and 7 is marked with QAFIBERSTATUS!=0, but I suspect that others cases may have been overlooked. However, the overall histograms for the redshifts appear reasonable.
Last night the FEE errors appeared on SP4 R, SP6 R and SP8 R. Besides, the morning dark in B7 seems to have more structure than usual and the clumpiness in the sky redshifts in Petal 1 continues to be there.
So, there seems to be a lot going on. I am inclined to mark everything as unsure!

In total, I marked 24 dark and 1 bright tile as unsure.

**Comment by forero** [comment]
![b7 morning dark 20240402](https://github.com/desihub/desisurveyops/assets/1848618/6e5e6e35-92a5-48ba-8773-906557b12f52)

**Comment by forero** [comment]
![Screen Shot 2024-04-04 at 2 45 50 PM](https://github.com/desihub/desisurveyops/assets/1848618/0463e492-8fcc-421a-b218-88919c269206)

**Comment by forero** [comment]
![Screen Shot 2024-04-04 at 2 51 22 PM](https://github.com/desihub/desisurveyops/assets/1848618/31e91571-8b46-4d4a-8f01-40ff45a19fb2)

(masked) structure on petals 3 and 7

**Comment by forero** [comment]
![Screen Shot 2024-04-04 at 2 52 41 PM](https://github.com/desihub/desisurveyops/assets/1848618/ad284567-cce1-405b-881d-51830d63cfa9)
 unmasked pileup between petals 0 and 1?

**Comment by schlafly** [comment]
The story with what cameras got reset is confusing here.  According to the log, R4, R6, R8.  According to VCCDSEC, here's the history of restarting...
R1, R4: before 234079 (R1 first, R4 330 afterward, only this exposure)
R6: before 234091
Z8: before 234103
R6: before 234129
Given the correlation with the logged devices, and the fact that Z8 shows a weird dark, my inclination is to believe the VCCDSEC.

I only see issues in the sframes or sky redshifts for P8.  I propose that we mark Z8 on 234105 as bad and reprocess.

The rest of this night looks good to me.  The other mystery to unravel would be whether there is a potential issue with VCCDSEC recording the wrong thing, as the log indicated different devices got reset than what that records.

**Comment by schlafly** [comment]
@akremin , @abhi0395 , can you mark z8 on 234105 as bad and reprocess this exposure?  Thanks!

**Comment by schlafly** [comment]
(note this is a split exposure with another observation on 20240406; tile 26690)

**Comment by abhi0395** [comment]
@schlafly I marked "a8" as bad for exposure 234771 (tile 26690, night 20240403) and re-processed that tile. As mentioned [here](https://github.com/desihub/desisurveyops/issues/187#issuecomment-2037587762), the current code can not fit standard stars without all 3 arms/cameras. But I commented that it's due to z8 for future reference.

Then, I also re-processed tile 26690 on 20240406, given that we had reprocessed the previous night's observation.

tsnr and nightqa have been re-run for both nights.

Please close the issue if things look fine to you.

**Comment by schlafly** [comment]
Thanks, looks good, closing!
