### ISSUE TITLE
Tile 6157 observed on 20240404 marked as unsure due to feature in redshift distribution 

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#189]
I believe there might be a notable pattern in the redshift distribution between petals 0 and 1 on tile 6157 (observed on 20240404, exposure 234297).

You can see the QA plot here:
![unsure tiles from 20240404](https://github.com/desihub/desisurveyops/assets/1848618/dc5eee00-afe2-4ce5-9f35-593e4e758aa8)

This feature appears similar to what was observed on tile 10015 the night before, on 2024003. Here's the image:

![Screen Shot 2024-04-04 at 2 52 41 PM](https://github.com/desihub/desisurveyops/assets/1848618/d8c2772a-3307-4557-8489-a73b95385eba)

To me, it seems like there's a cluster of redshifts between petals 0 and 1, surrounded by emptier regions. However, I might be reading too much into the data. I'd really appreciate a second opinion on this.

**Comment by schlafly** [comment]
This does look a bit fishy, but I can't corroborate any issues with things in the sframes or sky redshifts, and the redshift histograms look fine, so I am going to go ahead and mark good.
