### ISSUE TITLE
Bias variation in b8 causes jump in spectra

### ISSUE THREAD

**Issue by rongpu** [desihub/desisurveyops#19]
The bias variation in b8 causes jump in spectra, which results in some features in sky Z vs. FIBER plot and lower-than-normal success rate of LRGs, and it's particularly noticeable for the night of 2022-02-02:

Sky Z vs. FIBER plot: https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20220202/skyzfiber-20220202.png

Example of affected spectrum:
![example](https://user-images.githubusercontent.com/16765087/152421615-11ec6961-10a3-48b7-9888-bcaccada7717.png)

**Comment by julienguy** [comment]
This issue is also reported in https://github.com/desihub/desispec/issues/1656 .

**Comment by schlafly** [comment]
Added to closed_issues; closing.
