### ISSUE TITLE
redrock files missing from archive folder

### ISSUE THREAD

**Issue by ashleyjross** [desihub/desisurveyops#191]
When doing LSS processing for DA2, I noticed that tiles 25257, 22855, 22245, 24563, 22856, 23823 have no redrock files in the archive folder the LSS code gets pointed to. All six have a thru date of 20221209. The archive data is 20230922 for all except 22856, which has 20230920.

The archive folders do all have zmtl files.

**Comment by schlafly** [comment]
See https://github.com/desihub/desisurveyops/issues/88#issuecomment-1732100860 .  I think these are cases where we marked the whole tile as bad post facto.

**Comment by ashleyjross** [comment]
@geordie666 confirmed that everything here is as expected. These were re-archived tiles after setting the observations as bad, as described in https://github.com/desihub/desisurveyops/issues/88
