### ISSUE TITLE
Bright tile 23163 marked as unsure

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#198]
Tile 23163 has a cluster of spurious redshifts in petal 7

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/23163/20240609/tile-qa-23163-thru20240609.png

I marked the tile as "unsure" during QA.

**Comment by schlafly** [comment]
This is in the same situation as https://github.com/desihub/desisurveyops/issues/197; let's go ahead and mark these as good for now, and do the archiving & MTLing.

**Comment by forero** [comment]
Marked as good.
