### ISSUE TITLE
Tile 4402 rejects half fibers on r8 due to CTE in amp region

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#20]
Tile 4402 on 2022-02-05 expid 121487 which rejects fibers 4250-4499 due to a cosmic appearing at location (2197,3718) of the r8 CCD. This has OSTEPD=5.7 in the frame file.  Corresponding spectro issue is https://github.com/desihub/desispec/issues/1619 .

Below is a cutout of the raw image centered on (2197,3718).
<img width="274" alt="Screen Shot 2022-02-06 at 12 22 50 PM" src="https://user-images.githubusercontent.com/7918018/152845368-2f364c41-1b09-4ea8-951c-243b6074f383.png">

**Comment by schlafly** [comment]
Entered in closed_issues; closing.  https://github.com/desihub/desisurveyops/commit/6492fc131aeaf9e8c438df1f8ab739035bf341c6
