### ISSUE TITLE
Reprocess tiles with "old" QN weights instead of new QN weights

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#200]
Christophe reports that the new QN weights lead to somewhat worse quasar identification in certain redshift ranges.  We want to replace the new QN weights with the old weights from daily until this is sorted out.

This affects all tiles since the restart on 20240603, though only the dark tiles are especially important.  The highest priority are the un-MTLed tiles, observed since 20240611.  For these tiles we could reprocess them and it would be "as if" we used the old weights.  At lower priority we will look at the tiles observed from 20240603 -- 20240610, where we would have to update the MTLs in order to incorporate a new processing.

The high priority tiles for reprocessing are the ones in the tiles-specstatus file that are good (i.e., tile done), not archived (no MTL update), and observed since the restart.  I select these as follows:
```
marchive = tspec['ARCHIVEDATE'] > 0
mdone = tspec['QA'] == 'good'
mrecent = tspec['LASTNIGHT'] > 20240600
tspec[['TILEID', 'LASTNIGHT']][~marchive & mdone & mrecent]
```
Note that the recency cut is needed to reject a small number of weird-program tiles that were marked as good and archived but aren't part of the main survey.

Those cuts produce the following list of 94 tiles, of which 51 are dark tiles.  I list the TILEID and LASTNIGHT for each tile.
```
2992 20240611
3376 20240611
3443 20240611
3449 20240611
3454 20240615
3462 20240614
3475 20240614
3485 20240614
4335 20240611
4336 20240611
4444 20240615
4546 20240611
4568 20240611
4963 20240614
5025 20240614
5323 20240616
5690 20240616
5759 20240616
5957 20240614
6123 20240614
6593 20240615
6598 20240614
6599 20240615
6622 20240616
6769 20240615
7502 20240614
7503 20240611
7657 20240611
7677 20240611
7678 20240615
7765 20240616
8088 20240614
8120 20240615
8163 20240611
9019 20240611
9214 20240614
9313 20240616
9318 20240616
9322 20240615
9641 20240611
9869 20240614
10465 20240614
10615 20240614
10635 20240611
10898 20240615
11242 20240611
11259 20240615
11267 20240614
11276 20240614
11285 20240615
11295 20240615
20041 20240615
20202 20240614
20203 20240614
20521 20240614
20522 20240614
20829 20240611
21230 20240615
21582 20240615
21586 20240615
21595 20240615
21608 20240615
21619 20240614
21789 20240614
21802 20240611
21803 20240611
22771 20240614
22829 20240615
23146 20240614
23171 20240615
23345 20240614
23358 20240611
24703 20240616
24705 20240614
24709 20240616
24737 20240615
24935 20240614
26365 20240615
26608 20240616
26701 20240615
27024 20240616
27025 20240616
27037 20240616
27049 20240616
27052 20240616
27164 20240616
27165 20240616
27166 20240616
27167 20240616
27168 20240616
27169 20240616
27186 20240616
27187 20240616
27198 20240616
```

**Comment by akremin** [comment]
Just double checking -- we don't have any completed dark tiles in the past two weeks that don't have QA == 'good', correct? I don't think we do, so I think QA == done is equivalent to all completed tiles, but I am checking since what we want is all completed tiles. I'm assuming you did it this way because there was no simple way to select the completed tiles directly, which I am perfectly happy with.

**Comment by akremin** [comment]
Also confirming for the record, we are only reprocessing dark tiles since the only things impacted are quasars, correct?

**Comment by geordie666** [comment]
So:

(1) No _behavior_ in the bright MTLs is governed by whether something is deemed to be a LyA quasar or not.
(2) _But_ we do propagate QN-derived columns (`IS_QSO_QN`, `Z_QN`) into the bright MTLs. 
 - We also _do_ make the `zmtl` files and put them in the `archive` directories for bright tiles.

So, I think to be complete we'd need to reprocess the bright tiles, too. Sorry!

OTOH, I'm not sure anyone ever actually directly uses the QN information in the bright MTLs or `zmtl` files. So, if we cared about expediency and not completeness then we could gloss over this detail and just document the bright tiles for which we used an inconsistent version of QuasarNet.

**Comment by schlafly** [comment]
Yes, only the dark tiles are urgent, but we should reprocess both sets of tiles eventually for consistency eventually.  That could be as late as next prod time for the bright tiles.  But I figured it might be easy for you to process both now; your call. 

Re QA = good, yes, we're up to date now so this was an easy way to get done tiles.

**Comment by akremin** [comment]
Thank you both for the replies. I'll proceed with all dark and bright tiles in this list.

**Comment by akremin** [comment]
For all 94 tiles I have removed the `qso_qn*`,` zmtl*`, and `tile-qa*` files (moving them to `/global/cfs/cdirs/desi/spectro/redux/daily/run/scripts/custom/quasarnet_reproc_20240617/old_quasar_netfiles` in case we want to compare them in the future).
We then updated the quasarnet afterburner to use the old weights file, `QN_MODEL_FILE=/global/cfs/cdirs/desi/target/catalogs/lya/qn_models/qn_train_coadd_indtrain_0_0_boss10.h5`. 
Then I reran all 94 scripts to regenerate the files that we removed. I then reran the nightqa for all 4 nights impacted.

For posterity: scripts and old files and logs can be found at `/global/cfs/cdirs/desi/spectro/redux/daily/run/scripts/custom/quasarnet_reproc_20240617`.

All 94 tiles are ready for evaluation. Impacted nights are 20240611, 20240614, 20240615, and 20240616.

**Comment by schlafly** [comment]
I looked at QA and everything looks sane to me.  I also compared the new zmtls in daily with the old zmtls you saved and verified that the new zmtls contain more QN quasars than the old ones did.
![image](https://github.com/desihub/desisurveyops/assets/1417841/8757291e-4630-440b-86a5-a5e4f0518a16)
I'm not sure how many is too many more, but at least the correlation is clear and the new versions have more quasars.

**Comment by schlafly** [comment]
We're now happy and the new files have been MTLed.  The remaining question is how important it is to reprocess & rearchive & reMTL older tiles.  @geordie666 , I show below the IS_QSO_QN quasar identifications, but I didn't look hard enough or figure out how to go all the way to "would we have identified this as a LyA quasar?"  I think that's the important question from the perspective of whether we go back and fix all of the old MTLs in this time period.  Is that an easy question to answer?

**Comment by geordie666** [comment]
@schlafly: That's certainly a question I can answer. I think I'll have to run the old/new versions of the MTLs through the actual code, though, given the special cases.

So, it's just a question of hooking everything together. I can try and answer that question this week (I'll be slower then normal due to the review).

**Comment by schlafly** [comment]
Thanks Adam.  I'm just not familiar enough with the LyA logic, but I think I would also just be happy comparing something like (IS_QSO_QN | IS_QSO_RR) & (z > 2.1) or whatever the detailed LyA cut is, before and after.  As you say, it would be better to go through the MTLs---that's the only way we'd be able to reproduce things like exactly which targets are affected due to first observations, etc.---but I guess from my plot above it's a 5-10% effect in IS_QSO_QN, which sounds meaningful.  But it's less clear to me if that's 5-10% for LyA QSOs or if objects at LyA redshifts are relatively unaffected and this primarily affects some other redshift regime.

**Comment by geordie666** [comment]
I'm set up now to do this fully though the complete MTL logic. Perlmutter is down today, though, so it'll be another day before I report in.

**Comment by geordie666** [comment]
I've run the actual MTL loops for the old and new version of the QN weights, which I'm referring to as "kremin" for the `zmtl` files in `/global/cfs/cdirs/desi/spectro/redux/daily/run/scripts/custom/quasarnet_reproc_20240617/old_quasar_netfiles` and "archive" for the files in the standard location of `/global/cfs/cdirs/desi/spectro/redux/daily/tiles/archive/`.

The resulting full state of the MTLs after processing with these different sets of redshifts are available in:

`/pscratch/sd/a/adamyers/mtlkremin/trunk/mtl`
`/pscratch/sd/a/adamyers/mtlarchive/trunk/mtl`

The subset of ledgers that were changed for the 51 dark tiles are listed in `/pscratch/sd/a/adamyers/mtlkremin/kremin-file-changes.ascii`, e.g.:

```
fns = Table.read("/pscratch/sd/a/adamyers/mtlkremin/kremin-file-changes.ascii", format="ascii.no_header")
```

and the `TARGETID`s that actually changed in those files can be identified by rows that contain `VERSION=="2.7.0.dev5481"`.

Spooling through and looking for discrepant rows that have a "QSO-like" target state, e.g.:

```
tot = 0
diff = 0
for fn in fns:
    kremin = read_mtl_ledger("mtlkremin/trunk/mtl/main/dark/" + fn["col1"])
    archive = read_mtl_ledger("mtlarchive/trunk/mtl/main/dark/" + fn["col1"])
    ii = archive["VERSION"] == "2.7.0.dev5481"
    ii &= np.array(["QSO" in ts for ts in archive["TARGET_STATE"]])
    kremin = kremin[ii]
    archive = archive[ii]
    tot += len(archive)
    diff += np.sum(kremin["TARGET_STATE"] != archive["TARGET_STATE"])
print(diff, tot)
```
I find 175/28135 differences in the different sets of MTLs (~0.6%). These changes won't all strictly be Lyman-alpha decisions, so the real answer should be <0.6%. I'm not sure what the correct metric is to assess a "small" difference, but this seems "small" to me!

**Comment by schlafly** [comment]
I think it will be hard for people to get too excited about 175 targets.  Potentially affected targets are identifiable in the MTLs as having been updated between 6/2 and 6/17?  I just want to be able to tell folks what they would need to do if they wanted to look at these for differences.

**Comment by geordie666** [comment]
I think the most rigorous way to identify the targets of interest in the MTLs is because they have a `ZTILEID` corresponding to one of the tiles listed [above](https://github.com/desihub/desisurveyops/issues/200#issue-2358364625). It's possible to retrieve the subset of MTL ledgers that were touched via:

`svn diff -r 3859:3860 --summarize`

Some easy options for finding the exact _targets_ that were touched in the MTLs:

1. `svn diff -r 3859:3860`
2. Anything in an MTL ledger with a TIMESTAMP between: 
    - `2024-06-24T18:26:18+00:00` and `2024-06-24T18:27:20+00:00`  (bright) 
    - `2024-06-24T18:28:27+00:00` and `2024-06-24T18:30:26+00:00` (dark)
    - So in the five minutes before `2024-06-24T18:31`, basically.

**Comment by schlafly** [comment]
Thanks.  That's the right way to find the targets I asked about, but for posterity, these are the targets we corrected.  The targets that are still problematic are in commit 3840 (svn diff -r 3839:3860) and will have timestamps from June 11.  So if LSS wanted to apply weights or something to correct them, those would be the targets.

**Comment by geordie666** [comment]
@schlafly: I think we can close this issue?

**Comment by schlafly** [comment]
Thanks Adam, yes, closing.
