### ISSUE TITLE
Tile 3395 from 20240811 has low THRUFRAC values on P1/P2/P3

### ISSUE THREAD

**Issue by LNapolitano** [desihub/desisurveyops#204]
Tile 3395 is currently marked as unsure due to thrufrac alerts related to low exposure time as can clearly be seen on the attached QA sheet. 

Additional information shared on slack by Anand:
the two exposures are 247522-3, taken from 00:06 to 00:48:

247524	4951	SCIENCE	00:48	1266.3	DARK	0-9	ok	ok	ok	ok	ok	-	-
247523	3395	SCIENCE	00:28	1112.8	DARK	0-9	ok	ok	ok	ok	ok	-	-
247522	3395	SCIENCE	00:06	1208.8	DARK	0-9	ok	ok	ok	ok	ok	-	-

the nightlog mentions clouds:

00:06 [07:06] Exp. 247522- Good - First SPLIT of the tenth DARK tile 3395, correction move: 3.4 micron, Survey speed variable between 30% and 80% as fine clouds pass through, no issues with the data. (SO)
Tile 3395, Exptime: 1208.78, Airmass: 1.10, Sequence: DESI, Flavor: science, Program: DARK

00:28 [07:28] Exp. 247523- Good - Second SPLIT of the tenth DARK tile 3395, correction move: 3.4 micron, Survey speed up to 80% again, no issues with the data. (SO)
Tile 3395, Exptime: 1112.81, Airmass: 1.08, Sequence: _Split, Flavor: science, Program: DARK

the grafana plots for transparency + survey speed show a drop at that time (attached screenshot)if useful, here are the b/r/z thrufrac values for the two exposures:

>>> Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20240811/00247522/exposure-qa-00247522.fits", "PETALQA")
["PETAL_LOC", "BTHRUFRAC", "RTHRUFRAC", "ZTHRUFRAC"]
<Table length=10>

--------- ---------- --------- ----------
        PETAL_LOC BTHRUFRAC  RTHRUFRAC ZTHRUFRAC 
        int16    float32    float32   float32  
        0  0.9558431 0.9934089  0.9828018
        1 0.80612034 0.8655604  0.8398901
        2  0.7772591 0.8320261 0.80464345
        3  0.8329367 0.8896742 0.85450953
        4 0.96630466 0.9430628   0.940925
        5  1.0361375 1.0321798   1.084696
        6  1.1930491 1.1293575  1.1565788
        7  1.1751591 1.1102453   1.137546
        8  1.1619656 1.1303558  1.1441573
        9  1.0952247 1.0741291  1.0542518

>>> Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20240811/00247523/exposure-qa-00247523.fits", "PETALQA")["PETAL_LOC", "BTHRUFRAC", "RTHRUFRAC", "ZTHRUFRAC"]
<Table length=10>

--------- ---------- ---------- ----------
        PETAL_LOC BTHRUFRAC  RTHRUFRAC  ZTHRUFRAC 
        int16    float32    float32    float32  
        0  0.9230686 0.97155917 0.94972503
        1  0.7602825  0.8280579  0.8014233
        2  0.7920688  0.8376865  0.8208937
        3 0.89362687   0.931959 0.91757005
        4  1.0115296   0.974123  0.9868406
        5   1.057972  1.0534825  1.1160134
        6  1.1845658  1.1254636  1.1499221
        7  1.1724463  1.1165701  1.1357466
        8  1.1422725  1.1107304  1.1063292
        9  1.0621675  1.0503678  1.0155352

![20240812-Tile3395](https://github.com/user-attachments/assets/a78b384c-0daa-4079-bd48-c463229547f2)

![Screenshot 2024-08-12 at 10 09 20 AM](https://github.com/user-attachments/assets/b8c5656b-52e7-4417-8b11-94b2509f5278)

**Comment by schlafly** [comment]
Looks likely cloudy here to me.  https://data.desi.lbl.gov/desi/users/raichoor/main-status/spacewatch/spacewatch-20240811.mp4  .  Let's go ahead and call it bad; if there's 30% differential extinction there will be other issues.  @akremin , @abhi0395 , could we mark tileid 3395 on 20240811, expid 00247522, 00247523 as bad?  Thanks!

**Comment by schlafly** [comment]
Pinging this outstanding issue.

**Comment by geordie666** [comment]
@akremin: Could you please mark these exposures as bad?

**Comment by akremin** [comment]
I have marked exposures 00247522 and 00247523 on 20240811 as bad and purged all the data for tile 3395 on that night. It has not been observed since, so there was no reprocessing to do.

**Comment by geordie666** [comment]
I updated the `tiles-specstatus` file for tile `3395` and am closing out.
