### ISSUE TITLE
mark tile 20674 as bad

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#206]
BRIGHT tile 20674, expid 250085 (2024-08-24) has n_z/nz_ref < 0.9 and ZSKYCHI2PDF alerts on all petals. There are suggestions from @ashleyjross and @araichoor in [this slack thread](https://desisurvey.slack.com/archives/C01HNN87Y7J/p1724704469175409) to mark it as bad. It was apparently the final tile of the night. This ticket is a reminder to revisit this tile tomorrow.

**Comment by sybenzvi** [comment]
Tile 20674 is marked as bad and was committed.

**Comment by schlafly** [comment]
Looking at the "pending" tiles, I'm reopening this one.  desi_tile_vi gives us the ability to mark tiles as bad but we rarely want to do that; usually we want to mark these tiles as "unsure", and ask @akremin or @abhi0395 to mark the underlying exposures as bad.  Then we can reset QA to "none" once the EFFTIME is set to zero (i.e., the exposures have been marked bad and this information has propagated into tiles-daily).  If we just mark the tile as bad without doing anything to the underlying exposures it sits as "obsend" in the NTS (it has enough effective time) but will never get MTLed (it doesn't have QA = good), and it becomes a zombie.  

@akremin or @abhi0395 , would you mind marking exposure 250085 on tile 20674 as bad, and reprocessing this tile?  The only observation was on 20240824.  Then we'll clear QA.

**Comment by geordie666** [comment]
@kremin: Could you please mark this exposure marked as bad and rerun the tile?

**Comment by geordie666** [comment]
@akremin : Could you please mark this exposure marked as bad and rerun the tile?

**Comment by akremin** [comment]
That exposure has been marked as bad and the processing purged. I also ran tsnr and nightqa so that tiles-daily.csv now reflects 0s EFFTIME for this tile.

There are no other observations of this tile, so surveyops just needs to update the specstatus table to reflect the lack of EFFTIME and reset the QA.
