### ISSUE TITLE
check for OSTEP outliers

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#217]
Following up on an [issue raised on slack](https://desisurvey.slack.com/archives/C01HNN87Y7J/p1725985420426669) by @LNapolitano during survey ops: on 20240909, expid 252286 a hot region was spotted in r2 during the evening darks (see below).

The `OSTEP` keyword in the `preproc` headers is supposed to track the largest step change in overscan observed in the exposure. Check for this keyword and plot the distribution of OSTEP to see if this particular exposure is an outlier. Include all exposure types and potentially sort by types.

![20240909-r2dark](https://github.com/user-attachments/assets/9ede9e5d-18f1-4e3f-899a-f7210a74bb0d)

**Comment by schlafly** [comment]
FWIW, my understanding is that OSTEP is a property of the overscan and we expect it to not depend on type of exposure.  I'd hazard that the most useful dimensions are time & device (i.e., to answer questions like: "is it just r2" and "is it just recent").

**Comment by sybenzvi** [comment]
Closing this as a duplicate of [desispec#2366](https://github.com/desihub/desispec/issues/2366). Will post comments there.
