### ISSUE TITLE
update the logs messages for desimodel_sync

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#218]
The network reconfiguration of desi-16 has disabled the use of slack webhooks for automatic jobs, so notifications about the focalplane sync are not sent to `#survey-ops` as of today.

Get instructions from @elliotta on how to forward the logs by email and update the scripts in `~datasystems/desimodel_sync` to send email the logs to `desi-survey@desi.lbl.gov`.

**Comment by geordie666** [comment]
@sybenzvi: I think we can close this issue? We can reopen it later if the DB log syncs turn out to be too large.

**Comment by sybenzvi** [comment]
We can close this issue, which was addressed by [desimodel#177](https://github.com/desihub/desimodel/pull/177).
