### ISSUE TITLE
Petal 9, exp 254394, tile 23301 looks like bright star on stuck sky?

### ISSUE THREAD

**Issue by ashleyjross** [desihub/desisurveyops#219]
<img width="318" alt="Screenshot 2024-09-23 at 5 19 36 PM" src="https://github.com/user-attachments/assets/94af486d-acc9-4408-b520-7d69fa985604">

**Comment by ashleyjross** [comment]
We should mask the affected fibers somehow. Is masking the whole amp or even petal necessary?

**Comment by schlafly** [comment]
I think the right thing to do is to identify the affected pixels and to add them to this file
https://github.com/desihub/desispec/pull/2050
That would mean opening a preproc image and visually inspecting how much area is affected by the over-bright trace.

Someone also needs to figure out which trace was too bright and check if it's a stuck fiber or a real target.

**Comment by araichoor** [comment]
I think the culprit `TARGETID=2375903153750016`, a `BRIGHT_HPM` secondary target on `FIBER=4818`:
https://www.legacysurvey.org/viewer/?ra=24.7557&dec=-17.9507&catalog=tmpm90pr_h1&zoom=14
<img width="1374" alt="Screenshot 2024-09-25 at 12 28 45 PM" src="https://github.com/user-attachments/assets/c85e9378-21ed-403d-8ef1-f066db6969eb">

the green circle here is from the fiberassign file, ie with the infos from the `BRIGHT_PM` program:
```
    TARGETID     TARGET_RA TARGET_DEC   PMRA   PMDEC  REF_EPOCH
---------------- --------- ---------- ------- ------- ---------
2375903153750016   24.7557   -17.9507  3385.8   532.0    2000.0
```
the offset in RA since 2000 is about 0.02 deg.

from the `tractor-0247m180.fits` file, it has these mags: (g, r, z) = (13.7, 11.9, 8.7):
```
objid         ra                dec          flux_g    flux_r    flux_z  ref_cat        ref_id          pmra    pmdec   gaia_phot_g_mean_mag
             deg                deg        nanomaggy nanomaggy nanomaggy                              mas / yr mas / yr         mag         
----- ------------------ ----------------- --------- --------- --------- ------- ------------------- --------- -------- --------------------
 4257 24.771210452138845 -17.9477628246832 3208.1155 16876.986 324709.66      G2 5140693571158739712 3182.7341 592.1038            10.806108
```

@geordie666: didn t we already "cleaned" this `BRIGHT_PM` for super-bright objects?
I can have a quick look.

**Comment by geordie666** [comment]
Looking back at the [relevant issue](https://github.com/desihub/desisurveyops/issues/109) I think we only masked `FAINT_HPM` targets. Obviously that was an oversight. Let me spool through to find any `BRIGHT_HPM` targets and turn them off in the same manner I did for the `FAINT_HPM` targets.

**Comment by araichoor** [comment]
thanks!

btw, I notice that for this specific case, there actually are *two* very-close matches in the `tractor-0247m180.fits` file, with approx. the same proper-motion:
```
objid         ra                dec            pmra    pmdec   ref_epoch ref_cat        ref_id         flux_z 
             deg                deg          mas / yr mas / yr                                       nanomaggy
----- ------------------ ------------------ --------- -------- --------- ------- ------------------- ---------
 4248 24.771059358018583 -17.94837634531903 3385.8267 532.0398    2015.5      G2 5140693571158739840  5825.545
 4257 24.771210452138845  -17.9477628246832 3182.7341 592.1038    2015.5      G2 5140693571158739712 324709.66
```
they apparently are two different gaia `ref_id`, but could it be it s just the same source, detected twice in two images taken at two different epochs?
one of the match has a "more reasonable" z-mag of 13.1.

so I guess that a "matching" algorithm to identify those `HPM_BRIGHT` targets with high fluxes should consider something like the brightest mags of the few closest objects?

**Comment by geordie666** [comment]
Or even every object within 5" or so. Anyway, I'll look into it and turn this one (and any other relevant targets) off.

**Comment by araichoor** [comment]
@geordie666: for what is worth, I ve generated this two catalogs:
```
-rw-rw---- 1 raichoor desi 105K Sep 26 11:47 /global/cfs/cdirs/desi/users/raichoor/targets/BRIGHT_HPM-lsdr9-fluxmax-5arcsec.fits
-rw-rw---- 1 raichoor desi  18M Sep 26 11:48 /global/cfs/cdirs/desi/users/raichoor/targets/FAINT_HPM-lsdr9-fluxmax-5arcsec.fits
```
where I look in the tractor file (when available) at the brightest flux in grz within 5 arcsec (after having applied simple proper-motion correction to a same reference epoch -- 2024 -- for everything).
actually, maybe we d want to run that for 2025, 2026, ..., 2029? (I could do that easily).

here are the few objects I find with a brightest flux larger than 12 mag (arbitrary cut!):
```
d = Table.read("BRIGHT_HPM-lsdr9-fluxmax-5arcsec.fits")
d["TRACTOR_MAG_GRZ_MIN"] = 22.5 - 2.5 * np.log10(d["TRACTOR_FLUX_GRZ_MAX"])
sel = d["TRACTOR_MAG_GRZ_MIN"] < 12
d["TARGETID", "RA", "DEC", "TRACTOR_FLUX_GRZ_MAX", "TRACTOR_MAG_GRZ_MIN", "TRACTOR_OBJIDS"][sel]
# =>
    TARGETID        RA      DEC    TRACTOR_FLUX_GRZ_MAX TRACTOR_MAG_GRZ_MIN      TRACTOR_OBJIDS     
---------------- -------- -------- -------------------- ------------------- ------------------------
2375903153750016  24.7557 -17.9507         324709.65625   8.721261990217144 4248,4257,4621,4633,4636
2376846586937344 135.0981  21.8347      23039.310546875   11.59382630337465                3715,3737

d = Table.read("FAINT_HPM-lsdr9-fluxmax-5arcsec.fits")
d["TRACTOR_MAG_GRZ_MIN"] = 22.5 - 2.5 * np.log10(d["TRACTOR_FLUX_GRZ_MAX"])
sel = d["TRACTOR_MAG_GRZ_MIN"] < 12
d["TARGETID", "RA", "DEC", "TRACTOR_FLUX_GRZ_MAX", "TRACTOR_MAG_GRZ_MIN", "TRACTOR_OBJIDS"][sel]
# =>
     TARGETID             RA                 DEC         TRACTOR_FLUX_GRZ_MAX TRACTOR_MAG_GRZ_MIN TRACTOR_OBJIDS
----------------- ------------------ ------------------- -------------------- ------------------- --------------
39628435932319147 14.084735951824952  27.972419440213447     16158.0595703125  11.979026987694576      3499,3512
39627432759656859   41.3312169634514 -14.864961057159151       28076.24609375  11.379152398919146        411,437
 2252857029951489             46.827             -13.762       37235.87890625  11.072595976806825            857
 2253605423808512           198.0827             17.5179         277461.34375   8.891993786898196            507
 2253417447686145           199.1938              9.4242           1248962.25   7.258626720046355           4374
 2253915227684864           357.8913             31.4564       23248.46484375  11.584014298537221      3860,3871
```

maybe you ve already turned the `FAINT_HPM` ones off.
also, there are 84 `FAINT_HPM` row with nan's for (PMA,PMDEC); same, you ve surely already cleaned those!

**Comment by araichoor** [comment]
back to the original point of identifying in the preproc the region to be masked.

the effect is visible over all three cameras; I eye-balled that the max. region to mask:
- b-camera: 2540-2555;
- r-camera: 2560-2680;
- z-camera: 2510-2610.

this plot shows the profile along the fiber direction (note the log scale in the y-axis):
- solid thick: mean over all pixels along the wavelength direction;
- solid (dashed) thin: value at y=4000 (3000), to control what s happening on the reddest wavelengths part, as this star is brighter in the red

![preproc-00254394-9](https://github.com/user-attachments/assets/8b24b405-8a60-4baf-8148-203b3ec8df18)

@schlafly: makes sense?

**Comment by schlafly** [comment]
Yes, that looks good.  Practically I think that means that the larger z band mask will apply to all of the fibers, right, so that that whole region won't end up getting put in the MTLs?  I ask because the redshifts are clearly bad over the larger region, affecting more than one or two fibers.

**Comment by araichoor** [comment]
right.

as the mask is defined per-camera, I was trying to get the minimal masking for each camera, to save few b- and r-camera spectra.
as you say, I expect that, for MTLs, any spectra with a missing camera would be rejected, ie it would be the unions of fibers affected by the three per-camera masks -- so dominated by the z-camera masking here.
it would be good to double-check that, though, once the reprocessing is done.

for sure, at the redshift levels, a fairly broad large range of fiber are affected: I d say at least 4790 -- 4849:
![tmp](https://github.com/user-attachments/assets/a2aac333-538d-4e4e-bec8-b37491f515d3)

if anyone wants to have a look, the spectra for fibers 4750-4999 are displayed here: https://data.desi.lbl.gov/desi/users/raichoor/spectro/daily/data-check/cframe-00254394-9.pdf.

for reference, if I m correct, the mtl-specific zwarn flags are here:
https://github.com/desihub/desispec/blob/4eae355fbae93e5a138c6ca91074d961c2558286/py/desispec/zmtl.py#L266-L274
and `bad_qafstatus_mask` here:
https://github.com/desihub/desispec/blob/4eae355fbae93e5a138c6ca91074d961c2558286/py/desispec/data/qa/qa-params.yaml#L40

**Comment by araichoor** [comment]
re-thanks for your input!
you re 100% right :) sorry for this misleading first report... I m not familiar with the preproc files..

second try, much more conservative:
- b-camera: 2405 -- 2596 (~25 fibers);
- r-camera:  2235 -- 3004 (~100 fibers);
- z-camera: 1834 -- 3371  (~200 fibers).

looking a bit more carefully at that: indeed, the wings are quite extended, but I m not really sure how to catch those...
the plots below show the preproc with saturating the colorbar, where we can see that the wings do extend pretty wide.
I picked the above values with looking at the regions between the fiber blocks (25 fibers); I thought that those regions should be kind of stable with no signal; the bottom panel shows the median values for those regions (both over all wavelengths, and over a narrower range on the red side); I just eye-balled where those seem to be not affected..
(higher-resolution plots here: https://data.desi.lbl.gov/desi/users/raichoor/spectro/daily/data-check/)

for the z-camera:
![preproc-00254394-z9-lowres](https://github.com/user-attachments/assets/27864be7-1cc7-421b-98d1-267145cee3a5)

for the r-camera:
![preproc-00254394-r9-lowres](https://github.com/user-attachments/assets/aeade518-cb64-4222-b20e-27bfe6d0b58e)

for the b-camera:
![preproc-00254394-b9-lowres](https://github.com/user-attachments/assets/4b70ffc9-9df9-4c57-a935-83c6c711b0ec)

**Comment by geordie666** [comment]
Conflating investigations a bit. Sorry! But, I'm checking into the potentially problematic targets that Anand uncovered. I did, indeed, already turn off these `TARGETID`s (`FAINT_HPM`):

```
2252857029951489
2253605423808512
2253417447686145
```

But not the other `HPM` targets Anand identified. I'm still checking into why the others fell through the cracks.

**Comment by geordie666** [comment]
Interestingly, `39627432759656859` is an `MWS_NEARBY` target (as well as being a `FAINT_HPM` target) that we've apparently successfully observed on `TILEID=23829`.

**Comment by araichoor** [comment]
thanks for the follow-up!

for info, I ve "extended" my check with looking at the positions at 2025.0, 2026.0, ..., 2029.0.
it provides the same results, except one extra target pops up in the `FAINT_HPM` catalog:
```
     TARGETID             RA                 DEC         TRACTOR1_OBJIDS TRACTOR1_MAG_GRZ_MIN
----------------- ------------------ ------------------- --------------- --------------------
 2253043265437696   153.321883637085   -6.02558558716321            4616   11.696013328445938
```
(for the position at 2024.0, there are no objects closer to 5 arcsec).
sorry to add more to your plate!

also, about the 12 mag cut and 5 arcsec cut: I admit I just picked those values ~arbitrarily; at the same time, as there only are a handful of targets to exclude, I guess it s ok to be on the safe side.

**Comment by geordie666** [comment]
@araichoor: This is such a small number of objects that I agree that I should just "turn them off" to be safe. I'll do that later today or tomorrow.

I'll probably keep digging for other corner cases (and to try to determine why `desitarget` isn't finding those cases) but I think turning off the targets you've found so far makes sense.

**Comment by araichoor** [comment]
thanks @geordie666!

about implementing the masking (pinging @sbailey):
I think I ve the edited version of https://desi.lbl.gov/trac/browser/calib/desi_spectro_calib/trunk/ccd/ccd-region-mask.csv ready to commit.
I ll proceed to the commit tomorrow, during daytime, to avoid any interference with the on-going processing.

my edited file is here:
```
cat /global/cfs/cdirs/desi/users/raichoor/svn/desi_spectro_calib/trunk/ccd/ccd-region-mask.csv 
NIGHT,EXPID,CAMERA,XMIN,XMAX,YMIN,YMAX,COMMENT
20230512,180299,b6,2048,3923,2998,3006,'large tail in serial line from cosmic ray see https://github.com/desihub/desisurveyops/issues/117'
20231208,208688,b6,2048,4096,3928,3932,'tail from cosmic impacts overscan OSTEP; see https://github.com/desihub/desisurveyops/issues/164'
20240921,254394,b9,2405,2596,0,4095,'contamination from bright star; see https://github.com/desihub/desisurveyops/issues/219'
20240921,254394,r9,2235,3004,0,4127,'contamination from bright star; see https://github.com/desihub/desisurveyops/issues/219'
20240921,254394,z9,1834,3371,0,4127,'contamination from bright star; see https://github.com/desihub/desisurveyops/issues/219'
```

I plan to just do:
```
svn commit ccd-region-mask.csv -m "bad fibers for 20240921,254394,brz9"
```

as a sanity chek, I ve generated preproc files with that file, here s what it looks like, with the masking regions shaded in grey:

![newpreproc-00254394-9-dpi250](https://github.com/user-attachments/assets/a2b033ef-f618-4e47-90e3-a89065f2c48d)

**Comment by araichoor** [comment]
for info, I just committed this `ccd-region-mask.csv` file: https://desi.lbl.gov/trac/changeset/1206/calib.

if I m correct, we should now just need to reprocess the EXPID=254394 and the TILEID=23301, right? (of course with an svn-updated version of `$DESI_SPECTRO_CALIB`)

**Comment by schlafly** [comment]
@abhi0395 , @akremin , can we reprocess expid 254394 (tileid 23301)?

**Comment by geordie666** [comment]
I've "turned off" (added the `IN_BRIGHT_OBJECT` flag) for the additional potentially problematic targets Anand identified. A full census of the 9 `HPM` targets Anand mentions above:

**These two targets have already been successfully observed, so I haven't changed their state:**
2376846586937344 `BRIGHT_HPM`
39627432759656859 `FAINT_HPM`

**I'd already turned off these three targets:**
2252857029951489 `FAINT_HPM`
2253605423808512 `FAINT_HPM`
2253417447686145 `FAINT_HPM`

**I've now additionally turned off these four targets:**
2375903153750016 `BRIGHT_HPM`
39628435932319147 `FAINT_HPM`
2253915227684864 `FAINT_HPM`
2253043265437696 `FAINT_HPM`

**Comment by akremin** [comment]
I've rerun the processing for the tile. There was only the one exposure on the one night. I've rerun tsnr and nightqa. Back to surveyops for QA.

**Comment by sybenzvi** [comment]
@araichoor, could you please double-check this ticket for tile 23301 before we confirm the tile is OK? The new [tile 23301 QA was finished 2024-10-14 and is here](https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/23301/20240921/tile-qa-23301-thru20240921.png). There are a number of fibers in petal 9 with low EFFTIME and nonzero QAFIBERSTATUS. These are near but not on top of the bright star that was identified as the problem, as far as I can tell.

**Comment by araichoor** [comment]
looks good to me, as far as I can say:

- in `tile-qa-23301-thru20240921.fits`, the `EFFTIME_SPEC` vs. fiber distribution looks like it accounts for the missing z, or z+r, or z+r+b cameras; the `FIBER` range is 4725, 4924;
- in `zmtl-9-23301-thru20240921.fits`, the related fibers have the `BAD_SPECQA` flag turned on.

here s a plot:
<img width="1117" alt="Screenshot 2024-10-21 at 12 02 10 PM" src="https://github.com/user-attachments/assets/d7796b91-40a7-428b-897e-716a2315b08b">


looking at the `zmtl` file (and picking the `FIBER` range from the above plot):
```
from desitarget.targetmask import zwarn_mask
fn = "/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/23301/20240921/zmtl-9-23301-thru20240921.fits"
d = Table(fitsio.read(fn, "ZMTL"))
d["FIBER"] = 4500 + np.arange(len(d), dtype=int)
sel = (d["FIBER"] >= 4725) & (d["FIBER"] <= 4924)
d = d[sel]
assert np.all((d["ZWARN"] & zwarn_mask["BAD_SPECQA"]) > 0)
```

remarks:
- as we re masking a block of fibers, the (ra, dec) distribution in not close to the bright star, as expected;
- if I m correct, in `tile-qa-23301-thru20240921.fits`, there s no flag in `QAFIBERSTATUS` to say that some of those spectra have missing cameras; it is only reflected indirectly in the `EFFTIME_SPEC`; but as long as the `zmtl` file has the correct `BAD_SPECQA` info, I think we re good; if I m correct, it s the `LOWEFFTIME` flag that turns on the `BAD_SPECQA`; dumping here the `fibermask` names for that block of fibers:

```
from desispec.maskbits import fibermask
fn = "/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/23301/20240921/tile-qa-23301-thru20240921.fits"
d = Table(fitsio.read(fn, "FIBERQA"))
sel = (d["FIBER"] >= 4725) & (d["FIBER"] <= 4924)
d = d[sel]
for val, count in zip(*np.unique(d["QAFIBERSTATUS"], return_counts=True)):
    print("{}\t{}".format(count, "|".join(fibermask.names(val))))

=>

184	LOWEFFTIME
2	STUCKPOSITIONER|LOWEFFTIME
3	UNASSIGNED|STUCKPOSITIONER|LOWEFFTIME
2	POORPOSITION|LOWEFFTIME
4	STUCKPOSITIONER|POORPOSITION|LOWEFFTIME
1	UNASSIGNED|STUCKPOSITIONER|POORPOSITION|LOWEFFTIME
3	BADPOSITION|POORPOSITION|LOWEFFTIME
1	VARIABLETHRU|LOWEFFTIME
```

**Comment by sybenzvi** [comment]
Thanks for the detailed look. I think we can mark as good and close this.

**Comment by araichoor** [comment]
I ve just updated the `tiles-specstatus.ecsv` file, with setting that tile to "good": https://desi.lbl.gov/trac/changeset/4223/data

closing the ticket.
