### ISSUE TITLE
Tile 25270 on 20220206 has petal 7 rejected for low throughput

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#22]
Tile 25270 on 20220206 has petal 7 rejected for low throughput with no obvious reason why.
<img width="1161" alt="Screen Shot 2022-02-07 at 1 02 04 PM" src="https://user-images.githubusercontent.com/7918018/152871685-cf4d97d0-dc03-4c4c-b35f-d29206da12ba.png">

**Comment by schlafly** [comment]
These alerts are surprising but usually when petals are thrown out we see that in the EFFTIME plot---I would not have expected the petals to be thrown out in this case.

**Comment by araichoor** [comment]
Only the b-camera has this low thrufrac:
```
>>> d = Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/23225/20220206/tile-qa-23225-thru20220206.fits","PETALQA")
>>> d["PETAL_LOC", "NSTDSTAR", "BTHRUFRAC", "RTHRUFRAC", "ZTHRUFRAC"][8]
<Row index=8>
PETAL_LOC NSTDSTAR BTHRUFRAC  RTHRUFRAC  ZTHRUFRAC
  int16   float32   float32    float32    float32 
--------- -------- ---------- ---------- ---------
        8     23.0 0.74304354 0.99059546 0.9895618
```
As the TSNR2_LRG (or TSNR2_ELG?) is used, maybe it explains why the EFFTIME is "blind" to that?

For what is worth, I notice that this tile and the one in issue https://github.com/desihub/desisurveyops/issues/21 both have exposures from two nights; but in both case, it seems that the exposure from 202202026 is the one with issue.

**Comment by julienguy** [comment]
Fixed in https://github.com/desihub/desispec/pull/1667

**Comment by akremin** [comment]
I removed and reprocessed files for tile 25270 on both night 20220203 and 20220206.

Back to Eddie for QA/specstatus
