### ISSUE TITLE
Bad darks on 20240918, 20240919, 20240920

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#220]
There are several peculiar darks on 20240918-20240920.  This is doubtless related to power cycling those CCDs as part of replacing the collimators, but the darks look exceptionally bad---more than I remember being typical for VCCD cycling issues.

20240918 - r2 is a mess.  Note this device came back with new extremely hot pixels leading to bad columns, so this is perhaps not a surprise, but the dark more broadly also says that something bad happened to this device.   1 bright + some backup.
20240919 - r2 still recovering, r6 bad.  8 bright + some backup.
20240920 - r3 dark is bad.  3 bright + some backup.

These darks evolve from the evening to morning darks and so are instability-like problems we can't solve with a different dark; I don't think it's beneficial to try reprocessing with a different dark.  We should decide if we want to mark data bad on these nights.

I would ordinarily recommend throwing out r2 on 20240918 and r6 on 20240919 since they look really bad.  In all cases the sky redshifts and tileqa look fine to me, though; the bright targets are really helping.  But there will clearly be a lot of bad signal on those petals on those nights, and you can see it in the sky fibers on science exposures.  On 20240920, the signal in the darks is ~10x lower and it's harder to pick out of the sky sframes so my inclination would be to ignore it.

I will mark all of these nights as unsure pending the resolution of this issue.

20240918: 
![image](https://github.com/user-attachments/assets/c06c9ee3-d861-40fa-8134-1f9744125f6b)
20240919: 
![image](https://github.com/user-attachments/assets/359ea2fa-2724-4158-a33b-04321760e2a2)
![image](https://github.com/user-attachments/assets/e6847db2-c312-49b9-aa53-845376dbed8a)
20240920: 
![image](https://github.com/user-attachments/assets/3e483a7c-7d39-42fd-b888-090994e5b69e)

**Comment by schlafly** [comment]
Let's go ahead and mark r2 bad on the 18th and r6 bad on the 19th, and ignore the 20th.  Then reprocess and we'll reQA.

**Comment by abhi0395** [comment]
@schlafly 
re-processing of 20240918 and 20240919 is complete; nightqa updated. Please feel free to close the ticket.

**Comment by araichoor** [comment]
I ve not carefully followed this ticket, but one remark:
I see that some tiles (listed below), observed on 20240918-19, have been observed on later nights.
I guess we d want to also re-process those (note that I consider here all exposures from 20240918-19; maybe we could exclude the (backup) ones which have `EFFTIME_SPEC=0`, as they shouldn t affect the later reduction; but, in doubt, it doesn t hurt to rerun few extra backup tiles).

```
e = Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures-daily.csv")
sel = (e["NIGHT"] == 20240918) | (e["NIGHT"] == 20240919)
tileids = np.unique(e["TILEID"][sel])
sel = (e["NIGHT"] >= 20240920) & (np.in1d(e["TILEID"], tileids))
e[sel]["NIGHT","EXPID","TILEID","EFFTIME_SPEC"]
```
returns:
```
 NIGHT   EXPID  TILEID EFFTIME_SPEC
-------- ------ ------ ------------
20240920 254153  27092        184.3
20240920 254154  27094         85.0
20240920 254155  27093        231.3
20240920 254157  42050         52.9
20240920 254158  41325         31.4
20240920 254159  41323         37.1
20240920 254160  41302         44.8
20240921 254373  40610         26.7
20240922 254582  40610         36.0
```

and on the safe side: those three bright tiles have `QA="unsure"`, so they should not be a problem for a mtl update.
```
t = Table.read("/global/cfs/cdirs/desi/survey/ops/surveyops/trunk/ops/tiles-specstatus.ecsv")
t[np.in1d(t["TILEID"], [27092, 27093, 27094])]["TILEID", "EFFTIME_SPEC", "LASTNIGHT", "QA", "USER", "QANIGHT"]
```
returns:
```
TILEID EFFTIME_SPEC LASTNIGHT   QA     USER   QANIGHT 
------ ------------ --------- ------ -------- --------
 27092        293.5  20240920 unsure schlafly 20240920
 27093        305.5  20240920 unsure schlafly 20240920
 27094        261.9  20240920 unsure schlafly 20240920
```

**Comment by abhi0395** [comment]
Thanks @araichoor. I missed this part. I have now re-processed all these tiles and updated the tsnr and nightqafor these nights as well.

**Comment by araichoor** [comment]
thanks @abhi0395!

**Comment by schlafly** [comment]
@SGontcho , can you reQA these?  Thanks!

**Comment by geordie666** [comment]
I've re-marked 6 of the outstanding tiles correctly as `good` or `none`:

`27092, 27093, 27094`: `good`
`27435, 27438, 27802`: `none`

and committed the tiles-specstatus file. So, we're only waiting on `26377` before we can close out this ticket.

**Comment by akremin** [comment]
Luckily it was just a job timeout issue. I was able to push tile 26377 across the finish line. I've also rerun tsnr and nightqa.

**Comment by sybenzvi** [comment]
Confirming that the final tile affected by bad darks (26377 on 20240919 with bad r6) has r6 purged and successful QA. Closing the issue.
