### ISSUE TITLE
Tile 6643 on 20241005 abnormal number of QAFiberStatus >0 on Petal 2

### ISSUE THREAD

**Issue by SGontcho** [desihub/desisurveyops#225]
Abnormal number of non-zero redshifts from QAFiberStatus >0 on Petal 2.
Tile QA status at the moment: unsure. 

<img width="416" alt="Screenshot 2024-10-06 at 10 20 53" src="https://github.com/user-attachments/assets/fd3d6dc1-6be1-45d6-a2de-50b08ab4ecfb">

**Comment by sybenzvi** [comment]
Discussion in 2024-10-07: this tile (exp 256450) followed a long slew out of the SGC from dec=-15 to dec=+51. The telescope may not have been in focus, as indicated by half the focal plane having a higher throughput than the other. The SO also noted in the log that the guide stars were elongated for this exposure, symptomatic of a focus issue.

We may have several tiles like this following long slews that do not recover focus.

**Comment by geordie666** [comment]
I'm going to close this and consolidate this similar issues with the one in Dustin's longer thread.
