### ISSUE TITLE
NIGHT/EXPID/TILEID = 20241014/257978-80/27338 : stuck fiber on bright star

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#233]
tileid=27338 has the stuck`FIBER=1604` (`LOCATION=3398`) on a mag~6 star:
<img width="1378" alt="Screenshot 2024-10-15 at 11 46 39 AM" src="https://github.com/user-attachments/assets/4cc80391-0794-46c5-9dc5-23327f105983">

this is the star ("high-proper motion", don t know if that matters): https://simbad.cds.unistra.fr/simbad/sim-id?Ident=TYC++1218+1667+1&NbIdent=1

that messes up the `PETAL_LOC=3` redshifts:
<img width="1201" alt="Screenshot 2024-10-15 at 11 36 21 AM" src="https://github.com/user-attachments/assets/dbf698c2-5b2d-417a-a2b5-7cf800a352f8">

I think it s just bad luck, as this positioner has been moved this summer..

the observers did flag those exposures as "bad":
```
22:09 [05:09] Exp. 257978- Bad - Split 1 of tile 27338, transparency 95%, seeing 1.2 arcsec, survey speed 15%, positioner RMS final move is borderline (5.05), guiding is ok. One warning for high amp read noise in Z. Group of fibres with high flux (1603-1606) which show step changes in flux in uncalibrated spectra. 1604 is very bright object. CCD images for camera 3 show this might be affecting more fibres, especially in B. (SO)
Tile 27338, Exptime: 1304.60, Airmass: 1.37, Sequence: DESI, Flavor: science, Program: BRIGHT

22:33 [05:33] Exp. 257979- Bad - Split 2 of tile 27338, transparency 95%, seeing 1.2 arcsec, survey speed 15%. Same issues as exposure 257978. (SO)
Tile 27338, Exptime: 1013.82, Airmass: 1.27, Sequence: _Split, Flavor: science, Program: BRIGHT

22:52 [05:52] Exp. 257980- Bad - Split 3 of tile 27338, transparency 95%, seeing 1.2 arcsec, survey speed 20%. Same issues as exposure 257978. (SO)
Tile 27338, Exptime: 912.30, Airmass: 1.21, Sequence: _Split, Flavor: science, Program: BRIGHT
```

the spectro. pipeline still processed those.
here s a zoom on the Z vs. FIBER plot; should we just declare e.g. `FIBERS=1500-1749` as bad? or do we want to define a finer mask?

![tmp](https://github.com/user-attachments/assets/e9a02d7d-56f4-43eb-825c-a76c04215701)

**Comment by geordie666** [comment]
@abhi0395, @akremin: Can we mark all of Petal 3 as bad for exposures `257978`, `257979` and `257980` and re-process tile `27338`. Thanks!

**Comment by akremin** [comment]
I've marked petal 3 as bad for all three exposures, purged, rerun, and updated tsnr and nightqa. Back to surveyops for QA.

**Comment by sybenzvi** [comment]
@araichoor, I looked at the tile and confirmed that petal 3 is now removed, so I marked tile 27338 as good.

**Comment by araichoor** [comment]
thanks! (you ve been ahead of me, I was planning to do that today.)
