### ISSUE TITLE
NIGHT/EXPID/TILEID = 20241015/258118-19/23041 : SKYCHI2PDF alerts and weird sframe

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#235]
this tileid=23041 got two exposures (258118-19) on 20241015.
the qa has lots of `{R,Z}SKYCHI2PDF` alerts:
<img width="1375" alt="Screenshot 2024-10-19 at 2 52 58 PM" src="https://github.com/user-attachments/assets/8b9e838b-ee9d-4ae4-a5ea-1e3114d21f68">

we usually ignore those if the data look fine.
the redshifts look ok to me, but I notice that the sframe for 258118 looks quite different than the one from 258119, even though they have similar exptimes and efftimes:
```
 NIGHT   EXPID  TILEID EXPTIME EFFTIME_SPEC
-------- ------ ------ ------- ------------
20241015 258118  23041  1516.7        169.0
20241015 258119  23041  1264.4        176.5
```

<img width="737" alt="Screenshot 2024-10-19 at 2 54 43 PM" src="https://github.com/user-attachments/assets/bc66cdb9-3c90-4029-8dac-ebbe3d975bda">

<img width="735" alt="Screenshot 2024-10-19 at 2 54 56 PM" src="https://github.com/user-attachments/assets/fa476c63-ee75-40d2-9686-81b6f6eb2a59">

so I have marked this tile as "unsure" for now, until I can get feedback from people after the weekend.

ps: the spacewatch movie does not show anything particular for 258118 (https://data.desi.lbl.gov/desi/users/raichoor/main-status/spacewatch/spacewatch-20241015.mp4).

**Comment by schlafly** [comment]
I agree with Anand that 258118 looks much worse than 258119 for no discernible reason.  It doesn't seem to affect redshifts but we usually react to SKYCHI2PDF issues and it looks bad.  So I would mark 258118 on night 20241015, tileid 23041 as bad and reprocess without that data, but keep 258119 which looks to have much smaller SKYCHI2PDF.

The one other thing I would remark is that the sky was very bright then.
https://telemetry.desi.lbl.gov/d/4Ut9C-3Zz/etc-telemetry?orgId=2&from=1729040599428&to=1729084666782
![image](https://github.com/user-attachments/assets/034c6197-faa3-4b21-ad6d-b2423740308b)
It's interesting that the sky ranged from 30 to 20 during that exposure; presuming the moon separation changed slightly but it's hard to imagine that that's important enough.

Note that both of these have EFFTIME_SPEC ~ 180 s so this tile will still be complete even after removing 258118.

**Comment by geordie666** [comment]
@akremin: Can we please mark exposure number `258118` on night `20241015`, tileid `23041` as bad and reprocess?

**Comment by akremin** [comment]
258118 has been marked as bad and tileid 23041 has been rerun with just exposure 258119 on night 20241015. Tsnr and nightqa have been updated.

**Comment by geordie666** [comment]
@forero: I set the QA for the tile mentioned here (`23041`) back to none. This tile will now reappear in regular tile QA again. Can you please mark this tile as good when you run QA tomorrow, if it looks good and if you beat me to it?

Once you've done that, you can close this issue, thanks!

**Comment by forero** [comment]
Done!
