### ISSUE TITLE
unexplained SVN slowdowns during AP

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#236]
Coincident with the engineering work starting on 2024-10-15 and the lengthy perlmutter outage starting 2024-10-16, Anand has reported slow/unresponsive `svn up` and `svn commit` several times when running AP. Yesterday (2024-10-20) `svn commit` timed out at 4 pm MT, but then worked without obvious slowdowns at 6 pm MT ([discussion on Slack here](https://desisurvey.slack.com/archives/C01HNN87Y7J/p1729446917324359)).

Let's keep an eye on this and report if the slowdowns and timeouts recur this week.

**Comment by geordie666** [comment]
`svn` seems to be behaving well in the last week. We also have the related issue #242. So, I'm closing this issue.
