### ISSUE TITLE
check status of r2 readnoise since FEE swap on 2024-10-16

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#237]
@julienguy has confirmed in Nightwatch that the FEE swap on r2 last week has cleaned up the readnoise. During QA this week, let's do a cursory check that the readnoise has improved since 2024-10-26.

**Comment by geordie666** [comment]
Read noise looked OK last week (at least nothing was unusual in tile QA). Can we close this issue @sybenzvi?

**Comment by sybenzvi** [comment]
Yes, you can see the change in the overscan bias and corresponding reduction in readnoise for all amps in r2 in the [history plots](https://nightwatch.desi.lbl.gov/historyqa/history-ccd-r2.html), so we can safely close this out.
![Screenshot 2024-10-29 at 9 59 12 AM](https://github.com/user-attachments/assets/e733e5b5-05f3-4ae8-bd2c-905e827755b5)
