### ISSUE TITLE
Dark tiles 4014 and 11707 observed close to Moon on 20241020

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#239]
on 20241020, two dark tiles were observed clos-ish to the Moon:
- tileid=4014:  expids=258979-258982, Moon distance: 56.7 deg;
- tileid=11707: expids=258984-258986, Moon distance: 49.2 deg.

they got 3-4 exposures, which all were >0.4 survey speed, and overall high efftime_spec.
but their lrg success rate is lower than nominal.

here s the per-petal lrg success rate nightqa plot:
<img width="296" alt="Screenshot 2024-10-21 at 10 53 05 AM" src="https://github.com/user-attachments/assets/4c5e7a87-feaa-4036-96b0-89bfc7cd0397">

here s the sky map, with the grey shaded area showing 50 deg from the Moon:
![skyseq-20241020](https://github.com/user-attachments/assets/7fe684db-b47f-4e38-94c6-aa0eafc0f7ae)

and here are some stats for the five dark tiles observed that night, where one can see that tileids=4014 and 11707 are the dubious ones:
```
# TILEID NEXP EFFTIME_SPEC NGOOD_LRG/NLRG=GOOD_FRAC
8084	1    1103  637/649=0.98
6226	3    1295  330/339=0.97
5841	3    1421  309/315=0.98
4014	4    1506  635/665=0.95 # <- in des region, at dec~-17
11707	3    1314  823/905=0.91 # <- north of the ngc region
```

I guess we d want to mark those exposures as "bad" and reprocess?

for reference, slack threads:
- about the nts picking dark tiles issue: https://desisurvey.slack.com/archives/C01HNN87Y7J/p1729515239789439
- about those two dark tiles: https://desisurvey.slack.com/archives/C01HNN87Y7J/p1729534777365939

**Comment by sybenzvi** [comment]
I agree that 4104 and 11707 should be marked bad; these were mistaken observations and the redshift distribution looks off.

**Comment by geordie666** [comment]
@abrodze: Could you please mark exposures contributing to tiles `4014` and `11707` from the night of `20241020` as bad due to closeness to the moon and reprocess? Let me know here when that's done. And certainly please don't feel you have to do this over the weekend!

**Comment by abrodze** [comment]
tiles 4014 and 11707 from the night of 20241020 are now marked as bad. nightqa pages have been regenerated.

**Comment by geordie666** [comment]
Thanks, @abrodze. I've zeroed out the `EFFTIME` and reset the tile QA for `4014` and `11707` on the surveyops side. So I'm closing this out.
