### ISSUE TITLE
Tile 22230 on 20220211 rejects half of R4 due to CTE in overscan

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#24]
The single exposure on tile 22230 on 2022-02-11 (expid 122156) rejects half of P4 (fibers 2250-2499) due to a small CTE from a cosmic effecting the overscan region, resulting in a too-large overscan jump (OSTEPB=6.07).

This has previously been seen in r8-D, z8-D, z3-D, z5-A, as described in the desispec issue #1619 (https://github.com/desihub/desispec/issues/1619).  However, it had not been identified previously on r4-B.

Below is the raw image centered on the bright cosmic at location (2219,1036).
<img width="409" alt="Screen Shot 2022-02-12 at 11 04 37 AM" src="https://user-images.githubusercontent.com/7918018/153724755-d0e625cb-dc4f-4e90-b22e-f87fdda12923.png">

**Comment by schlafly** [comment]
I've been marking these as good; they don't mess with LyA decisions (particularly on a bright tile!), and are only 5% of an exposure.  We also don't have a software fix in immediate sight.  My inclination would be to mark the tile as good and add the TILEID to desispec/1619, and then close this ticket.

**Comment by schlafly** [comment]
Adding this to the existing ticket about this problem re tileid 9497, marking this tile as good, and closing.
