### ISSUE TITLE
High-redshift sky fibers in petal=3 and 7 for 20241020

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#240]
more or less all bright / dark tiles from 20241020 have high-redshift sky fibers in petal=3 and 7.
I ll investigate more, but in the meantime I ve marked all the tiles as "unsure" in the qa.
(note: those two dark tiles are independently marked as "unsure": https://github.com/desihub/desisurveyops/issues/239)

for instance here for tileid=23680:

<img width="308" alt="Screenshot 2024-10-21 at 3 04 47 PM" src="https://github.com/user-attachments/assets/4a91cebb-c150-45aa-ad31-8750b2ae6dcc">

if useful, I ve plotted all the sky fibers from petal=3 and petal=7 for that tileid=23680:
https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/tmp-daily-23680-thru20241020-sky-petal3.pdf
https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/tmp-daily-23680-thru20241020-sky-petal7.pdf

I attach here two typical examples:
- fiber=1949 (petal=3): offset for the whole z3 camera; it s read in 2-amp mode, so it s ampB, which has a (corrected) cte issue => maybe we d need to change to the “stronger” (regnault) correction?
<img width="1370" alt="tmp-23680-fiber1949" src="https://github.com/user-attachments/assets/6076f514-28ec-4dfb-95a5-17d5e13cfcc6">

- fiber 3921: looks like it s the red part of the z-camera which has issue, and for the 3750-4000 fibers part; ie I d say it s ampD in z7…
<img width="1372" alt="tmp-23680-fiber3921" src="https://github.com/user-attachments/assets/dbcc2c33-0bbf-426b-9848-269a9d5df5ee">

**Comment by geordie666** [comment]
@djschlegel: I think you ended up passing all of these tiles as good? If so, can we close this issue?

**Comment by geordie666** [comment]
I confirmed that these tiles were passed as good by David S. and so I'm closing this issue.
