### ISSUE TITLE
wget from `data.desi.lbl.gov` to KPNO is timing out in NTS and afternoon planning

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#242]
A call to `wget` during afternoon planning has been timing out since 20241023. The following two files, synced from NERSC to KPNO, are affected:
- `$CFS/desi/spectro/redux/daily/tsnr-exposures.fits`
- `$CFS/desi/spectro/redux/daily/tiles.csv`

A workaround has been to copy the files by hand to desi-8; see @djschlegel's updates to the [wiki instructions here](https://desi.lbl.gov/trac/wiki/SurveyOps/DailyOps#AfternoonPlanning), and Slack threads at [#survey-ops](https://desisurvey.slack.com/archives/C01HNN87Y7J/p1729700147266809) and [#on-mountain_status](https://desisurvey.slack.com/archives/C0104P6RG8J/p1729715254280199).

I confirm that I can download the files without issue from my laptop but not from `desi-16`.

**Comment by sbailey** [comment]
It sounds like the problem is on the KPNO side, to be debugged by @elliotta @daqiii and Eli Vinal, but I'll ping @weaverba137 to keep him in the loop too.

**Comment by weaverba137** [comment]
Noted, thanx @sbailey.

**Comment by sybenzvi** [comment]
Eli and Ann updated access to data.desi.lbl.gov from the DESI workstations. They reported some problems with an untrusted certificate during their tests but I successfully ran `wget` without any problems as both `datasystems@desi-8` and `planner@desi-8` ([details in a long slack thread](https://desisurvey.slack.com/archives/C0104P6RG8J/p1729719937783279)).

If wget works properly during AP today, I will close this ticket and update the relevant instructions on the wiki.

**Comment by sybenzvi** [comment]
I confirm that afternoon planning is no longer affected by `wget` timeouts on `desi-8`.
