### ISSUE TITLE
Tile 6663 has no standards on petal 5

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#244]
The main-survey dark tile 6663 observed on exp 260725 on 2024-11-01 has no standard stars on petal 5, and therefore no reductions on that petal.  There are indeed no standard stars in the fiberassign file for petal 5.  This is surprising, as the location is squarely inside the DR9 footprint and the imaging looks fine.  The other petals have 5 to 10 standards. I've marked this tile as unsure.

**Comment by araichoor** [comment]
for what is worth, we already faced that, and we actually knew this was going to happen for this tile :)
see this comment - and the whole thread: https://github.com/desihub/desisurveyops/issues/82#issuecomment-1347655891.

the reason for the lack of standard stars is that it s a super-dusty region.

from a quick re-read of the thread:
- we expect that to happen for ~30 petals for main{bright, dark}, all in the same area of this corner of the ngc;
-  I am not sure we then converged on a solution for those cases; looks like we passed the tiles as "good", dropping the petal with no standard star;
- @schlafly suggests a method to solve that in desispec, but it was never implemented, as far as I know; I guess we just forgot about that...

**Comment by schlafly** [comment]
Thanks Anand.  Yeah, I thought this sounded familiar.

Yes, practically I think we should just accept these at this juncture.  It's unfortunate but we're not losing a ton of petals.  We can recover one pass but because of the MTLs we'll never really get "full depth" here.

**Comment by djschlegel** [comment]
For this particular tile+petal, fiber 2606 could be used as a standard star.  This is a MWS_MAIN_BLUE target that is very close to the standard color box.  An interesting question might be if those particular stars could be used for spectrophotometry for those cases (as enumerated in issue #82) where there are zero standard stars.  There are actually five such stars on this petal: fibers 2568 2606 2625 2670 2706.

**Comment by geordie666** [comment]
@forero: I set the QA for the tile mentioned here (6663) back to none. They will now reappear in regular tile QA. Can you please mark this tile as good when you run QA tomorrow, if you beat me to it?

Also, can you close this issue when you've done that? I think we can keep tracking the issue in #82.

**Comment by forero** [comment]
Done!
