### ISSUE TITLE
Tile 27438 marked as unsure. Recurring low EFFTIME patterns.

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#245]
I've noticed a pattern with tile 27438 across multiple observations.

The most recent data from 20241103 (EXPID 0261223) shows good performance - the tile achieved 108% of its goal exposure time with uniform distribution across all petals and 3681 good fibers, leading to its VALID status. However, there is a clear pattern in EFFTIME across the focal plane.

<img width="1138" alt="241103" src="https://github.com/user-attachments/assets/7b777b6d-7615-469c-8d65-e9f17c2786bc">

This follows a problematic observation from 20240919 (EXPID 00253984) where the tile significantly underperformed. During this exposure, we only achieved 76% of the goal time, with petal 6 completely failing (no standard stars) and several other petals showing very low exposure times. The tile was appropriately marked NOT VALID by the pipeline.

<img width="1186" alt="240919" src="https://github.com/user-attachments/assets/3f14144d-2925-4df6-97a4-f50c3734f7e5">

This pattern isn't new - we saw similar issues back in 20231220 (EXPID 00211321), where irregular exposure time patterns across the focal plane led to marking the tile as bad (referenced in issue #169).
<img width="883" alt="231220" src="https://github.com/user-attachments/assets/f807895c-dc94-473e-8ae5-99210ebbf6e8">

I marked the tile as UNSURE. Looking forward to the team's input on how to proceed.

**Comment by araichoor** [comment]
if useful, I had a look at that: the culprit likely is 253984 from 20240919, 261223 from 20241103 is probably fine.

here I am plotting the sky variation over the field-of-view (the per-fiber median `SKY` value from the `sky-??-EXPID.fits.gz` files, divided by the mean value over the exposure):
- for 253984:
![tmp-bright-00253984](https://github.com/user-attachments/assets/498d3b09-8321-4064-aa40-b8d948f05e71)
- for 261223:
![tmp-bright-00261223](https://github.com/user-attachments/assets/856fe409-cfc0-4735-b1a3-3887c3787f6b)

the amplitude of the pattern for 253984 looks chromatic, being stronger in the redder cameras.
do we know what can cause such pattern? (sorry if that is already known...)

**Comment by geordie666** [comment]
Staring at this I think it's pretty clear that we're going to want to mark  exposure `253984` from `20240919` as bad and reprocess. 

I'm going to give it a day for people to push back on that suggestion before I make this request of the spectro pipeline team.

**Comment by sbailey** [comment]
Done.  The only good exposure from this tile is now night 20241103 expid 261223.
```
TILEID  NIGHT   EXPID  EFFTIME_SPEC
------ -------- ------ ------------
 27438 20231220 211321       0.0000
 27438 20240919 253984       0.0000
 27438 20241103 261223      58.6000
```

**Comment by geordie666** [comment]
I've set the QA status for `27438` to `none`.
