### ISSUE TITLE
Weird behavior of petals 0-3 in tile 23288 

### ISSUE THREAD

**Issue by jose-bermejo** [desihub/desisurveyops#249]
Tile 23288 was marked as unsure. SO reported issues also in the nightlog
![Screenshot 2024-11-14 at 18 44 31](https://github.com/user-attachments/assets/2713421d-53f1-4e98-ab44-0082cc38fad1)

**Comment by geordie666** [comment]
I note that this exposure was close to being right after a `tertiary43` (high airmass) tile, too. From the SO:


```
22:05 [05:05] Exp. 262661- Good - Tertiary -- No issues with data quality. Fairly large blind moves on bottom half of petal plot, same area as large blind move on exposure 626655 earlier in the night. (SO)
Tile 83502, Exptime: 1800.05, Airmass: 2.91, Sequence: DESI, Flavor: science, Program: tertiary43
```

https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20241113/nightqa-20241113.html

**Comment by araichoor** [comment]
running the same piece of code as here https://github.com/desihub/desisurveyops/issues/245#issuecomment-2456396175, ie plotting the sky variation over the field-of-view (the per-fiber median SKY value from the sky-??-EXPID.fits.gz files, divided by the mean value over the exposure):

<img width="1113" alt="Screenshot 2024-11-18 at 2 30 15 PM" src="https://github.com/user-attachments/assets/089f54c3-c1f5-4518-a00f-e41fa948ffa9">

**Comment by geordie666** [comment]
@sbailey: On Monday's survey ops call we decided to mark these exposures as bad and reprocess. Can you please mark exposures `262662` and `262663` from `20241113` as bad and hand that back to me. Thanks!

**Comment by sbailey** [comment]
@geordie666 I have flagged these exposures as bad and reprocessed; they now appear as EFFTIME_SPEC=0 in the exposures-daily files:
```
TILEID  NIGHT   EXPID  EFFTIME_SPEC
------ -------- ------ ------------
 23288 20241113 262662       0.0000
 23288 20241113 262663       0.0000
```
Back to you.

**Comment by geordie666** [comment]
Thanks, Stephen. I've reset the QA for tile `23288` to `none` and I'm closing this issue.
