### ISSUE TITLE
Tile 23224 rejects fibers in patch of high EBV

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#25]
Tile 23224 observed on 2022-02-12 rejects a patch of hundreds of fibers in a patch of high Galactic extinction for failing the effective time cut.  We had planned to replace this EFFTIME cut to be corrected for the median EBV for the tile, rather than the per-object EBV.  That would recover these fibers.

I had marked this tile as QA='good'.  If one wanted to back this out, is it sufficient to edit the surveyops/ops/tiles-specstatus.ecsv file to have QA='unsure' before it gets archived?
![tile-qa-23224-thru20220212](https://user-images.githubusercontent.com/7918018/153770950-9aeaff5e-6220-454c-9286-1d3318198344.png)

**Comment by schlafly** [comment]
Yes, the QA field of tiles-specstatus.ecsv determines what gets archived, and setting it to unsure will pendent the tile from being archived.  We have many such cases, though, so I don't think we should hold this one back.

**Comment by schlafly** [comment]
I'd propose we open this against desispec and close here.  This is marked good, so we don't really need to track this tile specifically it for survey purposes.

**Comment by schlafly** [comment]
Opened https://github.com/desihub/desispec/issues/1685, closing this ticket.
