### ISSUE TITLE
Valid tile with partial Petal 1 on night of 20241130 (tile 23523, exposure 266219)

### ISSUE THREAD

**Issue by geordie666** [desihub/desisurveyops#251]
Petal 1 for tile `23523` has very low `EFFTIME` on the completion night of `20241130` due to the petal being missing entirely for exposure `263681` on the night of `20241118`.

I'm pretty sure these cases are OK for LSS (as all the targets on the low `EFFTIME` petal are marked `QAFIBERSTATUS > 0`) and we can pass tile `23523` as `good`. But it's the weekend so I'm marking the tile as `unsure` just in case. I'll obtain an opinion from the wider group tomorrow.
<img width="1096" alt="20241118" src="https://github.com/user-attachments/assets/feafc029-f28b-410d-a9bf-0f1f8ce00aaf">
<img width="1188" alt="20241130" src="https://github.com/user-attachments/assets/32ef4fad-9b9e-4922-9cd6-3059fa44999b">

**Comment by schlafly** [comment]
Agreed, missing one petal for known reasons -> good.  I think we change our mind at 4 petals.

**Comment by geordie666** [comment]
Great — that was my recollection but I wanted to be careful on a holiday Sunday. I'll update the QA for this tile soon.

**Comment by geordie666** [comment]
I updated the QA for tile `23523` to `none`. @LNapolitano will mark this tile as `good` during normal tile QA tomorrow.

**Comment by geordie666** [comment]
Lucas marked this tile as good, so I'm closing the ticket.
