### ISSUE TITLE
Nights with tiles with exposures with missing times, as reported by Afternoon Planning.

### ISSUE THREAD

**Issue by geordie666** [desihub/desisurveyops#252]
We’ve been triggering warnings in Afternoon Planning about tiles with exposures with missing times. 

The main concern is the following dark/bright tiles and exposures:

- Night: `20241026` / Tile `9768` / Exposure `259821`
- Night: `20241026` / Tile `20968` / Exposure `259822`

Although we also have a backlog of warnings for backup tiles:

```
20240127 (1): 41285 (221977)
20240220 (1): 42548 (226379)
20240322 (1): 42178 (231678)
20240818 (3): 42083 (249035), 42282 (249036), 42918 (249030)
20241019 (2): 41309 (258844), 41340 (258845)
```
These cases are usually caused by issues in offline processing or exposures that we’ve purged from the `exposures-daily.csv` file.

**Comment by sbailey** [comment]
I'll take care of tiles 9768 and 20968 on 20241026.  There was a delay in data transfer such that the last exposures didn't arrive until after the pipeline had ended for the morning.

**Comment by geordie666** [comment]
Eddie marked `9768` and `20968` as `good` in daily QA, so I'm closing this issue.
