### ISSUE TITLE
Tiles 1970 and 2340 from 20241209 have NSTDSTAR = 1 alerts

### ISSUE THREAD

**Issue by LNapolitano** [desihub/desisurveyops#255]
As can be seen on the tile QA sheets both tiles have a petal with one standard star and no EFFTIME plot as a result. I've currently marked both tiles as "unsure". This thread details similar cases: https://github.com/desihub/desisurveyops/issues/82
 
<img width="1714" alt="20241208-Tile2340" src="https://github.com/user-attachments/assets/9e220429-8964-4cee-b862-137cd8676121">
<img width="1717" alt="20241208-Tile1970" src="https://github.com/user-attachments/assets/3dac3d86-c053-4815-ad2b-6f867c1f1c46">

**Comment by geordie666** [comment]
I've reset the QA for tiles 1970 and 2340 as good based on Slack discussions (https://desisurvey.slack.com/archives/C01HNN87Y7J/p1733768464101579). I'll close this issue once they're marked good.
