### ISSUE TITLE
sky warnings on tile 26589

### ISSUE THREAD

**Issue by ashleyjross** [desihub/desisurveyops#256]
Everything else looks ok, but it is marked unsure for now in case I missed something
<img width="966" alt="Screenshot 2024-12-10 at 2 41 47 PM" src="https://github.com/user-attachments/assets/53282d4b-433d-47f1-b384-12e9e0624abb">

**Comment by geordie666** [comment]
We [marked this as good](https://desisurvey.slack.com/archives/C01HNN87Y7J/p1733932475832609), so closing the issue.
