### ISSUE TITLE
Bright tile 21348 with strong z=0.6 pileup for sky fibers

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#29]
Bright 21348 observed on 20220314 shows a strong z=0.6  pileup for sky fibers on petal 7

![unsure-tile21348](https://user-images.githubusercontent.com/1848618/158448977-fab502a9-c533-4257-9f8d-32e5ba2ccf2d.png)

**Comment by schlafly** [comment]
The sframe files look fine to me, though the moon was clearly quite bright with a gradient in the petal.  Given that the actual targets aren't really participating in this pile up, I'm inclined to go ahead and mark this tile as good.  I'll give it a day for anyone else to overrule.

**Comment by schlafly** [comment]
I've optimistically marked this as good in QA and will close tomorrow.
