### ISSUE TITLE
Bright tile 26226 observed with high read noise 

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#32]
Bright tile 26266 observed on 20220318 over three different exposures was reported by the observers to have high read noise on all of them.

<img width="728" alt="Screen Shot 2022-03-19 at 2 41 48 PM" src="https://user-images.githubusercontent.com/1848618/159136023-c2f8344c-984f-4c18-96c5-b3b8463d32d1.png">

The redshifts as a function of FIBERID look patchier than usual. They seem to have a pattern that changes petal by petal. 

<img width="1215" alt="26226-unsure" src="https://user-images.githubusercontent.com/1848618/159135932-71f99021-c8df-4fe4-b636-6f2ad81b013e.png">

**Comment by schlafly** [comment]
We discussed this on the 20220321 survey-ops call and decided that we would call these exposures bad (126715, 126716, 126717, 126718).  This is the three exposures on the BRIGHT tile (026226) and the one exposure on the following BACKUP tile (41779).  I'm not convinced that the read noise is actually an issue on this BRIGHT tile in very bright sky conditions, and I'm confident that it's not an issue on the following BACKUP tile, but for homogeneity's sake we'll take the very marginal loss of effective time.

@akremin, can you mark these as bad and reprocess?

**Comment by schlafly** [comment]
@akremin , this one has somewhat high priority because it's one of the few tiles remaining in the early, southern part of the NGC, which is now setting.  It would be good to mark this exposure bad so that we can get more observations to complete this section of the footprint in Y1.

**Comment by akremin** [comment]
Apologies -- I missed this the first time around and am just getting to it after the ping yesterday.

The four exposures (126715, 126716, 126717, 126718) have been marked bad, and the spectra+redshift files associated with those exposures have been removed from daily. There were no other exposures for those tiles, so nothing needed to be rerun. I also don't see any later observations of the tiles, so no downstream cumulatives need to be redone either.

I just reran the tsnr script and the nigthly_qa script to reflect the removal of these exposures.

Back to you, Eddie.

**Comment by schlafly** [comment]
Thanks, I cleared the QA here.
