### ISSUE TITLE
Bright tile 23736 with suspicious low-z pileup

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#33]
Bright tile 23736 observed on 20220318 has a low redshift z=0.25 pileup that might be real,  but it looks suspicious because it's exclusively located on petal 7 and does not extend across neighboring petals 6 and 8.
<img width="1374" alt="23736-unsure" src="https://user-images.githubusercontent.com/1848618/159136195-b5ae83e9-a1e1-4b23-aa5a-9062ff1c4032.png">

**Comment by schlafly** [comment]
I plotted up a few of these spectra via
plot_spectra -i ~/redux/daily/tiles/cumulative/23736/20220318/coadd-7-23736-thru20220318.fits --zrange 0.01 0.05 --redrock ~/redux/daily/tiles/cumulative/23736/20220318/redrock-7-23736-thru20220318.fits --rebin 5 --errors
e.g.
![image](https://user-images.githubusercontent.com/1417841/159373885-430bc7b3-2830-4337-ada3-0a9c3ed8bb3e.png)
They look fine to my untrained eyes.  With some imagination I can see the cluster of blue galaxies here
https://www.legacysurvey.org/viewer?ra=173.8225&dec=48.8569&layer=ls-dr9&zoom=12
that are making these.

Given that the sframe's also look fine---I don't think there's a hot unmasked column, or something---I'm declaring this good and closing.
