### ISSUE TITLE
Acquisition failed on tile 2219

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#37]
Field acquisition failed on tile 2219 exposure 128339 on April 1.  This is a high-Galactic-latitude DARK tile.  Conditions were good with 1.3 arcsec seeing in clear, dark skies: https://www.legacysurvey.org/viewer?ra=187.319&dec=36.81&layer=ls-dr9&zoom=8&desifoot=187.3190,36.5810

Steve Kent's response: Yes, low star density.  Several other fields in the same region succeeded, so this one was just over the edge.  There are several tuning parameters in the star finding and matching code, and I think allowing fainter stars is the easiest fix  (the current limit is 18th mag).  Note that the parameters were tuned in the days when the GFA CCDs were often in their noisy state and PM still succeeds when that happens.  Given how rare the failures have been, I'd suggest waiting for a few more to occur before making any change (which is eay to do - Klaus needs to edit a configuration file but no reinstall of code is needed.)

We could change this configuration file (to a faint limit of 18.5 or 19.0) and try re-observing at this exact location again.  I suggest we design BACKUP tile 42546 which has exactly the same coordinates and observe during engineering time.  (The corresponding BRIGHT tile has slightly different coordinates due to our small offsets to some tile centers to avoid bright stars on disabled fibers, and we've already observed it anyway.)

**Comment by djschlegel** [comment]
BACKUP tile 42546 at the identical location was observed as EXPNUM 130102 on 2022-04-13.  Field acquisition succeeded.  The conditions were pretty different, though, with a very bright sky (sky level=10) and very good seeing (0.85 arcsec).

**Comment by schlafly** [comment]
It sounds to me like we can declare this a success and close the ticket?
