### ISSUE TITLE
Exposure ID 129062 on tile 24668 was out-of-focus

### ISSUE THREAD

**Issue by geordie666** [desihub/desisurveyops#39]
Another exposure at the very beginning of the night that looks like it was out-of-focus causing petal 7 to mostly be dropped:

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/24668/20220407/tile-qa-24668-thru20220407.png

**Comment by schlafly** [comment]
We need to mark 129062 as bad and reprocess (though this is the only exposure so this just means propagating EFFTIME = 0 forward.

**Comment by akremin** [comment]
Flagged exp 129062 on tile 24668 on 20220407 to ignore and removed the spectra and redshift files, and updated the summary tables and nightqa. There were no other observations of the tile, so nothing to rerun.

Done on the pipeline side.

**Comment by schlafly** [comment]
I've cleared the QA for this tile.  When it's observed one of these nights it should pop up again for QA.
