### ISSUE TITLE
Tiles with ~large sky residuals that need to be marked bad or better processed

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#4]
These are currently "unsure" and typically have lots of significant redshifts at z=1.8.  Often have SKYCHI2PDF warning.  May just need to have their component exposures marked bad so that NTS will reobserve them.

Affected: 20140, 21321, 23276, 24633, 24634, 26147

e.g.
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/20140/20211117/tile-qa-20140-thru20211117.png

sframe files show lots of sky amplitude variation from fiber to fiber that is either a gradient or cloudy?
https://data.desi.lbl.gov/desi/users/raichoor/main-status/sframesky/sframesky-20211117-00109233.png

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/20140/20211117/tile-qa-20140-thru20211117.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/21321/20220114/tile-qa-21321-thru20220114.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/23276/20211117/tile-qa-23276-thru20211117.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/24633/20211219/tile-qa-24633-thru20211219.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/24634/20211219/tile-qa-24634-thru20211219.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/26147/20211219/tile-qa-26147-thru20211219.png

**Comment by julienguy** [comment]
Would be interesting to display the sky residual brightness as a function of focal plane coordinates.

**Comment by schlafly** [comment]
No idea if this is the right plot, but here's something:
![image](https://user-images.githubusercontent.com/1417841/150891436-0fe97d95-8fab-481b-be0e-9d99f97c2533.png)
I took all the sky fibers, and extracted the median flux from the frame-r files (i.e., not sframe, cframe, coadd ...) with 6000 < lam < 7000, and then plotted.  So, yes, obvious structures on sub-petal scales, I think?  If I were better, I should be adding the skies to the sframes and doing this, and then might be taking advantage of the fiberflat?

**Comment by julienguy** [comment]
gradient due to moon light or twilight?

**Comment by schlafly** [comment]
Here's a gallery of these cases:
https://data.desi.lbl.gov/desi/users/schlafly/sky/largeskyresid.pdf
It's likely I don't yet have the direction to the moon right, etc.; I need to check this more.  But the most striking thing to me about these is that the trend is more radial than a gradient.

I suspect this means that I'm primarily looking at the fiber flat field.  I didn't want to work with the sframe files because I wanted the sky.  I don't immediately see where the fiberflat lives, so maybe the best choice is to use the sframe + sky files, which will be flattened?

I'd also be interested in understanding the THRPUTCORR extension of the sky models; every fiber gets an empirical sky amplitude fit, maybe based on bright sky lines?  That would be news to me?

**Comment by sybenzvi** [comment]
Several more exposures with similar SKYCHI2PDF warnings:
* https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/21829/20220516/tile-qa-21829-thru20220516.png
* https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/24896/20220516/tile-qa-24896-thru20220516.png
* https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/24905/20220516/tile-qa-24905-thru20220516.png
* https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/24919/20220516/tile-qa-24919-thru20220516.png
The sky fiber sframes show the fiber-to-fiber striped variations mentioned earlier in the ticket:
* https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20220516/sframesky-20220516.pdf

**Comment by geordie666** [comment]
A few more of these. Back-to-back exposures (`139344` and `139345`) on `20220611` had multiple sky `CHI2PDF` alerts:

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/25124/20220611/tile-qa-25124-thru20220611.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/25109/20220611/tile-qa-25109-thru20220611.png

See (closed) issue #59 for details.

**Comment by schlafly** [comment]
@akremin, can we reprocess the following tiles now that the new sky subtraction code is in?  We'd then want to re-QA them and see if we can mark them as good and archive & mtl-update.

This list merges a few different issues together to hopefully get all the tiles that I think may be able to be solved by improved sky subtraction.

```
TILEID LASTNIGHT   QA  
int64    int64    str6 
------ --------- ------
  2295  20220211 unsure
  5805  20220505 unsure
  7009  20211215 unsure
  8801  20220219 unsure
 20140  20211117 unsure
 21321  20220114 unsure
 21809  20220512 unsure
 21828  20220612 unsure
 21829  20220516 unsure
 21984  20220514 unsure
 23276  20211117 unsure
 24633  20211219 unsure
 24634  20211219 unsure
 24896  20220516 unsure
 24905  20220516 unsure
 24919  20220516 unsure
 25109  20220611 unsure
 25124  20220611 unsure
 26147  20211219 unsure
```

**Comment by akremin** [comment]
I have removed and re-run all of the exposures associated with the above tiles on the corresponding nights. None of the tiles were observed on other nights and none of them were archived, so this was a clean procedure. The redshifts are now done and the tsnr afterburner + night QA have been rerun on the new outputs. The scripts used for this cleanup are in `/global/cfs/cdirs/desi/spectro/redux/daily/run/scripts/custom/large_sky_residuals_20220909`.

These tiles are now ready for re-QA.

**Comment by schlafly** [comment]
Great!  Here are the results:
```
  2295  20220211 unsure
  5805  20220505 good
  7009  20211215 good
  8801  20220219 good
 20140  20211117 unsure
 21321  20220114 unsure
 21809  20220512 good
 21828  20220612 unsure
 21829  20220516 good
 21984  20220514 good
 23276  20211117 unsure
 24633  20211219 unsure
 24634  20211219 good
 24896  20220516 good
 24905  20220516 good
 24919  20220516 good
 25109  20220611 good
 25124  20220611 unsure
 26147  20211219 good
```
So 2/3 of these are now survey quality and marked good.  Let's discuss briefly on the data call later today, but I'm going to recommend we mark the others bad and reprocess.  Some examples:
dark tile 2295:
![image](https://user-images.githubusercontent.com/1417841/189848853-0768f4a0-fb76-4c29-aaec-5866d22b0db3.png)
The line at z=1.8 is related to sky residuals.  But it is very subtle.  I could be convinced to keep it as good, I guess.

20140:
![image](https://user-images.githubusercontent.com/1417841/189849111-94db0a85-6b21-4e7b-8466-bf8c58458fb1.png)
Still pretty bad.

25124:
![image](https://user-images.githubusercontent.com/1417841/189849284-0bb9e1b2-2635-4a8d-82e2-1a913b8ff830.png)
More arguable, but I've left it unsure.

21828:
![image](https://user-images.githubusercontent.com/1417841/189849621-e154dfa8-557d-4016-81eb-ba30aef3cd77.png)
More arguable, but I've left it unsure.

I don't see any easy approaches to improving the sky subtraction further at the desispec level.  One could imagine next steps being fitting the sky simultaneously among the three cameras (e.g., to avoid jumps at camera boundaries), and introducing additional terms into redrock to soak up sky residuals.  But those would be more major operations.

**Comment by schlafly** [comment]
@akremin, following the discussion on yesterday's survey-ops call, let's go ahead and mark 
```
  2295  20220211 unsure
 20140  20211117 unsure
 21321  20220114 unsure
 21828  20220612 unsure
 23276  20211117 unsure
 24633  20211219 unsure
 25124  20220611 unsure
```
as bad and reprocess.  Then I need to clear their QA status to none.

**Comment by akremin** [comment]
The above tiles have all had the corresponding night's exposures removed, along with redshifts. None had later night's redshifts. I have rerun the tsnr afterburner for all nights.

Back to you, @schlafly .

**Comment by schlafly** [comment]
Thanks, this is in.  Closing!
