### ISSUE TITLE
Exposure 130095 on tile 22170 did not have fiber correction move

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#40]
Exposure 130095 on BRIGHT tile ~22211~ 22170 (night 20220413) did not have fiber correction move and should be rejected.  I didn't catch this until seeing the QA plot, combining those data with exposure 130266 on night 20220414.

That first exposure should be marked bad, and the cumulative tile reductions removed.  We'll need another exposure on this tile to complete it.

**Comment by schlafly** [comment]
This tile currently has 0 EFFTIME_SPEC.  I think this means that we have treated it correctly and I can close this ticket.  Agreed?

**Comment by djschlegel** [comment]
That's some good luck!  No action *required*, though I would still be more comfortable with having such exposures intentionally labeled as bad in Anthony's exposure tables so that we don't accidentally pick them up in any future reductions.

**Comment by sbailey** [comment]
I think the posting has a typo on the tileid; those exposures are tile 22170 not 22211 and it does require cleanup to remove the first exposure (which I typo checked that it does indeed have poor positioning).  I'll cleanup after I finish my last meeting of the day (but too late for tonight's plan...)

**Comment by schlafly** [comment]
Ah, yes, 22170 is definitely a mess.  Correcting the title.

**Comment by sbailey** [comment]
I flagged exposure 20220413/130095 as bad, purged it from the 0413 processing, reprocessed tile 22170 lastnight 20220414 redshifts, and remade the tiles-daily.* and exposures-daily.* files.  EFFTIME_SPEC is now 95.5 .

**Comment by schlafly** [comment]
After running desi_update_tiles_specstatus, I was still left with the following entry for 22170:
22170 main bright mainbright 2 1509.8 179.968 57.392 247.5 210.1 308.6 180.0 obsend false 201.3 235.9 210.1 130.3 bright 0.85 20220414 unsure schlegel 0 20220414 0
I'm worried about the "obsend" status and the 210 s EFFTIME_SPEC.

**Comment by schlafly** [comment]
Now fixed with an update from tiles-specstatus.ecsv (desi_update_tiles_specstatus --all --tileids to force update of particular tileids when LASTNIGHT matches).
