### ISSUE TITLE
Expid 113678 not propagated into tsnr-exposures.fits / exposures-daily.fits

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#46]
Expid 113678 is a bad exposure on tile 21281 for which the ETC estimates 0.085 s of effective exposure time.  This exposure looks to have been rejected by the pipeline (EFFTIME_SPEC = 0), but it doesn't have a record in the tsnr-exposures file and so the NTS believes that this tile has 0.085 s of effective time, when it should have 0 seconds of effective exposure time.  Can we get an entry in tsnr-exposures.fits recording the fact that the pipeline has rejected this tile?  Thanks!

**Comment by akremin** [comment]
All exposures on this night were low efftime (bad weather). That triggered a longstanding bug in the tsnr afterburner that crashes if no valid exposures are present on a night: https://github.com/desihub/desispec/issues/1345 .

I'll look into fixing that long-standing issue now that it has real implications.

**Comment by akremin** [comment]
This exposure is now in the `exposures-daily.csv` file after rerunning following https://github.com/desihub/desispec/pull/1950:
```
>$ grep 113678 exposures-daily.csv
20211213,113678,21281,336.495,21.243,59562.087959013,main,bright,bright,mainbright,718.3,0.0,180.0,bright,0.85,0.0,0.047,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.084,1.366,0.447,0.338,0.159,0.061,0.064,0.066,1.124,17.207,17.904,17.206,16.856,0.0,0.0,0.0,0.0
```
