### ISSUE TITLE
Tileid=21809 marked as unsure; large sky residuals, possibly due to weird scattered light path?

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#48]
This TILEID=21809 has been observed on 20220512 with EXPID=134448.
It has been marked as "unsure".

It has ZSKYPDF alert for petal=6,7,8.
The n(z) look a bit awkward.
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/21809/20220512/tile-qa-21809-thru20220512.png
![tile-qa-21809-thru20220512](https://user-images.githubusercontent.com/61986357/168506770-2347dfd0-fac1-45f0-895d-81148b29484b.png)

The sframesky has some brightish lines in the z7 camera, but I can t figure out where that does come from (no bright star in the viewer); the neighboring exposures have nothing like tht.
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20220512/sframesky-20220512.pdf
<img width="907" alt="Screen Shot 2022-05-15 at 6 53 13 PM" src="https://user-images.githubusercontent.com/61986357/168506893-b9eaa56b-ed6e-4f00-99f1-676165a4fa99.png">

The sky monitor also has significantly brighter sky there (it's the outlier at 8:00):
![image (5)](https://user-images.githubusercontent.com/61986357/168506295-115d1f93-7727-4b12-a150-247219390584.png)

Don't know if that s related, but the cryostat pressure for sm8 (=petal=7) has some fluctuations before that exposure:
https://telemetry.desi.lbl.gov/d/xcYVcw3Zk/spectrographs-cryostats?orgId=2&from=1652403600000&to=1652443200000
<img width="650" alt="Screen Shot 2022-05-15 at 6 54 33 PM" src="https://user-images.githubusercontent.com/61986357/168506998-cfafe354-2db0-4974-aab8-bdba1aed6f6e.png">

Original slack message: https://desisurvey.slack.com/archives/C01HNN87Y7J/p1652480247392209

**Comment by schlafly** [comment]
@akremin, let's go ahead and mark 20220512/21809 as bad & reprocess.  Then we'll need to clear QA.

**Comment by araichoor** [comment]
if I m correct, this tile has been reprocessed on Sept. 9, and archived as "good" on Sep. 22.
so we could close this ticket?

**Comment by schlafly** [comment]
Thanks, closing!

**Comment by akremin** [comment]
This was indeed archived on 20220922. @schlafly please advise.
