### ISSUE TITLE
Tileid= 21984 marked as unsure

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#50]
Tileid=21984 has been observed with expids=134791-92 on 20220514.
It has several r- and z-band sky alerts (petals 4-5-6-7-8-9); and a suspicious bgs_faint n(z), despite having nominally ~1.5 more effime than required (efftime=265s):
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/21984/20220514/tile-qa-21984-thru20220514.png
![tile-qa-21984-thru20220514](https://user-images.githubusercontent.com/61986357/168710987-770c3864-0d88-4b6a-a86d-017c69cdc388.png)

If relevant, on the same night, all backup exposures from expid=134789 onwards were flagged as "unsure" by the observers in the nightlog.
Besides, these expids=134791-92 were preceded/succeded with backup observations, so conditions might have been variable.

**Comment by schlafly** [comment]
This is a large sky residual case that has been added to the list of tiles for reprocessing in
https://github.com/desihub/desisurveyops/issues/4
Closing here.
