### ISSUE TITLE
Tileid 9934 marked as unsure

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#51]
Tileid 9934 was observed with exposure 136310, 136311 and 136312 on 20220522.
It apperead as a clear outlier on the Lya plot. The redshifts as a function of the fiberid looks clumpy in some locations.

<img width="668" alt="Screen Shot 2022-05-23 at 12 59 54 PM" src="https://user-images.githubusercontent.com/1848618/169891835-2170c6b1-6fa1-4ca9-9acf-8f58d1bcbf37.png">

<img width="1127" alt="Screen Shot 2022-05-23 at 12 59 30 PM" src="https://user-images.githubusercontent.com/1848618/169891874-f45dd41e-6052-4684-a4a4-51fd7524f1aa.png">

In the nightlog we can read: "SPLIT on DARK tile 9934, exposure 136311. Survey speed dropped from 85% to 40%, presumed to be seeing related."

**Comment by schlafly** [comment]
Following Ashley's analysis here
https://desisurvey.slack.com/archives/C01HNN87Y7J/p1653335184279529?thread_ts=1653334819.325629&cid=C01HNN87Y7J
and my inspection of the tileqa & sframe files, I think it's fine to mark this as good.  If you could do this tomorrow as part of QA, that would be great.  desi_tile_vi --tileid 9934 will show only this one and give you the chance to mark it as good.

**Comment by forero** [comment]
Thanks. I will do so tomorrow!
