### ISSUE TITLE
Tile 11103 marked unsure -- Z7 sky chi2

### ISSUE THREAD

**Issue by dstndstn** [desihub/desisurveyops#53]
Expnum 137248 on 2022-05-29.  The tile qa plot looked fine to me, but the sframesky QA plot shows a broad glowing back in R7 and Z7, and the Z7 one triggered a warning on the QA plot.

<img width="1270" alt="1" src="https://user-images.githubusercontent.com/1065981/171041871-e5f80eff-df37-4f55-aef2-c1f52220d57c.png">

**Comment by djschlegel** [comment]
This appears to be due to the very bright star g Her landing on petal 7.  It's very red (B=6.5 but J=-0.8).
<img width="894" alt="Screen Shot 2022-05-30 at 11 35 48 AM" src="https://user-images.githubusercontent.com/7918018/171045673-8acea1be-66ac-47cc-ba32-c0b6a58db7ff.png">

**Comment by schlafly** [comment]
Dustin, given the very bright star, can you go ahead and mark this as good?  The --tileids to desi_tile_vi should work now to let you just update 11103.

**Comment by dstndstn** [comment]
Thanks, done!
