### ISSUE TITLE
Tile 9219 marked unsure: the left half of petal 1 fibers are flagged

### ISSUE THREAD

**Issue by dstndstn** [desihub/desisurveyops#56]
![tile-qa-9219-thru20220601](https://user-images.githubusercontent.com/1065981/171734467-c7b6b18c-20b9-43a2-b9c6-d98131f723d7.png)

**Comment by schlafly** [comment]
We're accepting these and moving on.  @julienguy , this doesn't look to me like the normal kind of cosmic ray overscan contamination case though.  It looks to me like there's a normal CR without hysteresis there, though, that might be causing issues?
![image](https://user-images.githubusercontent.com/1417841/171743778-f799e6ee-ba93-4982-a28c-6c1b4a331e0f.png)

**Comment by schlafly** [comment]
(i.e., @dstndstn , please mark as good tomorrow despite the one flagged CCD)

**Comment by dstndstn** [comment]
Done!
