### ISSUE TITLE
Add 10 deg twilight to the Afternoon Planning code

### ISSUE THREAD

**Issue by geordie666** [desihub/desisurveyops#57]
The AP code reports 6 deg and 12 deg twilight. We seem to be moving towards 10 deg twilight in the plan. We currently integrate between 6 deg and 12 deg twilight to determine 10 deg twilight.  

We should include 10 deg twilight in the manual plan next time we update the AP code.

Related: Should the instructions change to "focus the telescope 5 minutes before" instead of "10 minutes before" twilight?

**Comment by schlafly** [comment]
10 deg twilight was put in at some point.  I haven't changed the focusing wording but I have the impression that the LOs don't need more input there; closing.

**Comment by geordie666** [comment]
Looks like this didn't actually get closed. Closing now.
