### ISSUE TITLE
z3 CTE issue tiles benefitting from future reprocessing

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#6]
z3 had CTE issues from 20211126 - 20211202 (inclusive).  These are minor and could be largely fixed with the per-sector fits.

**Comment by schlafly** [comment]
@julienguy , I'm assigning you this for the moment, but please push back as appropriate.  Broader ticket is to make sure we have all of the sm.yaml files updated so that we fit out the sectors when we can.  This should probably be for all of the tiles we formerly marked bad in November?

**Comment by julienguy** [comment]
I am on it

**Comment by julienguy** [comment]
Done. See https://github.com/desihub/desispec/issues/1826 .
