### ISSUE TITLE
6 bright tiles from 20220422 with no fiberassign intermediate files

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#60]
I notice that six bright tiles from 20220422 are not present in `$DESI_ROOT/survey/fiberassign`.
I think that we just did not run `validate_lastnight_fba` on Apr. 23 (maybe we forgot, or there was another reason).
I ve checked that:
- those have been archived with "good" status;
- all other main tiles with LASTNIGHT=20220422 have also been observed before/after that night, so they have been dealt with.

@ashleyjross : would running `validate_lastnight_fba --night 20220422` be the thing to do?

code snippet to identify the six tiles:
```
fns = sorted(glob("/global/cfs/cdirs/desi/survey/fiberassign/main/???/??????-targ.fits"))
tileids = [int(os.path.basename(fn)[:6]) for fn in fns]
d = Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/tiles-daily.csv")
miss = (d["SURVEY"] == "main") & (~np.in1d(d["TILEID"], tileids))
d[miss]["TILEID", "FAFLAVOR", "NEXP", "EFFTIME_SPEC", "LASTNIGHT"].pprint_all()

TILEID  FAFLAVOR  NEXP EFFTIME_SPEC LASTNIGHT
------ ---------- ---- ------------ ---------
 23552 mainbright    2        244.6  20220422
 21675 mainbright    1        207.8  20220422
 21785 mainbright    1        195.1  20220422
 21786 mainbright    1        207.2  20220422
 21831 mainbright    1        192.8  20220422
 23554 mainbright    1        230.1  20220422
```

code snippet to check "good" status:
```
specstatus = Table.read("/global/cfs/cdirs/desi/survey/ops/surveyops/trunk/ops/tiles-specstatus.ecsv")
np.unique(specstatus[np.in1d(specstatus["TILEID"], d["TILEID"][miss])]["QA"])

good
```

check that those are the only tiles from 20220422 which have been only observed on 20220422:
```
night = 20220422
exps = Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures-daily.csv")
for tileid in np.unique(exps["TILEID"][exps["NIGHT"] == night]):
    sel = exps["TILEID"] == tileid
    first_night, last_night = exps["NIGHT"][sel].min(), exps["NIGHT"][sel].max()
    if (first_night == night) & (last_night == night):
        print(tileid)

21675
21785
21786
21831
23552
23554
```

**Comment by araichoor** [comment]
@sbailey : would it make sense to add in the archiving routine a check that all intermediate fiberassign files are there, and to refuse to archive a tile if those are missing?

**Comment by ashleyjross** [comment]
Thanks Anand! That command should be correct, I'm running it now.

**Comment by ashleyjross** [comment]
(They all passed. There were 16 to check from the night but only 6 to copy as the other 10 must have been observed on another night copied when validated for the other night.)

**Comment by araichoor** [comment]
awesome, thanks!
(yes, I confirm that the ten other ones have also been observed on another night, that was my last check).

**Comment by schlafly** [comment]
I think we can go ahead and close this ticket?

**Comment by schlafly** [comment]
@araichoor , can we go ahead and close this ticket?

**Comment by araichoor** [comment]
I confirm the intermediate files are now there for those six files, so I close this ticket:

```
raichoor@cori12:~> date; for TILEID in 021675 021785 021786 021831 023552 023554; do echo $TILEID `ls $DESI_ROOT/survey/fiberassign/main/${TILEID:0:3}/$TILEID-*.fits | wc -l`; done
Mon Aug 15 15:53:38 PDT 2022
021675 5
021785 5
021786 5
021831 5
023552 5
023554 5
```
