### ISSUE TITLE
Last main tile completed before shutdown, tile 23644, is unarchived

### ISSUE THREAD

**Issue by akremin** [desihub/desisurveyops#61]
The following tile was QA'd after the last night of observation before the 2022 fire shutdown. It is the only main survey tile (excluding backup tiles) with enough exposure time and QA='good' that is not archived according to `tiles-specstatus.ecsv`.

```
TILEID,SURVEY,FAPRGRM,EFFTIME_SPEC,GOALTIME,ZDONE,QA
23644,main,bright,250.9,180.0,false,good
```

My guess is we expected more nights of observing and we weren't archiving daily, so this was left behind. @araichoor was the one who QA'd it, so he should say if that is true or not.

Assuming Anand approves, should we archive this @schlafly?

**Comment by schlafly** [comment]
The tile looks fine to me.  I'll go ahead and archive it now.  I somehow missed that we had a main survey tile on that night, sorry.

**Comment by schlafly** [comment]
This is now archived, together with 4215 which I also recently moved from unsure -> good.
