### ISSUE TITLE
Tile 11066 has poor QSO redshift distribution

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#62]
The redshift distribution for QSOs on tile 11066 observed on 2022-09-15 appears to be poor.  About 20% of these have redshifts near z=0.95 or z=1, which appears to be spurious.  Note the sky subtraction is worse-than-typical for this tile, as it was observed with 3 exposures in deteriorating conditions where the sky brightened from ~3 to ~5.
![tile-qa-11066-thru20220915](https://user-images.githubusercontent.com/7918018/190918918-009f25ea-6af7-4dcd-b4ec-a317c6981ac5.png)

**Comment by araichoor** [comment]
for book-keeping, copying here what was reported on slack for these 11066 observations (https://desisurvey.slack.com/archives/C01HNN87Y7J/p1663460432362239):
- the Moon separation is 42º (constraint accidentally set to 40º instead of 50º)
- the ELG redshift distribution also looks poor
- from the nightlog, EXPID=142568 could be discarded:
```
04:15 [11:15] SPLIT on DARK tile 11066. Survey speed now <35% as moon continues to reach overhead. Monitoring. (LO)
04:16 [11:16] Exposure 142567 on DARK tile 11067 is fine (a SPLIT). (LO)
04:24 [11:24] Survey speed <25%. May be necessary to stop current exposure and move to BRIGHT tiles as 18 twilight emerges shortly. (LO)
04:36 [11:36] Second SPLIT on DARK tile 11066. Survey speed now <30% as moon continues to reach overhead and. sky brightens for 18 degree twilight. Monitoring. (LO)
04:37 [11:37] Exposure 142568 on DARK tile 11066 is technically fine (a second SPLIT). Likely needs rejecting for short exposure and low SNR due to Moon and sky brightness. (LO)
```

**Comment by schlafly** [comment]
@akremin, let's go ahead and mark 20220915/11066 as bad and reprocess, then I'll clear QA.

**Comment by akremin** [comment]
Clarifying on this one -- you want all 3 exposures marked as bad and the tsnr rerun so that it reflects 0 efftime?

**Comment by araichoor** [comment]
if useful, here are few numbers for the three exposures:

```
>>> d = Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures-daily.fits", "EXPOSURES")
>>> d = d[d["TILEID"] == 11066]
>>> d["NIGHT", "EXPID", "EXPTIME", "EFFTIME_SPEC", "SKY_MAG_R_SPEC"]
<Table length=3>
 NIGHT   EXPID       EXPTIME         EFFTIME_SPEC      SKY_MAG_R_SPEC  
 int32   int32       float64           float64            float64      
-------- ------ ----------------- ------------------ ------------------
20220915 142566 1744.362060546875  655.0241088867188 20.062223500827834
20220915 142567  1159.86083984375 314.78814697265625 19.881279541007263
20220915 142568 661.6949462890625 140.84600830078125 19.829756755864885
```

maybe the first one is ok? it has EFFTIME_SPEC/EXPTIME~0.38 (the last two have 0.27 and 0.21).

**Comment by schlafly** [comment]
Thanks Anthony, Anand.  Let's follow Anand's suggestion and mark 142567 and 142568 as bad only, though I worry we'll be coming back to this 142566.

**Comment by schlafly** [comment]
@akremin , pinging this outstanding low dec tile.

**Comment by akremin** [comment]
142567 and 142568 have been marked as bad and reprocessed tile 11066 with just exposure 142566. The daily files have been updated and nightqa re-populated.

**Comment by schlafly** [comment]
This got its top-off observation on 20230121 and now looks good.  Closing.
