### ISSUE TITLE
Tile 4542 marked unsure: redshift pileup around z=1.7 on four petals

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#64]
The redshift distribution on tile 4542 observed on 2022-09-23 appears to have a pileup arond z=1.7 on four petals, which appears to be spurious. The sky substraction did not raise any warnings.

![Screen Shot 2022-09-30 at 8 49 23 AM](https://user-images.githubusercontent.com/1848618/193285111-490c78b6-2cf2-4d6d-afa7-1938f2a46084.png)

**Comment by schlafly** [comment]
@akremin, let's go ahead and mark 20220923/4542 as bad and reprocess, then I'll clear QA.

**Comment by akremin** [comment]
This exposure has been removed and the tsnr rerun. Back to you @schlafly

**Comment by schlafly** [comment]
Cleared QA; closing.
