### ISSUE TITLE
Tile 4824 marked as unsure. More z=0.0 galaxies than usual.

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#65]
The redshift distribution on tile 4824 observed on 2022-09-27 appears to have more z=0.0 galaxies than usual. The sky substraction did not raise any warnings.

![Screen Shot 2022-09-30 at 8 59 56 AM](https://user-images.githubusercontent.com/1848618/193287944-8408c681-b866-48d3-a05a-05a9d963b805.png)

**Comment by djschlegel** [comment]
Many of the fibers on this tile have bright (positive or negative) apparent rest-frame [S II] 6716/6730 emission that Redrock is latching onto, some [N II], but not H-alpha.

**Comment by schlafly** [comment]
Marking as good since this is nebular emission we will have to address in the pipeline; closing.
https://github.com/desihub/desispec/issues/1861
