### ISSUE TITLE
Tile 5165 marked unsure -- petal 7 had poor positioning, should be omitted entirely

### ISSUE THREAD

**Issue by dstndstn** [desihub/desisurveyops#66]
Hi @akremin , any chance you could reprocess tile 5165, but omit Petal 7 entirely?  It was processed and the majority of sources were marked as bad due to poor positioning, but I think we'd prefer to just ignore the whole petal.

**Comment by dstndstn** [comment]
![tile-qa-5165-thru20221001](https://user-images.githubusercontent.com/1065981/194153093-b796ddea-4bb9-4835-869b-493a416ee1e1.png)

**Comment by schlafly** [comment]
20221001/145206, tileid 5165.  P7 needs to be marked bad and then 5165 reprocessed---thanks!

**Comment by schlafly** [comment]
@akremin , pinging on this outstanding low dec tile, thanks!

**Comment by akremin** [comment]
p7 on 145206 has been marked as bad and the exposure+tile reprocessed. I've rerun the daily tables and regenerated nightqa.

**Comment by schlafly** [comment]
Looks good, QA is now good, closing.
