### ISSUE TITLE
Tile 6984 has weird sky on Petal 7

### ISSUE THREAD

**Issue by dstndstn** [desihub/desisurveyops#67]
![tile-qa-6984-thru20221001](https://user-images.githubusercontent.com/1065981/194155048-6a6f1a23-d069-4fd8-af61-2b6f13f29d84.png)

**Comment by dstndstn** [comment]
Looking in the sframesky plot shows weird residuals

<img width="1295" alt="1" src="https://user-images.githubusercontent.com/1065981/194155254-ef32c38d-bf1a-4756-8c14-8d0b0c7b537b.png">

**Comment by schlafly** [comment]
The broad sky feature in the r camera at wavelength pixel ~150 is also weird?  Too broad to be astronomical?  I can't do this today, but a next step would be to plot the spatial distribution of the median sky residuals.  I really want that to be the fiducials 470 nm LED light, but that clearly doesn't work out?

**Comment by rongpu** [comment]
Looks like there are some cirrus in petal 6 and 7, but it's hard to fathom how it could cause broad band features: https://www.legacysurvey.org/viewer?ra=2.1255&dec=-0.4129&layer=ls-dr9&zoom=12&desifoot=1.0000,-1.0000

**Comment by schlafly** [comment]
I haven't been able to figure this out.
![image](https://user-images.githubusercontent.com/1417841/196775542-c338b697-eae3-47f5-90a3-f943144d37d3.png)
The ~gradient across the tile is very severe; the hot spot at the edge of the petal is ~3x brighter than the dark spot.  
![image](https://user-images.githubusercontent.com/1417841/196775916-6f546092-c3e4-4c48-83be-f279cd454cce.png)
42% moon is 90 deg away; one wouldn't immediately guess moon?  It's not strictly limited to P7, so not a petal thing.

The excess does not really have bright lines.  e.g., comparing the median sky (blue) to the sky in the corner minus the median sky (orange), you get something without lines, except, in the r band, at whatever blue doublet that is at pixel 170 or so.
![image](https://user-images.githubusercontent.com/1417841/196776647-001b7161-6c72-44cc-99e6-d66cffbe5320.png)
Presumably that's useful information?  I'm going to give up and recommend we mark bad and reprocess, but I'll give it another day in case someone is inspired.

**Comment by araichoor** [comment]
in local time, expid=145203 is between 00:18 and 00:39 MST.
if I didn t mess up, here is the all sky camera movie for a large timerange around that exposure (from 23:00 to 01:44 MST):
https://user-images.githubusercontent.com/61986357/197601984-c2de8ceb-99a5-4097-a989-d454e8d3761e.mp4

in case github doesn t like mp4 files, here is a snapshot during expid=145203:
<img width="1023" alt="Screen Shot 2022-10-24 at 11 49 44 AM" src="https://user-images.githubusercontent.com/61986357/197602781-9d50464b-69ff-48ea-bfc4-2289d9e9bec5.png">

there is this super-bright object in the middle of the sgc, where this tile approximately is.
some planet? (but I guess that nts knows about planets, no?); some supernovae?

**Comment by schlafly** [comment]
Good call!  NTS keeps planets two deg away (i.e., 0.5 deg off the focal plane) but not more than that. https://github.com/desihub/desisurvey/blob/main/py/desisurvey/data/config.yaml#L152-L159
Looks like Jupiter.  I guess we could increase the avoidance radius on Jupiter (and maybe Venus, though I have trouble imagining Venus is ever actually a problem?) to 2.5 or 3 degrees.  IIRC these distant PSF wings are often 1/r^2 so that would reduce the amount of contamination by a factor of 4 or 9.

**Comment by araichoor** [comment]
cool.
I definitely want to "automatize" the generation of such movies (like one per night? one per exposure?), and adding stuff like the field-of-view of the taken exposure..
(btw I made those with the `desipoint` tool, works great).

**Comment by araichoor** [comment]
if I didn t mess up, same movie, but with showing where the telescope is pointing (note that the circle size is a kind of random, ie the field of view could be different):
https://user-images.githubusercontent.com/61986357/197877654-4484dab8-fb50-4e13-a82c-b065a68eba66.mp4
one nicely sees that expid=145203 is the one close to jupiter :)

it s on the "left part" of the circle, so ~consistent with petal=7 (even from that plot, it looks to me it could have been petal=8, but I don t know how accurate is the plotted position).

**Comment by araichoor** [comment]
actually, I think the plotting positions are not super-accurate, so we shouldn t over-interpret those plots..

as a test, I just overplotted here those three bright stars:
```
    alf_And  2.096916 29.090431
    alf_Cet 45.569888 4.089739
    alf_Peg 346.190223 15.205267
```
[those are the J2000 coordinates from http://simbad.u-strasbg.fr/simbad; I think the proper-motion position change is negligible, right?]

<img width="767" alt="Screen Shot 2022-10-26 at 9 52 09 AM" src="https://user-images.githubusercontent.com/61986357/198087897-5ec7dc9d-f35f-4367-98c0-e980064f0137.png">

the circles are not properly centered on the stars.
and the offset is not the same for the three stars, so I don t know.. maybe some distortions in the all-sky camera images?

the (ra,dec) to (x,y) conversion is here: https://github.com/dylanagreen/desipoint/blob/b75c08f5468272935c58993ef83a4163542cda90/desipoint.py#L21-L65

**Comment by schlafly** [comment]
For the record, since it's easy and I know how to, I increased the separation radius for Jupiter to 2.5 deg from 2 deg.  That won't be enough to bring the impact to nothing, but it will make it >4x smaller (light should go down like ~4x; should also be better fit by linear gradient in petal).

**Comment by schlafly** [comment]
@akremin , pinging on this outstanding low dec tile.  Let's mark 20221001, expid 145203 P7 on tileid 6984 bad and reprocess, thanks!

**Comment by akremin** [comment]
p7 on 145203 has been marked as bad and the exposure+tile reprocessed. I've rerun the daily files and regenerated nightqa.

**Comment by schlafly** [comment]
Looks good, now good in QA, closing.
