### ISSUE TITLE
Exposure 146762 on Tile 23014 needs to be marked as bad

### ISSUE THREAD

**Issue by geordie666** [desihub/desisurveyops#68]
The exposure looks pretty terrible and there are anomalies in the redshift distribution on the tile. Exposure 146762 was the first bright exposure after a series of backup exposures and only accumulated 77s of effective time in 1224s of exposure time.

If we remove exposure 146762 and reprocess, there should be enough effective time on the tile from exposure 146763, so there's no real reason to retain exposure 146762.
<img width="842" alt="146762" src="https://user-images.githubusercontent.com/13952581/195225838-61419283-1181-48c9-a070-dec6459af7be.png">
<img width="1379" alt="23014" src="https://user-images.githubusercontent.com/13952581/195225844-614661ab-f23f-4c3d-8414-878ae096484b.png">

**Comment by akremin** [comment]
146762 has been marked as bad and the tile reprocessed with just 146763. I've rerun the daily files and regenerated nightqa. 23014 is now ready for QA.

**Comment by schlafly** [comment]
@ashleyjross , can you tell me how egregious the new n(z)/n(z)_ref of 0.94 is?  There's a tail of redshifts to high redshift that I don't really like, making me inclined to reject the remaining exposure as well---even though the sframesky residuals don't look that bad.  But maybe it's just that this exposure is now "only" 20% overexposed and we should expect a little bit worse than average behavior.  But 0.94 sounds bad for the bright program to me.

**Comment by ashleyjross** [comment]
Looking through the night, 0.94 seem reasonable enough to me given the efftime. I see the tail you point out, but is there anything that actually looks wrong with the data?

**Comment by schlafly** [comment]
Not especially---the sframesky looks not good, but fairly average given the very bright sky.  It's just a formerly bad exposure taken in very bright conditions with somewhat less overexposure than typical in those conditions, additionally with a somewhat suspect redshift distribution.

**Comment by ashleyjross** [comment]
I think it meets our standards for acceptance. See TILEID 25529 from earlier in the night.
