### ISSUE TITLE
Exposure 147196 on Tile 24475 includes a strange feature on Petal 2

### ISSUE THREAD

**Issue by geordie666** [desihub/desisurveyops#69]
I'm marking Tile 24475 as "unsure" because of the strange feature in Petal 2 for Exposure 147196 in the sframe image. The redshifts actually look good for Petal 2 in Tile QA (!), but just to be safe we should try to determine what caused this feature.
<img width="1005" alt="147196" src="https://user-images.githubusercontent.com/13952581/195406080-b24e809b-b6c5-4846-b1ae-133b48421ad6.png">
<img width="1230" alt="24475" src="https://user-images.githubusercontent.com/13952581/195406106-cf443b2d-6f66-4048-926c-bde90a0249cb.png">

**Comment by schlafly** [comment]
I think this is just the worst cosmic ray shower I've seen?
![image](https://user-images.githubusercontent.com/1417841/196522222-46b1ba2f-e634-4b01-9a77-6f077d05169e.png)
But given the negative residuals in the sky residuals away from the core of the shower I'm inclined to say that something has gone very bad and we should mark this petal as bad.

**Comment by julienguy** [comment]
Amazing image.

**Comment by schlafly** [comment]
@akremin , we need to mark r2 on 20221009/147196, tileid 24475 as bad and reprocess.

**Comment by forero** [comment]
Could this be originated by GRB_2021009A? 

https://www.astronomerstelegram.org/?read=15650 

https://www.nasa.gov/feature/goddard/2022/nasa-s-swift-fermi-missions-detect-exceptional-cosmic-blast

> At 2022-10-09 14:10:17 UT, the Swift Burst Alert Telescope (BAT) triggered and located the new transient Swift J1913.1+1946 (triggers=1126853 and 1126854). Swift slewed immediately to the location. The BAT on-board calculated location is RA, Dec 288.263, +19.803.

The tile was observed ~16 hours later at 2022-10-10 8:05 UT on RA, Dec 102.224, +59.193

**Comment by forero** [comment]
I guess the relevant location is the GRB with respect to the CCD. At the time of the exposure the GRB was about to set (Alt, Az=0,81) 
<img width="843" alt="Screen Shot 2022-10-24 at 4 40 46 PM" src="https://user-images.githubusercontent.com/1848618/197642950-a29982ec-4a01-409f-bab2-b1ab7c47976b.png">


In what direction are the red CCDs pointing to?

**Comment by forero** [comment]
@ClairePpt said on slack that the CCD is facing west, roughly towards the GRB at the time of the CCD event.

**Comment by schlafly** [comment]
Looks good, marked good in QA, closing.
