### ISSUE TITLE
Exposures 150036-150037 on Tile 8705 have excess z~0 fibers

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#71]
This was a split dark exposure, where the SOs [noted in the night log](https://data.desi.lbl.gov/desi/users/raichoor/kpno_nightlogs/20221024_nightlog_kpno.html) that survey speed was fluctuating, indicating rapidly changing conditions.

Anand noticed some striping features in the sframes that are not present in previous or subsequent exposures.
![Screen Shot 2022-10-26 at 4 08 00 PM](https://user-images.githubusercontent.com/7385438/198132002-4ffcfcf8-aa2e-429b-904d-2d5e46b01001.png)

This is his plot of the normalized _z_ distributions in petals 7 and 8:
![tmp](https://user-images.githubusercontent.com/7385438/198132134-3b07c1df-4fe2-4556-bcc1-cf7326bdf85e.png)

Nothing else in the night log or Nightwatch stands out, and nothing is particularly unusual about the [observing field](https://www.legacysurvey.org/viewer-desi/?ra=58.437&dec=-3.531&zoom=8&layer=ls-dr9) (no really bright stars, for example).

**Comment by araichoor** [comment]
from the slack thread, it looks like it s petal=8 which is the most affected (https://desisurvey.slack.com/archives/C01HNN87Y7J/p1666813972136769).

if useful, here are the 85 spectra from petal=8 with -0.001 < z < 0.001: https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/tmp-tileid80705-petal8-z0.001.pdf

and here is their sky position of all fibers with -0.001 < z < 0.001, which also looks dubious for petal=8:
https://www.legacysurvey.org/viewer-desi/?ra=58.437&dec=-3.531&layer=ls-dr9&zoom=8&desifoot=58.4370,-3.5310&catalog=tmpzwre12ys

<img width="1384" alt="Screen Shot 2022-10-26 at 1 57 33 PM" src="https://user-images.githubusercontent.com/61986357/198136324-7f2d082b-6898-456c-b77c-00033ee67efa.png">

one interesting check could be to look if we did observe some tiles overlapping the outer part of petal=8, and look at those.

**Comment by schlafly** [comment]
This is https://github.com/desihub/desispec/issues/1861 where spatial variability of nebular MW emission lines lead to incorrect redshifts.  We've been marking these as good; I would continue to do that here.

**Comment by araichoor** [comment]
I thought it was different, because the "vertical" lines are present only for _some_ petals, not all.
from what I recalled, those nebular emission lines where present across all petals (as we see on expid=150036-37 for the z-camera, or on the b-camera at pixels~2500).
but maybe my recollection is wrong.
and also, maybe this per-petal thing is just a consequence of some per-petal sky subtraction, I don t know...

**Comment by schlafly** [comment]
This just indicates to me that the nebulosity is concentrated on the part of the sky covered by the leftmost petals.  I think the b camera at pixel ~2500 is the oxygen sky emission line.  It's definitely true that the per-petal sky causes the whole petal to be affected even when only a fraction of the petal actually has emission, because, as you say, it ends up contaminating the sky used for the whole petal.

**Comment by araichoor** [comment]
you re probably right.

to convince myself, I ve grabbed all `(QAFIBERSTATUS==0) & (abs(Z) < 0.001) & ((DESI_TARGET & STD_WD) == 0)` fibers from done dark tiles around.
https://www.legacysurvey.org/viewer-desi/?ra=58.437&dec=-3.531&layer=ls-dr9&zoom=7&desifoot=58.4370,-3.5310&catalog=tmp0jmmy0o6
<img width="1385" alt="Screen Shot 2022-10-26 at 9 32 10 PM" src="https://user-images.githubusercontent.com/61986357/198192006-64ffea54-d615-430b-bead-70d521855b27.png">

and there is a clear structure here! I don t know if other experiments traced those with such accuracy :)
maybe it s a nice desi by-product.

in case people are interested:
tileids = [2507, 4005, 4044, 5569, 7134, 8702, 8704, 8705, 10302, 11828]
in those 2472 fibers, there are 10% LRG, 61% ELG, 12% QSO-only, 7% SKY, 8% SCND_ANY-only.

**Comment by sybenzvi** [comment]
Neat plot! This is quite a big patch of sky, so the spatial resolution of the DESI spectroscopy could well be unique. Seems like it's worth sharing with the MW Science WG.

Based on precedent, it also seems we should mark this tile as good. We'll do that during QA today and close the ticket after.

**Comment by sybenzvi** [comment]
Changed 20221024-8705 from unsure to valid.
