### ISSUE TITLE
Exposure 150175 on Tile 23108: low EFFTIME in all of petal 9.

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#72]
Most of petal 9 has unusually low EFFTIME for this BRIGHT exposure at 05:28 MT, the last complete exposure of 20221025. Clearly, the sky background would have been increasing rapidly, but only this petal was affected. Logged tile as `unsure` during QA.

Nothing unusual was noted in the [night log](https://data.desi.lbl.gov/desi/users/raichoor/kpno_nightlogs/20221025_nightlog_kpno.html).

![Screen Shot 2022-10-27 at 9 36 22 PM](https://user-images.githubusercontent.com/7385438/198445492-19eee396-d9c4-4453-a437-b17b45e62a64.png)

**Comment by araichoor** [comment]
I think it s a consequence that petal=9 has been discarded in the first exposure on 23108, no?

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/23108/20220406/tile-qa-23108-thru20220406.png
<img width="1384" alt="Screenshot 2022-10-27 at 7 34 49 PM" src="https://user-images.githubusercontent.com/61986357/198472212-acce0593-a34a-4700-8ae9-20517b8c4dbe.png">

**Comment by schlafly** [comment]
Thanks Anand.  Yes, this exposure has a history.
https://github.com/desihub/desisurveyops/issues/38
We had an issue back in April that the first exposure of the night was out of focus.  We already marked the first exposure on this tile bad for this reason; now we'll also be marking the second.

@akremin , can you mark 20220406/128896 on tileid 23108 as bad and reprocess, and we'll repeat QA?

**Comment by akremin** [comment]
I have marked 20220406/128896 as bad and rerun the redshifts for tile 23108 for the remaining nights of observations (20221024 and 20221025). I have rerun the daily tables and nightqa for all three impacted nights.

**Comment by schlafly** [comment]
I've updated tiles-specstatus and cleared QA; closing.
