### ISSUE TITLE
reprocess expid 154146-154151 (tileid 25007, 22852, 25935, 24351, 24387), night = 20221121

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#78]
Exposures from 20221121 were reprocessed on 12/1 after a pileup of non-TGT redshifts at z~0.9 was observed in nearly all MAIN BRIGHT tiles. The exposures listed here still have the pileup. They were marked as good during initial QA on 11/28 but should be reclassified as unsure and reprocessed.

An example of the pileup is shown below (see upper right plot):
![Screen Shot 2022-12-02 at 1 23 06 PM](https://user-images.githubusercontent.com/7385438/205360386-642726cc-2d3d-4f02-a3e6-55bb64aedb55.png)

**Comment by schlafly** [comment]
The z ~ 0.9 pile up of yellow non-TGT sources is unrelated (though Anand and I haven't understood that either, yet).  Those sources all have flux = ivar = 0 and aren't actually causing problems.  The spurious sources at z ~ 1.8 are what is coming from the unstable amplifiers.

We want to mark expid 154146-154151 (tileid 25007, 22852, 25935, 24351, 24387), night = 20221121 as bad and reprocess.  I think Segev is marking the tiles as unsure in QA so that we can proceed with an MTL update in the interim.

**Comment by schlafly** [comment]
Note: the issue here is that the bias or dark are not stable for these instruments yet after a recent restart.  It's possible these could be recovered with --bkgsub-for-science but the amplitude is quite large to be pretty clear even on these bright tiles.  I'm suggesting we just give up on these.

**Comment by sybenzvi** [comment]
Confirming that these tiles are now marked as unsure.

**Comment by marcelo-alvarez** [comment]
@schlafly do I need to mark expid 154146-154151 (tileid 25007, 22852, 25935, 24351, 24387), night = 20221121 as bad and reprocess?

**Comment by schlafly** [comment]
Yes, thank you!

**Comment by marcelo-alvarez** [comment]
@schlafly I have marked the exposures above as bad and reprocessed with desi_tsnr_afterburner. The corresponding rows in the exposures-daily
```
rows matching tiles
  25007, 22852, 25935, 24351, 24387
in
  /global/cfs/cdirs/desi/spectro/redux/daily/exposures-daily.csv

TILEID EXPTIME  EFFTIME_SPEC  NIGHT   EXPID
------ -------- ------------ -------- ------
 25007  1053.30         0.00 20221121 154146
 22852   803.10         0.00 20221121 154147
 25935   949.90         0.00 20221121 154149
 24351   658.40         0.00 20221121 154150
 24387  1010.90         0.00 20221121 154151
```
and tiles-daily
```
rows matching tiles
  25007, 22852, 25935, 24351, 24387
in
  /global/cfs/cdirs/desi/spectro/redux/daily/tiles-daily.csv

TILEID NEXP EXPTIME  EFFTIME_SPEC LASTNIGHT
------ ---- -------- ------------ ---------
 25007    1  1053.30         0.00  20221121
 22852    1   803.10         0.00  20221121
 25935    1   949.90         0.00  20221121
 24351    1   658.40         0.00  20221121
 24387    1  1010.90         0.00  20221121
```
files look good to me. 

Please have a look, thanks.

**Comment by schlafly** [comment]
This looks good to me.  I've cleared QA and am closing.
