### ISSUE TITLE
redshift pileup in P9 for expid 154154-154158, 154164-156165 (tiles 8957, 1165, 7438, 10267), night=20221121

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#79]
A large set of MAIN DARK tiles from 20221121 have a pileup of redshifts at z~0.5 in P9. These were marked as good in QA; remarking as unsure for now.

An example of the pileup is shown in the z vs. fiber plot:

![Screen Shot 2022-12-02 at 1 28 48 PM](https://user-images.githubusercontent.com/7385438/205361250-45983451-426f-400d-a60d-a745a02c6041.png)

**Comment by sybenzvi** [comment]
From **20221123**, add the following exposures with the same issue:
* expid 154511, tile 3112
* expid 154512-154513, tile 4682

**Comment by schlafly** [comment]
Note: these are related to bias / dark instabilities on these nights and could probably be saved with --bkgsub-for-science.

**Comment by sybenzvi** [comment]
Confirming that these tiles are now marked unsure in QA.

**Comment by marcelo-alvarez** [comment]
@schlafly do I need to mark expid 154154-154158, 154164-156165, 154511-154513 (tileid 8957, 1165, 7438, 10267, 3112, 4682), night = 20221121, 20221123 as bad and reprocess?

**Comment by schlafly** [comment]
Yes.  Please also add 20221123/154511 tileid 3112; 20221123/154512-154514, tileid 4682.  Thank you!

**Comment by marcelo-alvarez** [comment]
@schlafly I have marked the exposures above as bad and reprocessed with desi_tsnr_afterburner. The corresponding rows in the exposures-daily
```
rows matching tiles
  8957, 1165, 7438, 10267, 3112, 4682, 3112, 4682
in
  /global/cfs/cdirs/desi/spectro/redux/daily/exposures-daily.csv

TILEID EXPTIME  EFFTIME_SPEC  NIGHT   EXPID
------ -------- ------------ -------- ------
  8957   637.40       111.00 20221116 153724
  8957  1220.80         0.00 20221121 154154

  1165  1066.80         0.00 20221121 154155
  1165  1215.10         0.00 20221121 154156

  7438   994.20         0.00 20221121 154157
  7438  1127.00         0.00 20221121 154158

 10267  1462.80         0.00 20221121 154164
 10267  1360.70         0.00 20221121 154165
 10267   470.40       241.60 20221210 157278

  3112  1240.30       445.50 20221112 153116
  3112  1468.20         0.00 20221112 153117
  3112  1641.40         0.00 20221123 154511

  4682  1412.50         0.00 20221123 154512
  4682  1255.30         0.00 20221123 154513
  4682  1127.70         0.00 20221123 154514

  3112  1240.30       445.50 20221112 153116
  3112  1468.20         0.00 20221112 153117
  3112  1641.40         0.00 20221123 154511

  4682  1412.50         0.00 20221123 154512
  4682  1255.30         0.00 20221123 154513
  4682  1127.70         0.00 20221123 154514
```
and tiles-daily
```
rows matching tiles
  8957, 1165, 7438, 10267, 3112, 4682, 3112, 4682
in
  /global/cfs/cdirs/desi/spectro/redux/daily/tiles-daily.csv

TILEID NEXP EXPTIME  EFFTIME_SPEC LASTNIGHT
------ ---- -------- ------------ ---------
  8957    2  1858.20       111.00  20221116
  1165    2  2281.80         0.00  20221121
  7438    2  2121.20         0.00  20221121
 10267    3  3293.90       241.60  20221210
  3112    3  4349.90       445.50  20221112
  4682    3  3795.50         0.00  20221123
  3112    3  4349.90       445.50  20221112
  4682    3  3795.50         0.00  20221123
```
files look good to me. Please have a look.

Tile 10267 has a good exposure 157278 from 20221210 that will be re-processed when Perlmutter is back up. I can update here when that is done if that is helpful.

**Comment by schlafly** [comment]
Looks good.  I've cleared QA and am closing, thanks!
