### ISSUE TITLE
petal 4 bad QAFIBERSTATUS in exp 154934, tile 9788, night 20221126

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#81]
Every fiber in petal 4 for exp 154934 has bad QAFIBERSTATUS. No obvious problems with throughput or efftime, and no previous exposure on this tile were made. This pattern is not observed in other DARK or BRIGHT exposures on 20221126.

![Screen Shot 2022-12-02 at 3 30 24 PM](https://user-images.githubusercontent.com/7385438/205380708-a726385d-352f-4d16-abb5-a1aa5d618fa2.png)

**Comment by schlafly** [comment]
Connie diagnosed this as a cosmic blasting the overscan here:
https://desisurvey.slack.com/archives/C01HNN87Y7J/p1669954915042819
We only lose a half amp and Julien's spent a while mitigating these before, so we'll just accept it.  I've marked this as good.  Closing.
