### ISSUE TITLE
Sky was very bright for TILEID=6991 through NIGHT=20221113

### ISSUE THREAD

**Issue by geordie666** [desihub/desisurveyops#83]
The sky was very bright for tile 6991 on 11/13. The redshifts look reasonable, but there are ZSKYCHI2PDF alerts across multiple petals:

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/6991/20221113/tile-qa-6991-thru20221113.png

From Eddie on Slack:

_The sky is really quite bright for 6990 and 6991.  Let's mark the former as good and make a ticket for the latter as unsure; I'll probably ask for it to be marked bad._

**Comment by marcelo-alvarez** [comment]
@schlafly do I need to mark exposure 153314 (tile 6991) as bad and reprocess?

**Comment by schlafly** [comment]
Sorry, you're ahead of me, awesome.  Yes, let's go ahead and mark both 153313 and 153314 on 6991 as bad and reprocess due to the slight pileup at z=1.4 and 1.8.  Thanks!

**Comment by marcelo-alvarez** [comment]
@schlafly to clarify for 20221113, can you fill in the "BAD" column with "yes" or "no" below? Thanks!
```
TILEID   EXPID  BAD
  6990  153312    ?
  6990  153313    ?
  6991  153314    ? 
  6991  153315    ?
```

**Comment by schlafly** [comment]
Thank you for catching my error.  This looks good to me.  I will reQA and close.
