### ISSUE TITLE
Poor z-band sky on night 20221207 led to an excess of redshifts near z~1.7 for tiles 22879 and 22886

### ISSUE THREAD

**Issue by geordie666** [desihub/desisurveyops#84]
The SKYCAM was down on 20221207, which may have led to lower-than usual exposure times. Tiles 22879 and 22886, in particular, had particularly bad z-band sky, leading to an excess of redshifts near z~1.7:

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/22879/20221207/tile-qa-22879-thru20221207.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/22886/20221207/tile-qa-22886-thru20221207.png

The related sframesky plots are here:

https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20221207/sframesky-20221207.pdf

**Comment by schlafly** [comment]
20221207/156881 (22886) and 20221207/156885, 20221207/156886 should be marked bad and reprocessed.

**Comment by marcelo-alvarez** [comment]
@schlafly I have marked the exposures above as bad and reprocessed with desi_tsnr_afterburner. The corresponding rows in the exposures-daily
```
rows matching tiles 
  22879, 22886 
in
  /global/cfs/cdirs/desi/spectro/redux/daily/exposures-daily.csv

TILEID EXPTIME  EFFTIME_SPEC  NIGHT   EXPID 
------ -------- ------------ -------- ------
 22879  1078.00         0.00 20221207 156885
 22879   795.70         0.00 20221207 156886

 22886   992.00         0.00 20221207 156881
 22886   121.80         0.00 20221207 156882

```
and tiles-daily
```
rows matching tiles 
  22879, 22886 
in
  /global/cfs/cdirs/desi/spectro/redux/daily/tiles-daily.csv

TILEID NEXP EXPTIME  EFFTIME_SPEC LASTNIGHT
------ ---- -------- ------------ ---------
 22879    2  1873.70         0.00  20221207
 22886    2  1113.90         0.00  20221207
```
files look good to me. Please have a look.

**Comment by schlafly** [comment]
Thanks, looks good.  I've reset QA and am closing.
