### ISSUE TITLE
Exposure 157267 for tertiary tile 83219 on night 20221210 should be marked as bad

### ISSUE THREAD

**Issue by geordie666** [desihub/desisurveyops#85]
Exposure 157267 for tertiary tile 83219 on night 20221210 had very low efftime:

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/83219/20221210/tile-qa-83219-thru20221210.png

It's possible we were unguided during this exposure. Regardless, we're going to repeat the observation in full and so exposure 157267 should be marked as bad.

**Comment by araichoor** [comment]
@marcelo-alvarez : I notice that this 157267 exposure is still not flagged as "bad".
it s not super-critical, as:
- observing queries are made manually for this tertiary15 program, and we know we should ignore it (so re-observed this tile on 20221214)
- I perform on my side the cross-tiles redux, where I can manually discard it.

but it would sound safer to flag it, still (sorry to add more on your plate!)

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/83219/20221214/tile-qa-83219-thru20221214.png
<img width="1383" alt="Screenshot 2022-12-15 at 9 44 22 AM" src="https://user-images.githubusercontent.com/61986357/207931347-e30e5cf4-9593-4929-a1da-748ebd4521c5.png">

```
>>> d[d["FAPRGRM"] == "tertiary15"]["NIGHT", "EXPID", "TILEID", "EFFTIME_SPEC"]
<Table length=25>
 NIGHT   EXPID  TILEID    EFFTIME_SPEC   
 int32   int32  int32       float64      
-------- ------ ------ ------------------
20221129 155693  83210  495.4139099121094
20221129 155694  83210  603.6492309570312
20221129 155695  83211  539.1722412109375
20221129 155696  83211  489.9026184082031
20221129 155697  83212  999.3721313476562
20221129 155698  83213  986.1234130859375
20221129 155699  83214  994.7094116210938
20221129 155700  83215  528.4810791015625
20221129 155701  83215  411.0719909667969
20221129 155702  83216  911.3710327148438
20221129 155703  83217    928.19482421875
20221129 155704  83218  885.4429931640625
20221210 157267  83219  280.9227600097656 # <= EFFTIME_SPEC should be zero
20221210 157268  83220 1111.5369873046875
20221210 157269  83221  1173.926025390625
20221210 157270  83222  1196.331298828125
20221210 157271  83223 1166.7371826171875
20221210 157272  83224 1195.4879150390625
20221210 157273  83225  550.1837768554688
20221210 157274  83225    628.25146484375
20221210 157275  83226  626.2041625976562
20221210 157276  83226  633.7552490234375
20221214 158188  83219 1043.6629638671875
20221214 158189  83227  992.8746948242188
20221214 158190  83228 1011.4068603515625
```

**Comment by marcelo-alvarez** [comment]
No worries @araichoor and thanks for the reminder. I am still getting up to speed on how different pipeline activities depend on one another and appreciate your patience as I sort it all out!

**Comment by marcelo-alvarez** [comment]
This exposure has been marked as bad, i.e.
```
% grep 157267 exposure_table_20221210.csv
157267,science,83219,ignore,a0123456789,,,1342.749,1038.423218,special,main,tertiary15,1000.0,dark,1.05072474013287,1.435424,-99.0,35.623479,-4.8357,1,1,tertiary15,main survey,59924.107212506,20221210,|,|,low efftime; see desisurveyops-85|
```

Closing this ticket.

**Comment by schlafly** [comment]
We need this to get propagated to the exposures-daily.csv file; it is currently still assigned 280.9 effective seconds.
$ cat /global/cfs/cdirs/desi/spectro/redux/daily/exposures-daily.csv | grep 157267
20221210,157267,83219,35.617,-4.826,59924.10721249,special,other,tertiary15,specialtertiary15,1342.7,280.9,1000.0,other,0.85,1.435,0.025,0.848,1038.4,36.2,9.6,23.1,31.7,2097.2,3237.4,589.1,5233.2,280.9,311.2,293.6,374.2,271.4,308.2,370.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.678,20.338,18.973,0.0,0.0,0.0,0.0

**Comment by marcelo-alvarez** [comment]
@schlafly I was just about to re-open, I'm doing that now.

**Comment by schlafly** [comment]
Looks good, closing!
