### ISSUE TITLE
Device restart around expid 157134 on 20221209 leads to horrible sframeskies; unstable amplifiers?

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#88]
The spectrograph CCDs (?) were restarted before expid 157134 on 20221209, leading to some horrible looking residuals.
![image](https://user-images.githubusercontent.com/1417841/208902030-f3fd79ca-bda6-4825-9d55-b2836471f1f2.png)
I think we may have missed this because they were on special M31 tiles for which we don't have the usual QA.

Going back, I would probably mark the exposures through 157148 as bad (157134-157148; tileid 22856, 22855, 23823, 22425, 24563, 25257).  These have been QAed as good and committed to the MTL ledgers, though, so if we decide to remove them, it will take more than the usual amount of effort.  They are all bright tiles where the MTLs are less important (no LyA decisions).  They could probably be saved by bkgsub-for-science (?), though someone would have to experiment, and I've just given up on that on a number of other issues.

@geordie666 , thoughts about how annoying it would be to extract these from the MTLs?  I actually forget our procedure here!  Did we end up making new tiles at these locations?

**Comment by geordie666** [comment]
We "reprocess" tiles as follows:

- (1) Stephen (or someone similar) re-archives the tiles. This gives them a second (or third, etc.) "archived" directory with a new `ARCHIVEDATE` and changes their `ARCHIVEDATE` in the tiles file.
- (2) I execute `run_mtl_loop` with the `--reprocess` [option](https://github.com/desihub/desitarget/blob/2.6.0/bin/run_mtl_loop#L31-L32). This magically reverts all of our poor redshift choices and replaces them with the updated choices. This also adds an additional line in the `mtl-done-tiles` files that includes the new `ARCHIVEDATE`, which is then adopted by downstream codes.

**Comment by schlafly** [comment]
Sorry, going back through old issues---what does re-archiving look like for a tile where we've just marked it as bad and aren't processing it anymore?

**Comment by geordie666** [comment]
I have a function to completely remove a set of tiles from the MTL ledgers:

https://github.com/desihub/desitarget/blob/2.6.0/py/desitarget/mtl.py#L887
(this function would need to be run once with `secondary=True` and once with `secondary=False`).

But, I also have a tool to check whether we've already observed an overlapping tile:

purge_mtl BRIGHT --isodate 2022-12-08T19:36:28+00:00 
(DO **NOT** ADD THE KEYWORD --purge TO THIS COMMAND!)

According to that tool, we haven't observed overlapping tiles for:

`22856`, `23823`, `24563`, `25257`

and we _have_ for:

`22855`, `22425`

Obviously we can't just purge tiles where we've already observed overlapping targets based on the MTL decisions.

If you want, I could take a go at removing tiles `22856`, `23823`, `24563`, `25257` and committing the resulting ledgers to svn? I'd want a little time to update my `purge_mtl` code to allow a preferred set of tiles to be specified.

But, I think we have to just take the hit on `22855` and `22425`. These are bright tiles, so it would be a mild hit.

I'd also love an independent confirmation that I'm correct that we've already observed overlapping tiles for `22855` and `22425`.

**Comment by geordie666** [comment]
Alternatively, we could faux-reprocess `22855` and `22425` by:
- Marking _all_ the redshifts as bad (setting either the `BAD_SPECQA` or `BAD_PETALQA` flags, or, most likely, the `NODATA` flag in the files produced by the spectroscopic pipeline). 
- Rearchiving these tiles with all-bad spectra. 
- Running the `desitarget.mtl` re-processing code to pick up the new archive dates on those tiles and re-process them as if they'd had all-bad data.
- Retire those tiles as having been observed.

Then, I think, everything should work consistently in the same way as a standard reprocessing — i.e. only the redshifts from the overlapping tiles would produce MTL decisions, and we would be able to track _why_. I might want to run that idea by @ashleyjross, but I'm 99% sure that's correct.

Note that for `22856`, `23823`, `24563`, `25257` as (I think) these haven't been overlapped, we wouldn't need to retire these tiles once they'd been purged — we could just pretend they were never observed in the first place.

**Comment by schlafly** [comment]
That's more along the lines I was thinking.  Given that these are bright tiles, etc., I don't think we need to try to remove the unoverlapped ones from the MTL.  Let's discuss Monday.

**Comment by geordie666** [comment]
I think you're saying that we should proceed by faux-reprocessing _all 6_ tiles according to my bullet points above, rather than just `22855` and `22425` — and then we'd retire all six tiles as having been observed. That would be fine by me.

Unfortunately, Monday is the meeting where I can only attend for 10 minutes due to a clash. But we could discuss this in the first 10 minutes, or a select group of us could have a short meeting later in the week. Or, if we could convince Stephen, we could steal some time from the DESI Data meeting on Tuesday morning. Faux-reprocessing will likely require some handling by the spectro folks, so stealing some time from DESI Data would be reasonable.

**Comment by ashleyjross** [comment]
I think everything works as long as any changes are associated with the re-archived tiles.

I'm not hugely concerned, though, as long as we maintain the ability to flag the bad data as bad for any eventual data assembly. Ideally, that bad info gets propagated back to the MTL at some point (we had discussed updating MTLs after a data release and I'm still very in favor of this).

On can imagine a scenario where these exposures are flagged as bad, this info is thus known in the associated data assembly, and then picked up by the MTL. Then, when we have nominally completed bright time and likely considering things like extra layers, we prioritize tiles where the completeness is low (like it would be in this area because the data ended up being bad).

We will almost definitely have scenarios like that that have not been caught so quickly and I think we should be preparing for it no matter what we decide about this issue.

**Comment by schlafly** [comment]
For this ticket, we'd also like to mark some tiles / petals as bad and reprocess.  These are also committed to the ledger and so require special reprocessing treatment (producing ~empty / masked zmtl files for entirely masked petals, where @sbailey is reviewing the procedure).  The affected expid are 20221209, 157134-157148; tileid 22856, 22855, 23823, 22425, 24563, 25257, plus 83200, 83201, 83202 (though those aren't main survey tiles and don't affect the MTLs).

The usual policy is min number of good fibers = 3000.
https://github.com/desihub/desispec/blob/main/py/desispec/data/qa/qa-params.yaml#L60C34-L60C34
So that means we need at least seven good petals.  r3, 4, 5, 9 are all pretty bad, so I think the easiest thing would be to mark the whole exposures as bad for that whole range.

Especially for the M31 tiles (83200, 83201, 83202) that seems deeply unfortunate, so for those tiles we could imagine instead marking z1, z6, z9, r3, r4, r5, r6, r9 as bad.  That leaves petals 0, 2, 4, 7 untouched.

**Comment by schlafly** [comment]
@akremin (or someone else?), can you mark z1, z6, z9, r3, r4, r5, r6, r9 as bad for 20221209, 157134-157148, tileid 22856, 22855, 23823, 22425, 24563, 25257, 83200, 83201, 83202?  Then we'll need @geordie666 to rearchive and readd to the MTLs.

**Comment by schlafly** [comment]
Pinging this ticket.

**Comment by schlafly** [comment]
Let's mark the whole exposure as bad for 157140-157148, tileid 22856, 22855, 23823, 22425, 24563, 25257.  

Then let's only mark z1, z6, z9, r3, r4, r5, r6, r9 for tileid 83200, 83201, 83202, expid 157134-157139 (M31 tiles where people might want to try to deal with the remaining good petals).

**Comment by abhi0395** [comment]
@schlafly Re-processed except tile 83200. tsnr+nightqa updated. Some issue with 83200 (ticket (#134) is mentioned describing the problem)

**Comment by schlafly** [comment]
@abhi0395 , these still show up in the nightqa here?
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20221209/tileqa-20221209.pdf
What am I missing?  Thanks!

**Comment by abhi0395** [comment]
Hi @schlafly, thanks for your comment. tiles 22856, 22855, 23823, 22245, 24563, and 25257 (expid: 157140-157148 ) are purged and therefore are not in nightqa. 

83201 and 83202 were reprocessed after marking those cameras as bad (they were also observed on 20221119, so the pipeline used some cameras from that night to create coadds).

83200 could not be processed because it had multiple exposures on 20221209 (exp: 157130, 157131, 157134), and a few r-cameras were marked bad on only one (exp 157134) exposure, which resulted in some errors in standard star selection (#134). So this tile is not updated in nightqa.

**Comment by schlafly** [comment]
Hmm, maybe it was a caching issue.  My issue had been that I did see these tiles in tileqa, but now with a refresh I no longer do.  Sorry!  @sbailey , these look good now, and would be part of a new archiving and eventual re-MTLing.

**Comment by abhi0395** [comment]
Awesome :) thanks @schlafly.

**Comment by schlafly** [comment]
@sbailey , resurfacing this ticket.  expid 157140-157148, tileid 22856, 22855, 23823, 22425, 24563, 25257 were reprocessed and need to be rearchived and recommitted to the MTL.

**Comment by schlafly** [comment]
Following up on this after Stephen's and my discussion last week... I listed 22425 in this list, but that was wrong; 22425 was observed on 20211103 and not on 20221209.  Abhijeet appropriately corrected me and points out that 22245 was instead the problematic tile (note the swapped 2 and 4).  That tile is now marked bad so I think we're set for 20221209. 

However, something is weird with 22425 now; I don't see it under $DESI_SPECTRO_REDUX/daily/tiles/cumulative.  Presumably it was cleared out because I misidentified it here, and now it needs to be restored (?).  I do see it in $DESI_SPECTRO_REDUX/tiles/archive, so maybe we just need to copy that back to daily/tiles/cumulative or something?  Sorry!

**Comment by schlafly** [comment]
I think Stephen did not actually rearchive, due to noticing this issue and potentially not having a mechanism for handling "all petals are bad" in the new rearchive framework.  So we still have to rearchive and re-MTL 22856, 22855, 23823, 22245, 24563, 25257 (now correcting my 2-4 swap for tileid 22245).

**Comment by sbailey** [comment]
@geordie666 @schlafly this case of re-archiving a tile that has been completely removed from a production is a bit delicate, so I've tried it with tile 22856 but would appreciate a downstream MTL-update cross check before I proceed with the other tiles.  I had to restore a blank tiles/cumulative/22856/20221209 directory, and then archive that blank directory:
```
mkdir -p tiles/cumulative/22856/20221209
desi_archive_tilenight --rearchive --badpetals 0,1,2,3,4,5,6,7,8,9 -t 22856
```
This results in daily/tiles/archive/22856/20230920 having the BAD_PETALQA zmtl files, but no other files.  tiles-specstatus.ecsv was also updated with the new ARCHIVEDATE, but it remains in QA=good ZDONE=true state, which isn't obvious to me if that is what we really want.

@geordie666 please confirm that you can MTL update tile 22856 given the current state.  If that works, I'll proceed with the other tiles.

**Comment by geordie666** [comment]
@sbailey: This looks correct from the MTL side. I did a dry run of updating tile `22856`. Here is the progression for some random `TARGETID`s (hopefully spread across petals) for that tile:
```
     TARGETID    TILEID   TARGET_STATE
```
```
39633519672036594    -1 MWS_BROAD|UNOBS
39633519672036594 22856 MWS_BROAD|MORE_ZGOOD
39633519672036594 24428 MWS_BROAD|DONE
39633519672036594 22856 MWS_BROAD|UNOBS
39633519672036594 24428 MWS_BROAD|MORE_ZGOOD
```
```
39633517973342250    -1 MWS_MAIN_RED|UNOBS
39633517973342250 22856 MWS_MAIN_RED|MORE_ZGOOD
39633517973342250 24428 MWS_MAIN_RED|DONE
39633517973342250 22856 MWS_MAIN_RED|UNOBS
39633517973342250 24428 MWS_MAIN_RED|MORE_ZGOOD
```
```
39633526194176518    -1 MWS_MAIN_BLUE|UNOBS
39633526194176518 25997 MWS_MAIN_BLUE|MORE_ZGOOD
39633526194176518 22856 MWS_MAIN_BLUE|DONE
39633526194176518 21322 MWS_MAIN_BLUE|DONE
39633526194176518 25997 MWS_MAIN_BLUE|MORE_ZGOOD
39633526194176518 22856 MWS_MAIN_BLUE|MORE_ZGOOD
39633526194176518 21322 MWS_MAIN_BLUE|DONE
```
```
39633522943593255    -1 BGS_BRIGHT|UNOBS
39633522943593255 22856 BGS_BRIGHT|MORE_ZGOOD
39633522943593255 22856 BGS_BRIGHT|UNOBS
```
```
39633530803716956    -1 MWS_BROAD|UNOBS
39633530803716956 22856 MWS_BROAD|MORE_ZGOOD
39633530803716956 21322 MWS_BROAD|DONE
39633530803716956 22856 MWS_BROAD|UNOBS
39633530803716956 21322 MWS_BROAD|MORE_ZGOOD
```
```
39633517973343103    -1 MWS_BROAD|UNOBS
39633517973343103 22856 MWS_BROAD|MORE_ZGOOD
39633517973343103 22856 MWS_BROAD|UNOBS
```
In each case it is clear that the observation on tile `22856` is corrected to the previous state in the MTL ledgers by the re-processing code.

I think it also makes sense to be in the `QA=good`, `ZDONE=true` state in `tiles-specstatus.ecsv`. Semantically that might not make sense. But I think that corresponds to "we're done with QA and we're done with processing for this tile" which seems correct.

**Comment by sbailey** [comment]
@geordie666 I have rearchived the remaining bad tiles with the commands below and committed the updated tiles-specstatus.ecsv.  Back to you for final MTL updates on these.

```
source $HOME/bin/desi_daily_env.sh
cd $DESI_SPECTRO_REDUX/$SPECPROD
mkdir -p tiles/cumulative/22855/20221209
desi_archive_tilenight --rearchive --badpetals 0,1,2,3,4,5,6,7,8,9 -t 22855
mkdir -p tiles/cumulative/23823/20221209
desi_archive_tilenight --rearchive --badpetals 0,1,2,3,4,5,6,7,8,9 -t 23823
mkdir -p tiles/cumulative/22245/20221209
desi_archive_tilenight --rearchive --badpetals 0,1,2,3,4,5,6,7,8,9 -t 22245
mkdir -p tiles/cumulative/24563/20221209
desi_archive_tilenight --rearchive --badpetals 0,1,2,3,4,5,6,7,8,9 -t 24563
mkdir -p tiles/cumulative/25257/20221209
desi_archive_tilenight --rearchive --badpetals 0,1,2,3,4,5,6,7,8,9 -t 25257
cd $DESI_ROOT/survey/ops/surveyops/trunk/ops
svn commit -m "re-archived bad tiles from 20221209; see desisurveyops #88"
```

**Comment by geordie666** [comment]
MTLs were successfully re-processed for the following tiles:
```
TILEID         TIMESTAMP       VERSION PROGRAM LASTNIGHT ARCHIVEDATE
22245 2023-09-22T22:19:43+00:00 2.6.0   BRIGHT 20221209  20230922
23823 2023-09-22T22:19:44+00:00 2.6.0   BRIGHT 20221209  20230922
25257 2023-09-22T22:19:45+00:00 2.6.0   BRIGHT 20221209  20230922
24563 2023-09-22T22:19:46+00:00 2.6.0   BRIGHT 20221209  20230922
22856 2023-09-22T22:19:47+00:00 2.6.0   BRIGHT 20221209  20230920
22855 2023-09-22T22:19:48+00:00 2.6.0   BRIGHT 20221209  20230922
```
and committed to svn.

**Comment by araichoor** [comment]
@schlafly @geordie666, a question about those six bright tiles (`22245, 22855, 22856, 23823, 24563, 25257`) discussed in this ticket.

those have `STATUS="good"` in the `tiles-main.ecsv`, and `QA="good"` and `EFFTIME_SPEC=0` in the `tiles-specstatus.ecsv`; that sounds awkward to me.

from re-reading this ticket, I *think* that:
- we mistakenly first archived+mtl-updated them (so they got `STATUS="good"` in tiles-main.ecsv`) though data was bogus;
- then we reprocessed with setting all the data as "bad", re-archived and re-mtl-updated with @geordie666's magic;
- *but* we forgot to revert their `STATUS` column in `tiles-main.ecsv`, so we never re-observed those.
is that correct?

context:
we re getting close to complete the original main/bright 4-passes program in the ngc, with a tile observed on 20250509:
![Image](https://github.com/user-attachments/assets/cf3e833d-e851-458f-add8-63974de8992a)

so I was wondering about the tileids of the two remaining tiles at ra,dec~150,75.
but, with checking, those are `22855,22856`; actually the four "holes" in the sgc at dec>-15 are the other four tiles from this ticket.
because, in my status script, I consider as "done" tiles with efftime_spec>0 and status="done".

if useful, here s how those six tiles appear in `tiles-specstatus.ecsv`:
```
TILEID  TILERA TILEDEC EXPTIME EFFTIME_SPEC OBSSTATUS ZDONE LASTNIGHT  QA    USER   OVERRIDE QANIGHT  ARCHIVEDATE
------ ------- ------- ------- ------------ --------- ----- --------- ---- -------- -------- -------- -----------
 22245  46.639  -2.022  1323.7          0.0     other  true  20221209 good adamyers        0 20221209    20230922
 22855 145.408  72.305  2782.4          0.0     other  true  20221209 good adamyers        0 20221209    20230922
 22856 152.511  74.982  1360.7          0.0     other  true  20221209 good adamyers        0 20221209    20230920
 23823  42.441   6.903  2727.8          0.0     other  true  20221209 good adamyers        0 20221209    20230922
 24563  58.744 -14.435  1203.7          0.0     other  true  20221209 good adamyers        0 20221209    20230922
 25257  39.946  14.804  1047.1          0.0     other  true  20221209 good adamyers        0 20221209    20230922
```

**Comment by araichoor** [comment]
in my previous message I wrote that these six tiles had `STATUS="good"` in the `tiles-main.ecsv`: sorry I meant `STATUS="done"`.
I ve edited the message.

**Comment by schlafly** [comment]
They probably are "done" because they are in mtl-done-tiles, which means
they won't be reobserved.  Probably the best thing to do would be to make
new tiles here.

**Comment by araichoor** [comment]
I see, that makes sense.

**Comment by geordie666** [comment]
I retired tiles: 

`22245` , `22855` , `22856`, `23823`, `24563`, `25257` 

and replaced them with tiles:

`30987`, `30988`, `30989` , `30990`, `30991`, `30992`

so we should be good, here now.
