### ISSUE TITLE
Tile 11745 has low efftimes on petals 4+5

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#89]
Tile 11745 observed with exp 159746 on 2022-12-23 has low and variable efftimes across sections of petals 4+5.  Observing conditions were photometric and good, and the night log didn't note anything unusual about this tile.  There's very little reddening on this tile.
![tile-qa-11745-thru20221223](https://user-images.githubusercontent.com/7918018/209452691-e0ef823b-1fc3-4f23-bcde-141433a61c60.png)

**Comment by schlafly** [comment]
This tile barely passed the EFFTIME requirement, and these two petals were given low THRUFRAC, leading them to fall under the minimum fiber EFFTIME.  We have been calling these good; I'd continue to do that in this case.
