### ISSUE TITLE
Dubious z=2.5 objects on all petals on tile 4403

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#9]
There's a dubious set of z=2.5 objects on all petals on TILEID 4403.
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/4403/20220113/tile-qa-4403-thru20220113.png

My suspicion is that this is the fiberflat / humidity code, but I am not sure.
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20220113/sframesky-20220113.pdf
It is remarkable how perfect the humidity correction is at the beginning of the night, and then how it suddenly gets worse for the rest of the night.  If this is actually the cause, then most of the night would benefit from reprocessing.

I can't mark this tile as good since this presumably affects LyA decisions, so this one is relatively high priority.

**Comment by julienguy** [comment]
Yes. This is a night with very low humidity for which the current fiber flat humidity correction code is ineffective (=no correction because on edge of template humidity range).
This causes the pile up at z=2.5, the residual of the mirror throughput dip at ~4300A in misinterpreted as Lya line.

**Comment by schlafly** [comment]
@akremin, it looks to me like the improved fiberflat code is in, so we could reprocess 4403 and then re-QA it, hopefully marking it good?

**Comment by akremin** [comment]
I removed the exposures and reran them using the current `main` branch for Tile 4403 on Night 20220113. I've also rerun the tsnr afterburner and the `desi_night_qa` scripts.

Ready for re-QA

**Comment by schlafly** [comment]
Thanks @akremin, @julienguy.  This tile now looks good.  I've marked this as good and am closing the ticket.
