### ISSUE TITLE
Set EFFTIME_SPEC=0 for EXPID=152996 on 20221111

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#92]
For whatever reason, EXPID=152996 still has `EFFTIME_SPEC>0` (on Jan 8, 2023), though it should have `EFFTIME_SPEC=0`, as it is listed in the bad-guiding exposures list of https://github.com/desihub/desisurveyops/issues/74.

```
>>> d = Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures-daily.fits","EXPOSURES")
>>> d[d["TILEID"] == 21443]["NIGHT","EXPID","TILEID","EXPTIME","EFFTIME_SPEC"]
<Table length=4>
 NIGHT   EXPID  TILEID      EXPTIME         EFFTIME_SPEC   
 int32   int32  int32       float64           float64      
-------- ------ ------ ----------------- ------------------
20221110 152863  21443         1190.9635                0.0
20221110 152864  21443         1176.0957                0.0
20221111 152996  21443 527.4842529296875  98.68692779541016
20230107 162343  21443 643.3032836914062 135.00694274902344
```

Slack thread: https://desisurvey.slack.com/archives/C01HNN87Y7J/p1673219020705959.

ps: I ve verified that it is the only one of the 91 exposures from `badguidingtileexp.ecsv` which has `EFFTIME_SPEC>0`.

**Comment by marcelo-alvarez** [comment]
@araichoor thanks for digging into this. It was an edge case in the reprocessing in which the exposure table entry was updated but the corresponding exposure directory did not get purged. I purged it by hand and re-ran tsnr, and EFFTIME_SPEC is now correct:
```
>>> d = Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures-daily.fits","EXPOSURES")
>>> d[d["TILEID"] == 21443]["NIGHT","EXPID","TILEID","EXPTIME","EFFTIME_SPEC"]
<Table length=4>
 NIGHT   EXPID  TILEID      EXPTIME         EFFTIME_SPEC
 int32   int32  int32       float64           float64
-------- ------ ------ ----------------- ------------------
20221110 152863  21443         1190.9635                0.0
20221110 152864  21443         1176.0957                0.0
20221111 152996  21443          527.4843                0.0
20230107 162343  21443 643.3032836914062 135.00694274902344
```
Please have a look let me know if there is anything else you need.

**Comment by araichoor** [comment]
looks good to me, thanks!
I verified that `tiles-daily.csv` also is updated:
```
>>> d = Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/tiles-daily.csv")
>>> d[d["TILEID"] == 21443]["LASTNIGHT","NEXP","TILEID","EXPTIME","EFFTIME_SPEC"]
<Table length=1>
LASTNIGHT  NEXP TILEID EXPTIME EFFTIME_SPEC
  int64   int64 int64  float64   float64   
--------- ----- ------ ------- ------------
 20230107     4  21443  3537.8        135.0
```

@schlafly : how do we update the info in `tiles-specstatus.ecsv`? (and what info should be updated?)

**Comment by schlafly** [comment]
Sorry @araichoor, can you finish and close out this one too with the desi_update_tiles_specstatus invocation from the other ticket?  Thanks!

**Comment by araichoor** [comment]
sure, done (see [here](https://desi.lbl.gov/trac/changeset?old=2266&old_path=data%2Fsurveyops%2Ftrunk%2Fops%2Ftiles-specstatus.ecsv&new=&new_path=data%2Fsurveyops%2Ftrunk%2Fops%2Ftiles-specstatus.ecsv); I ve proceeded as in https://github.com/desihub/desisurveyops/issues/91#issuecomment-1382342582).
