### ISSUE TITLE
alpha Leo / Leo I leads to poor sky fitting (?) on P6 / P7 of 20230127/164960, tileid 11803

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#98]
![Screenshot from 2023-01-28 18-38-46](https://user-images.githubusercontent.com/1417841/215296046-9806ab7d-c152-4668-aef3-09ee9e310cb5.png)

Some mixture of Leo I and alpha Leo are leading to lots of bad redshifts on P6 of 20230127 / 164960, tileid 11803.  I'm marking this tile as good anyway---we haven't been flagging issues associated with the sky.  But this case is ugly enough to be worth noting, and is particularly troubling because I suspect alpha Leo is actually the problem, but it's on P7 rather than P6 (though near the boundary).  The issue is likely that the P6 skies happen to preferentially sample the region near alpha Leo, but it's pretty clear from the sframesky residuals that we should be able to do better.

**Comment by araichoor** [comment]
if useful, few additional material here:

the current sframesky image:
<img width="975" alt="Screenshot 2023-01-30 at 2 58 21 PM" src="https://user-images.githubusercontent.com/61986357/215616129-7163fe3e-451a-4ffe-843f-34f9c73b0cd7.png">

from the fiberassign files, the `OBJTYPE=="SKY"` fibers position:
https://www.legacysurvey.org/viewer-desi/?ra=151.454&dec=11.618&catalog=tmp5qvev8ib&&layer=ls-dr9&zoom=8&desifoot=151.4540,11.6180
<img width="1384" alt="Screenshot 2023-01-30 at 3 05 39 PM" src="https://user-images.githubusercontent.com/61986357/215616757-a61bbc15-e3d7-4243-a2ec-0bae41871a34.png">

one should indeed check the actual spectra of the petal=6 sky fibers...
